packages:
  - "packages/*"
  - "integrations/*"
  - "tooling/*"
  - "libs/*/*"
  - "examples/*"
  - "examples/pokenerve/*"
  - "presentations/*/app"
  - "testing/*"
  - "websites/*"
  - "tools/specforge/*"
