/**
 * Build script that bundles `.d.ts` files from each `@hex-di/*` package
 * into string-constant TypeScript files for the playground editor.
 *
 * Reads from each package's `dist/index.d.ts` (packages must be built first),
 * uses `dts-bundle-generator` to produce a single bundled `.d.ts`, and writes
 * the result as an exported string constant to `src/editor/generated-types/`.
 *
 * Usage: tsx scripts/bundle-playground-types.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { execSync } from "node:child_process";
import { tmpdir } from "node:os";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const MONOREPO_ROOT = resolve(ROOT, "../..");
const OUTPUT_DIR = resolve(ROOT, "src/editor/generated-types");

const PACKAGES = [
  "core",
  "graph",
  "runtime",
  "result",
  "flow",
  "store",
  "query",
  "saga",
  "tracing",
  "logger",
] as const;

function packageDir(name: string): string {
  // Most packages live in packages/<name>, but some live in libs/<name>/core
  const standardPath = resolve(MONOREPO_ROOT, "packages", name);
  if (existsSync(standardPath)) return standardPath;
  const libPath = resolve(MONOREPO_ROOT, "libs", name, "core");
  if (existsSync(libPath)) return libPath;
  return standardPath;
}

function escapeForTemplate(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

/**
 * Normalize brand properties for cross-module compatibility in Monaco.
 *
 * dts-bundle-generator inlines types from workspace dependencies, so each
 * package bundle gets its own `declare const __brand: unique symbol` and
 * uses computed property keys like `readonly [__brand]: [T, TName]`.
 *
 * Monaco bundles TypeScript ~5.4, which cannot infer through computed
 * symbol property keys across separate `declare module` blocks. Even with
 * plain `symbol` (not `unique symbol`), the inference fails in TS 5.4.
 *
 * This function converts computed symbol brand properties to regular string
 * properties and removes the symbol constant declarations entirely:
 *   - `declare const __brand: unique symbol;` → removed
 *   - `readonly [__brand]: [T, TName]` → `readonly __brand: [T, TName]`
 *   - `readonly [__graphBrand]?: [...]` → `readonly __graphBrand?: [...]`
 *
 * This is safe for the playground because:
 * - Type discrimination still works via the tuple payload `[T, TName]`
 * - Users only interact with types from `@hex-di/*` (no competing brands)
 * - These types are only used for Monaco intellisense, not real compilation
 */
function normalizeBrandProperties(content: string): string {
  // Step 1: Remove `declare const __brand: unique symbol;` and similar declarations
  let result = content.replace(/^declare const __\w*[Bb]rand\w*: (?:unique )?symbol;\n/gm, "");

  // Step 2: Convert computed symbol property keys to string property keys
  // `readonly [__brand]: [T, TName]` → `readonly __brand: [T, TName]`
  // `readonly [__graphBrand]?: [...]` → `readonly __graphBrand?: [...]`
  result = result.replace(/readonly \[(__\w+)\](\??:\s)/g, "readonly $1$2");

  return result;
}

function main(): void {
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const results: Array<{ name: string; success: boolean; error?: string }> = [];

  for (const pkg of PACKAGES) {
    const npmName = `@hex-di/${pkg}`;
    const pkgDir = packageDir(pkg);
    const entryDts = resolve(pkgDir, "dist/index.d.ts");

    if (!existsSync(entryDts)) {
      // Fall back to reading src/index.ts and generating a minimal declaration
      console.warn(`[warn] ${npmName}: dist/index.d.ts not found, using placeholder`);
      const placeholder = `declare module "${npmName}" { /* auto-generated placeholder — build ${npmName} first */ }`;
      const outFile = resolve(OUTPUT_DIR, `${pkg}.ts`);
      writeFileSync(
        outFile,
        `// Auto-generated by scripts/bundle-playground-types.ts\n// Package: ${npmName}\nexport const dts = \`${escapeForTemplate(placeholder)}\`;\n`
      );
      results.push({ name: npmName, success: true, error: "placeholder" });
      continue;
    }

    try {
      // Use dts-bundle-generator to produce a single bundled .d.ts
      // Write to a temp file instead of stdout to avoid the ~64KB pipe buffer truncation
      const dtsBundleBin = resolve(ROOT, "node_modules/.bin/dts-bundle-generator");
      const tempFile = join(tmpdir(), `hex-di-dts-${pkg}.d.ts`);
      execSync(`"${dtsBundleBin}" --no-banner --no-check --silent -o "${tempFile}" "${entryDts}"`, {
        cwd: MONOREPO_ROOT,
        timeout: 60_000,
        stdio: ["pipe", "pipe", "pipe"],
      });
      const bundled = normalizeBrandProperties(readFileSync(tempFile, "utf-8").trim());
      unlinkSync(tempFile);

      // Wrap in declare module for Monaco's addExtraLib
      const wrapped = `declare module "${npmName}" {\n${bundled}\n}`;
      const outFile = resolve(OUTPUT_DIR, `${pkg}.ts`);
      writeFileSync(
        outFile,
        `// Auto-generated by scripts/bundle-playground-types.ts\n// Package: ${npmName}\nexport const dts = \`${escapeForTemplate(wrapped)}\`;\n`
      );

      results.push({ name: npmName, success: true });
      console.log(`[ok] ${npmName}: ${bundled.length} chars`);
    } catch (err) {
      // If dts-bundle-generator fails, fall back to reading the raw .d.ts
      console.warn(`[warn] ${npmName}: dts-bundle-generator failed, using raw .d.ts`);
      try {
        const raw = readFileSync(entryDts, "utf-8");
        const wrapped = `declare module "${npmName}" {\n${raw}\n}`;
        const outFile = resolve(OUTPUT_DIR, `${pkg}.ts`);
        writeFileSync(
          outFile,
          `// Auto-generated by scripts/bundle-playground-types.ts\n// Package: ${npmName}\nexport const dts = \`${escapeForTemplate(wrapped)}\`;\n`
        );
        results.push({ name: npmName, success: true, error: "raw fallback" });
      } catch {
        const placeholder = `declare module "${npmName}" { /* generation failed */ }`;
        const outFile = resolve(OUTPUT_DIR, `${pkg}.ts`);
        writeFileSync(
          outFile,
          `// Auto-generated by scripts/bundle-playground-types.ts\n// Package: ${npmName}\nexport const dts = \`${escapeForTemplate(placeholder)}\`;\n`
        );
        results.push({
          name: npmName,
          success: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  // Generate barrel index
  const indexLines = ["// Auto-generated by scripts/bundle-playground-types.ts", ""];
  for (const pkg of PACKAGES) {
    indexLines.push(`export { dts as ${pkg.replace(/-/g, "_")} } from "./${pkg}.js";`);
  }
  indexLines.push("");
  writeFileSync(resolve(OUTPUT_DIR, "index.ts"), indexLines.join("\n"));

  console.log(`\nGenerated type definitions for ${results.length} packages`);
  const failed = results.filter(r => !r.success);
  if (failed.length > 0) {
    console.warn(`${failed.length} package(s) used fallbacks`);
  }
}

main();
