// Auto-generated by scripts/bundle-playground-types.ts
// Package: @hex-di/guard
export const dts = `declare module "@hex-di/guard" {
/**
 * Guard error codes.
 *
 * ACL prefixed codes for all guard-domain errors. Container-level
 * errors (missing dependencies) use HEX codes, not ACL codes.
 */
export declare const ACL001: "ACL001";
export declare const ACL002: "ACL002";
export declare const ACL003: "ACL003";
export declare const ACL004: "ACL004";
export declare const ACL005: "ACL005";
export declare const ACL006: "ACL006";
export declare const ACL007: "ACL007";
export declare const ACL008: "ACL008";
export declare const ACL009: "ACL009";
export declare const ACL010: "ACL010";
export declare const ACL011: "ACL011";
export declare const ACL012: "ACL012";
export declare const ACL013: "ACL013";
export declare const ACL014: "ACL014";
export declare const ACL015: "ACL015";
export declare const ACL016: "ACL016";
export declare const ACL017: "ACL017";
export declare const ACL018: "ACL018";
export declare const ACL019: "ACL019";
export declare const ACL020: "ACL020";
export declare const ACL021: "ACL021";
export declare const ACL022: "ACL022";
export declare const ACL023: "ACL023";
export declare const ACL024: "ACL024";
export declare const ACL025: "ACL025";
export declare const ACL026: "ACL026";
export declare const ACL027: "ACL027";
export declare const ACL028: "ACL028";
export declare const ACL029: "ACL029";
export declare const ACL030: "ACL030";
export declare const ACL031: "ACL031";
export type GuardErrorCode = typeof ACL001 | typeof ACL002 | typeof ACL003 | typeof ACL004 | typeof ACL005 | typeof ACL006 | typeof ACL007 | typeof ACL008 | typeof ACL009 | typeof ACL010 | typeof ACL011 | typeof ACL012 | typeof ACL013 | typeof ACL014 | typeof ACL015 | typeof ACL016 | typeof ACL017 | typeof ACL018 | typeof ACL019 | typeof ACL020 | typeof ACL021 | typeof ACL022 | typeof ACL023 | typeof ACL024 | typeof ACL025 | typeof ACL026 | typeof ACL027 | typeof ACL028 | typeof ACL029 | typeof ACL030 | typeof ACL031;
/**
 * Human-readable descriptions of each error code.
 */
export declare const ERROR_CODE_DESCRIPTIONS: Readonly<Record<GuardErrorCode, string>>;
/**
 * Error produced when access is denied by policy evaluation.
 */
interface AccessDeniedError {
	readonly code: typeof ACL001;
	readonly message: string;
	readonly policy: string;
	readonly decision: string;
	readonly portName: string;
	readonly subjectId: string;
}
/**
 * Error produced when a circular role inheritance is detected.
 */
export interface CircularRoleInheritanceError {
	readonly code: typeof ACL002;
	readonly message: string;
	readonly roleName: string;
	readonly cycle: readonly string[];
}
/**
 * Error produced when policy evaluation throws.
 */
export interface PolicyEvaluationError {
	readonly code: typeof ACL003;
	readonly message: string;
	readonly policy: string;
	readonly cause: unknown;
}
/**
 * Error produced when policy deserialization fails.
 */
export interface PolicyDeserializationError {
	readonly code: typeof ACL007;
	readonly message: string;
	readonly input: unknown;
	readonly cause?: unknown;
}
/**
 * Error produced when an audit trail write fails.
 */
export interface AuditTrailWriteError {
	readonly code: typeof ACL008;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when an electronic signature operation fails.
 */
export interface SignatureError {
	readonly code: typeof ACL009;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when an audit entry cannot be parsed.
 */
export interface AuditEntryParseError {
	readonly code: typeof ACL014;
	readonly message: string;
	readonly input: unknown;
	readonly cause?: unknown;
}
/**
 * Error produced when an audit trail read fails.
 */
export interface AuditTrailReadError {
	readonly code: typeof ACL015;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when a meta-audit trail write fails.
 */
export interface MetaAuditWriteError {
	readonly code: typeof ACL011;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when audit trail archival fails.
 */
export interface ArchivalError {
	readonly code: typeof ACL012;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when data retention enforcement fails.
 */
export interface DataRetentionError {
	readonly code: typeof ACL013;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Warning produced when system clock drift is detected.
 */
export interface ClockDriftWarning {
	readonly code: typeof ACL016;
	readonly message: string;
	readonly driftMs: number;
}
/**
 * Error produced when scope disposal chain verification fails.
 */
export interface ScopeDisposalError {
	readonly code: typeof ACL017;
	readonly message: string;
	readonly undisposed: readonly string[];
}
/**
 * Error produced when async attribute resolution fails.
 */
export interface AttributeResolveError {
	readonly code: typeof ACL018;
	readonly message: string;
	readonly attribute: string;
	readonly cause?: unknown;
}
/**
 * Error produced when decommissioning verification fails.
 */
export interface DecommissionError {
	readonly code: typeof ACL020;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when qualification protocol validation fails.
 */
export interface ValidationError {
	readonly code: typeof ACL021;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * Error produced when relationship resolution fails.
 */
export interface RelationshipResolveError {
	readonly code: typeof ACL022;
	readonly message: string;
	readonly relation: string;
	readonly cause?: unknown;
}
/**
 * Error produced when the audit trail circuit breaker is open.
 */
export interface CircuitOpenError {
	readonly code: typeof ACL023;
	readonly message: string;
}
/**
 * Error produced when an authorization scope's TTL has elapsed.
 */
export interface ScopeExpiredError {
	readonly code: typeof ACL024;
	readonly message: string;
	readonly scopeId: string;
	readonly expiredAt: string;
}
/**
 * Error produced when the per-scope call rate limit is exceeded.
 */
export interface RateLimitExceededError {
	readonly code: typeof ACL025;
	readonly message: string;
	readonly scopeId: string;
	readonly limit: number;
	readonly windowMs: number;
}
/**
 * Error produced when async attribute resolution times out.
 */
export interface AttributeResolveTimeoutError {
	readonly code: typeof ACL026;
	readonly message: string;
	readonly attribute: string;
	readonly timeoutMs: number;
}
/**
 * Error produced when RelationshipResolverPort is not wired.
 */
export interface RelationshipResolverMissingError {
	readonly code: typeof ACL028;
	readonly message: string;
	readonly relation: string;
}
/**
 * Error produced when audit chain integrity verification fails.
 */
export interface ChainIntegrityError {
	readonly code: typeof ACL029;
	readonly message: string;
	readonly scopeId?: string;
}
/**
 * Error produced when resource.id is missing for a relationship check.
 */
export interface ResourceIdMissingError {
	readonly code: typeof ACL030;
	readonly message: string;
	readonly relation: string;
}
/**
 * Union of all guard-domain errors.
 */
export type GuardError = AccessDeniedError | CircularRoleInheritanceError | PolicyEvaluationError | PolicyDeserializationError | AuditTrailWriteError | SignatureError | AuditEntryParseError | AuditTrailReadError | MetaAuditWriteError | ArchivalError | DataRetentionError | ClockDriftWarning | ScopeDisposalError | AttributeResolveError | DecommissionError | ValidationError | RelationshipResolveError | CircuitOpenError | ScopeExpiredError | RateLimitExceededError | AttributeResolveTimeoutError | RelationshipResolverMissingError | ChainIntegrityError | ResourceIdMissingError;
/**
 * Permission token types and factory.
 *
 * Permissions use structural typing with well-known symbols so that
 * two Permission<'user', 'read'> created in different modules are
 * type-compatible. This contrasts with Port which uses unique symbols.
 */
export declare const PERMISSION_BRAND: unique symbol;
/**
 * A typed permission token representing a resource+action pair.
 * Uses the PERMISSION_BRAND runtime symbol for type discrimination
 * and literal type parameters on resource/action for structural incompatibility.
 */
export type Permission<TResource extends string, TAction extends string> = {
	readonly [PERMISSION_BRAND]: true;
	readonly resource: TResource;
	readonly action: TAction;
};
/**
 * Structural constraint matching ANY Permission without using \`any\`.
 */
export interface PermissionConstraint {
	readonly [PERMISSION_BRAND]: true;
	readonly resource: string;
	readonly action: string;
}
/**
 * Per-permission configuration options.
 */
export interface PermissionOptions {
	readonly description?: string;
	readonly effectiveDate?: string;
	readonly expirationDate?: string;
	readonly changeControlId?: string;
}
/**
 * Creates a typed permission token.
 *
 * The returned object is frozen and carries both runtime fields
 * (resource, action) and the PERMISSION_BRAND for type discrimination.
 */
export declare function createPermission<const TResource extends string, const TAction extends string>(config: {
	readonly resource: TResource;
	readonly action: TAction;
	readonly options?: PermissionOptions;
}): Permission<TResource, TAction>;
/**
 * Type guard: returns true if value is a Permission token.
 */
export declare function isPermission(value: unknown): value is PermissionConstraint;
/**
 * Formats a permission as "resource:action" string.
 */
export declare function formatPermission(perm: PermissionConstraint): string;
/**
 * Warning emitted when the same resource:action pair is registered twice.
 * Error code ACL006.
 */
export interface DuplicatePermissionWarning {
	readonly code: "ACL006";
	readonly message: string;
	readonly key: string;
}
/**
 * A registry that tracks all permissions registered within a bounded scope.
 * Emits a DuplicatePermissionWarning callback when the same resource:action
 * is registered more than once.
 */
export interface PermissionRegistry {
	/**
	 * Registers a permission in this registry.
	 * Calls onDuplicate if the same resource:action has already been registered.
	 */
	register<TResource extends string, TAction extends string>(permission: Permission<TResource, TAction>, onDuplicate?: (warning: DuplicatePermissionWarning) => void): Permission<TResource, TAction>;
	/** Returns all registered permissions in insertion order. */
	getAll(): readonly PermissionConstraint[];
}
/**
 * Creates an isolated permission registry.
 *
 * @example
 * \`\`\`ts
 * const registry = createPermissionRegistry();
 * const ReadDoc = registry.register(createPermission({ resource: "doc", action: "read" }));
 * const all = registry.getAll();
 * \`\`\`
 */
export declare function createPermissionRegistry(): PermissionRegistry;
/**
 * Maps a set of action names to Permission types for a given resource.
 */
export type PermissionGroupMap<TResource extends string, TActions extends readonly string[] | Record<string, PermissionOptions>> = {
	readonly [K in TActions extends readonly string[] ? TActions[number] : keyof TActions & string]: Permission<TResource, K & string>;
};
/**
 * Creates a permission group mapping action names to typed Permission tokens.
 *
 * Overload 1: Array of action names.
 * Overload 2: Object mapping action names to PermissionOptions.
 */
export declare function createPermissionGroup<const TResource extends string, const TActions extends readonly string[]>(resource: TResource, actions: TActions): PermissionGroupMap<TResource, TActions>;
export declare function createPermissionGroup<const TResource extends string, const TActions extends Record<string, PermissionOptions>>(resource: TResource, actions: TActions): PermissionGroupMap<TResource, TActions>;
declare const RESULT_BRAND: unique symbol;
declare const OPTION_BRAND: unique symbol;
/**
 * The presence variant of \`Option\`. Represents a value that exists.
 *
 * \`Some<T>\` carries a \`value\` of type \`T\` and provides transformation,
 * chaining, extraction, and conversion methods. Instances are created
 * via the \`some()\` factory and are frozen plain objects branded with \`OPTION_BRAND\`.
 *
 * @example
 * \`\`\`ts
 * import { some } from '@hex-di/result';
 *
 * const opt = some(42);
 * opt.isSome();      // true
 * opt.map(x => x * 2); // Some(84)
 * opt.unwrapOr(0);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-002
 */
export interface Some<T> {
	readonly _tag: "Some";
	readonly value: T;
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<T>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: T) => boolean): boolean;
	map<U>(f: (value: T) => U): Some<U>;
	filter(predicate: (value: T) => boolean): Option<T>;
	flatten<U>(this: Some<Option<U>>): Option<U>;
	zip<U>(other: Option<U>): Option<[
		T,
		U
	]>;
	zipWith<U, R>(other: Option<U>, f: (a: T, b: U) => R): Option<R>;
	andThen<U>(f: (value: T) => Option<U>): Option<U>;
	orElse(f: () => Option<T>): Some<T>;
	match<A, B>(onSome: (value: T) => A, onNone: () => B): A;
	unwrapOr<U>(defaultValue: U): T;
	expect(message: string): T;
	toResult<E>(onNone: () => E): Ok<T, E>;
	toNullable(): T;
	toUndefined(): T;
	toJSON(): {
		_tag: "Some";
		_schemaVersion: 1;
		value: T;
	};
	transpose<U, E>(this: Some<Result<U, E>>): Result<Some<U>, E>;
}
/**
 * The absence variant of \`Option\`. Represents the lack of a value.
 *
 * \`None\` carries no value and short-circuits all transformations and chaining operations.
 * Extraction methods return defaults or throw. A single frozen singleton is reused
 * for all \`none()\` calls.
 *
 * @example
 * \`\`\`ts
 * import { none } from '@hex-di/result';
 *
 * const opt = none();
 * opt.isNone();      // true
 * opt.map(x => x * 2); // None
 * opt.unwrapOr(0);   // 0
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-003
 */
export interface None {
	readonly _tag: "None";
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<never>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: never) => boolean): boolean;
	map<U>(f: (value: never) => U): None;
	filter(predicate: (value: never) => boolean): None;
	flatten(): None;
	zip<U>(other: Option<U>): None;
	zipWith<U, R>(other: Option<U>, f: (a: never, b: U) => R): None;
	andThen<U>(f: (value: never) => Option<U>): None;
	orElse<T>(f: () => Option<T>): Option<T>;
	match<A, B>(onSome: (value: never) => A, onNone: () => B): B;
	unwrapOr<U>(defaultValue: U): U;
	expect(message: string): never;
	toResult<E>(onNone: () => E): Err<never, E>;
	toNullable(): null;
	toUndefined(): undefined;
	toJSON(): {
		_tag: "None";
		_schemaVersion: 1;
	};
	transpose(): Ok<None, never>;
}
/**
 * Discriminated union of \`Some<T>\` and \`None\`.
 *
 * \`Option<T>\` models the presence or absence of a value. TypeScript narrows
 * to the correct variant after checking \`_tag\`, \`isSome()\`, or \`isNone()\`.
 *
 * @example
 * \`\`\`ts
 * import { some, none } from '@hex-di/result';
 * import type { Option } from '@hex-di/result';
 *
 * function greet(name: Option<string>): string {
 *   return name.match(
 *     n => \`Hello, \${n}!\`,
 *     () => "Hello, stranger!"
 *   );
 * }
 *
 * greet(some("Alice")); // "Hello, Alice!"
 * greet(none());        // "Hello, stranger!"
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-004
 */
export type Option<T> = Some<T> | None;
export interface ResultAsync<T, E> extends PromiseLike<Result<T, E>> {
	map<U>(f: (value: T) => U | Promise<U>): ResultAsync<U, E>;
	mapErr<F>(f: (error: E) => F | Promise<F>): ResultAsync<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U | Promise<U>, onErr: (error: E) => F | Promise<F>): ResultAsync<U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F> | ResultAsync<U, F>): ResultAsync<T | U, F>;
	andTee(f: (value: T) => void | Promise<void>): ResultAsync<T, E>;
	orTee(f: (error: E) => void | Promise<void>): ResultAsync<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F> | ResultAsync<unknown, F>): ResultAsync<T, E | F>;
	inspect(f: (value: T) => void): ResultAsync<T, E>;
	inspectErr(f: (error: E) => void): ResultAsync<T, E>;
	match<A, B>(onOk: (value: T) => A | Promise<A>, onErr: (error: E) => B | Promise<B>): Promise<A | B>;
	unwrapOr<U>(defaultValue: U): Promise<T | U>;
	unwrapOrElse<U>(f: (error: E) => U): Promise<T | U>;
	orDie(): Promise<T>;
	toNullable(): Promise<T | null>;
	toUndefined(): Promise<T | undefined>;
	intoTuple(): Promise<[
		null,
		T
	] | [
		E,
		null
	]>;
	merge(): Promise<T | E>;
	flatten<U>(this: ResultAsync<Result<U, E>, E>): ResultAsync<U, E>;
	flip(): ResultAsync<E, T>;
	toJSON(): Promise<{
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	} | {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	}>;
}
/**
 * The success variant of {@link Result}. Contains a \`value\` of type \`T\`.
 *
 * \`Ok\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link ok} factory function. The phantom type parameter \`E\` has no runtime
 * representation; the \`ok()\` factory produces \`Ok<T, never>\`, where \`never\` extends any \`E\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error (phantom on Ok; defaults to \`never\` from the factory).
 *
 * @example
 * \`\`\`ts
 * import { ok } from '@hex-di/result';
 *
 * const result = ok(42);
 * console.log(result.isOk());  // true
 * console.log(result.value);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-004}
 */
export interface Ok<T, E> {
	readonly _tag: "Ok";
	readonly value: T;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Ok<U, E>;
	mapErr<F>(f: (error: E) => F): Ok<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Ok<U, F>;
	flatten<U, E2>(this: Ok<Result<U, E2>, E>): Result<U, E | E2>;
	flip(): Err<E, T>;
	and<U, F>(other: Result<U, F>): Result<U, E | F>;
	or<U, F>(other: Result<U, F>): Ok<T, E>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Result<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Ok<T, E>;
	andTee(f: (value: T) => void): Ok<T, E>;
	orTee(f: (error: E) => void): Ok<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Result<T, E | F>;
	inspect(f: (value: T) => void): Ok<T, E>;
	inspectErr(f: (error: E) => void): Ok<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): A;
	unwrapOr<U>(defaultValue: U): T;
	unwrapOrElse<U>(f: (error: E) => U): T;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): T;
	expectErr(message: string): never;
	orDie(): T;
	toNullable(): T;
	toUndefined(): T;
	intoTuple(): [
		null,
		T
	];
	merge(): T;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): Some<T>;
	toOptionErr(): None;
	transpose<U>(this: Ok<Option<U>, E>): Option<Result<U, E>>;
	toJSON(): {
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	};
	[Symbol.iterator](): Generator<never, T, unknown>;
}
/**
 * The failure variant of {@link Result}. Contains an \`error\` of type \`E\`.
 *
 * \`Err\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link err} factory function. The phantom type parameter \`T\` has no runtime
 * representation; the \`err()\` factory produces \`Err<never, E>\`, where \`never\` extends any \`T\`.
 *
 * @typeParam T - The type of the success value (phantom on Err; defaults to \`never\` from the factory).
 * @typeParam E - The type of the error.
 *
 * @example
 * \`\`\`ts
 * import { err } from '@hex-di/result';
 *
 * const result = err('not found');
 * console.log(result.isErr());  // true
 * console.log(result.error);    // 'not found'
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-005}
 */
export interface Err<T, E> {
	readonly _tag: "Err";
	readonly error: E;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Err<U, E>;
	mapErr<F>(f: (error: E) => F): Err<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Err<U, F>;
	flatten<U, E2>(this: Err<Result<U, E2>, E>): Err<U, E>;
	flip(): Ok<E, T>;
	and<U, F>(other: Result<U, F>): Err<U, E>;
	or<U, F>(other: Result<U, F>): Result<T | U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Err<U, E>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Result<T | U, F>;
	andTee(f: (value: T) => void): Err<T, E>;
	orTee(f: (error: E) => void): Err<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Err<T, E>;
	inspect(f: (value: T) => void): Err<T, E>;
	inspectErr(f: (error: E) => void): Err<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): B;
	unwrapOr<U>(defaultValue: U): U;
	unwrapOrElse<U>(f: (error: E) => U): U;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): never;
	expectErr(message: string): E;
	orDie(): never;
	toNullable(): null;
	toUndefined(): undefined;
	intoTuple(): [
		E,
		null
	];
	merge(): E;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): None;
	toOptionErr(): Some<E>;
	transpose(): Some<Err<never, E>>;
	toJSON(): {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	};
	[Symbol.iterator](): Generator<Err<never, E>, never, unknown>;
}
/**
 * A discriminated union of {@link Ok} and {@link Err}.
 *
 * \`Result<T, E>\` represents either a success (\`Ok\`) holding a value of type \`T\`,
 * or a failure (\`Err\`) holding an error of type \`E\`. TypeScript narrows to the
 * correct variant after checking \`_tag\`, \`isOk()\`, or \`isErr()\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error value.
 *
 * @example
 * \`\`\`ts
 * import { ok, err, type Result } from '@hex-di/result';
 *
 * function divide(a: number, b: number): Result<number, string> {
 *   if (b === 0) return err('division by zero');
 *   return ok(a / b);
 * }
 *
 * const result = divide(10, 2);
 * if (result.isOk()) {
 *   console.log(result.value); // 5
 * }
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-006}
 */
export type Result<T, E> = Ok<T, E> | Err<T, E>;
export declare const ROLE_BRAND: unique symbol;
/**
 * Runtime symbol carrying the direct permission tuple for type-level flattening.
 * This is a real symbol so its value can be set without casts.
 * The value at runtime is the direct permissions array; the TYPE preserves the generic tuple.
 */
export declare const ROLE_PERMISSIONS_TAG: unique symbol;
/**
 * A typed role that carries its complete flattened permission set and inherits list.
 * ROLE_PERMISSIONS_TAG carries the direct permission tuple type for FlattenRolePermissions.
 */
export type Role<TName extends string, TPermissions extends readonly PermissionConstraint[], TInherits extends readonly RoleConstraint[] = readonly RoleConstraint[]> = {
	readonly [ROLE_BRAND]: true;
	readonly [ROLE_PERMISSIONS_TAG]: TPermissions;
	readonly name: TName;
	readonly permissions: readonly PermissionConstraint[];
	readonly inherits: TInherits;
};
/**
 * Structural constraint matching ANY Role.
 */
export interface RoleConstraint {
	readonly [ROLE_BRAND]: true;
	readonly name: string;
	readonly permissions: readonly PermissionConstraint[];
	readonly inherits: readonly RoleConstraint[];
}
/**
 * Type-level utility: Peano depth counter for recursive flattening.
 * Limits recursion to 20 levels.
 */
export type Prev = [
	never,
	0,
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20
];
/**
 * Type-level permission flattening across a role DAG.
 * Uses the ROLE_PERMISSIONS_TAG when available (concrete Role types)
 * and falls back to PermissionConstraint for plain RoleConstraint values.
 */
export type FlattenRolePermissions<TRoles extends readonly RoleConstraint[], TDepth extends number = 20> = [
	TDepth
] extends [
	never
] ? never : TRoles extends readonly [
] ? never : TRoles extends readonly [
	infer Head,
	...infer Tail
] ? Tail extends readonly RoleConstraint[] ? Head extends {
	readonly [ROLE_PERMISSIONS_TAG]: infer P;
	readonly inherits: infer TI;
} ? P extends readonly PermissionConstraint[] ? TI extends readonly RoleConstraint[] ? P[number] | FlattenRolePermissions<TI, Prev[TDepth]> | FlattenRolePermissions<Tail, TDepth> : P[number] | FlattenRolePermissions<Tail, TDepth> : never : Head extends RoleConstraint ? PermissionConstraint | FlattenRolePermissions<Head["inherits"], Prev[TDepth]> | FlattenRolePermissions<Tail, TDepth> : never : never : never;
/**
 * Creates a typed role with inheritance.
 */
export declare function createRole<const TName extends string, const TPermissions extends readonly PermissionConstraint[], const TInherits extends readonly RoleConstraint[]>(config: {
	readonly name: TName;
	readonly permissions: TPermissions;
	readonly inherits: TInherits;
}): Role<TName, TPermissions, TInherits>;
/**
 * Creates a typed role without inheritance.
 */
export declare function createRole<const TName extends string, const TPermissions extends readonly PermissionConstraint[]>(config: {
	readonly name: TName;
	readonly permissions: TPermissions;
}): Role<TName, TPermissions, readonly [
]>;
/**
 * Runtime function: returns all flattened permissions for a role, with cycle detection.
 * Walks the DAG using DFS with a visited set. Returns Err on circular inheritance.
 */
export declare function flattenPermissions(role: RoleConstraint): Result<readonly PermissionConstraint[], CircularRoleInheritanceError>;
/**
 * Type guard: returns true if value is a Role token.
 */
export declare function isRole(value: unknown): value is RoleConstraint;
/**
 * A Separation of Duties constraint declaring that no subject may hold
 * all listed roles simultaneously.
 */
export interface MutuallyExclusiveRoles {
	readonly _tag: "MutuallyExclusiveRoles";
	readonly roles: readonly string[];
	readonly reason: string;
}
/**
 * Creates a MutuallyExclusiveRoles SoD constraint.
 *
 * @example
 * \`\`\`ts
 * const constraint = createMutuallyExclusiveRoles(["approver", "requester"], "Four-eyes principle");
 * \`\`\`
 */
export declare function createMutuallyExclusiveRoles(roles: readonly string[], reason: string): MutuallyExclusiveRoles;
/**
 * A conflict detected by validateSoDConstraints.
 */
export interface SoDConflict {
	readonly constraint: MutuallyExclusiveRoles;
	readonly conflictingRoles: readonly string[];
}
/**
 * Validates a set of subject roles against a list of SoD constraints.
 * Returns all conflicts found (empty array means compliant).
 *
 * @example
 * \`\`\`ts
 * const conflicts = validateSoDConstraints(["approver", "requester"], [approverRequesterConstraint]);
 * if (conflicts.length > 0) throw new Error("SoD violation");
 * \`\`\`
 */
export declare function validateSoDConstraints(subjectRoles: readonly string[], constraints: readonly MutuallyExclusiveRoles[]): readonly SoDConflict[];
/**
 * Discriminant tag for all policy types.
 */
export type PolicyKind = "hasPermission" | "hasRole" | "hasAttribute" | "hasResourceAttribute" | "hasSignature" | "hasRelationship" | "allOf" | "anyOf" | "not" | "labeled";
/**
 * Structural constraint matching any Policy.
 */
export interface PolicyConstraint {
	readonly kind: PolicyKind;
}
/**
 * Type guard: returns true if the value is a PolicyConstraint (i.e. an object with a valid kind).
 */
export declare function isPolicyConstraint(v: unknown): v is PolicyConstraint;
/**
 * Strategy for merging visible field sets in composite policies.
 *
 * - \`"intersection"\`: fields visible in ALL allowing children (least-privilege, default for allOf)
 * - \`"union"\`: fields visible in ANY allowing child (maximum visibility, used with anyOf)
 * - \`"first"\`: fields from the first allowing child (short-circuit, default for anyOf)
 */
export type FieldStrategy = "intersection" | "union" | "first";
export type SubjectRef = {
	readonly kind: "subject";
	readonly path: string;
};
export type ResourceRef = {
	readonly kind: "resource";
	readonly path: string;
};
export type LiteralRef = {
	readonly kind: "literal";
	readonly value: unknown;
};
export type ValueRef = SubjectRef | ResourceRef | LiteralRef;
export type EqMatcher = {
	readonly kind: "eq";
	readonly ref: ValueRef;
};
export type NeqMatcher = {
	readonly kind: "neq";
	readonly ref: ValueRef;
};
export type InMatcher = {
	readonly kind: "in";
	readonly values: readonly unknown[];
};
export type ExistsMatcher = {
	readonly kind: "exists";
};
export type FieldMatchMatcher = {
	readonly kind: "fieldMatch";
	readonly field: string;
	readonly matcher: MatcherExpression;
};
export type GteMatcher = {
	readonly kind: "gte";
	readonly value: number;
};
export type LtMatcher = {
	readonly kind: "lt";
	readonly value: number;
};
export type SomeMatchMatcher = {
	readonly kind: "someMatch";
	readonly matcher: MatcherExpression;
};
export type ContainsMatcher = {
	readonly kind: "contains";
	readonly value: unknown;
};
export type EveryMatchMatcher = {
	readonly kind: "everyMatch";
	readonly matcher: MatcherExpression;
};
export type SizeMatcher = {
	readonly kind: "size";
	readonly matcher: MatcherExpression;
};
export type MatcherExpression = EqMatcher | NeqMatcher | InMatcher | ExistsMatcher | FieldMatchMatcher | GteMatcher | LtMatcher | SomeMatchMatcher | ContainsMatcher | EveryMatchMatcher | SizeMatcher;
export interface HasPermissionPolicy<TPermission extends PermissionConstraint = PermissionConstraint> {
	readonly kind: "hasPermission";
	readonly permission: TPermission;
	readonly fields?: ReadonlyArray<string>;
}
export interface HasRolePolicy<TRoleName extends string = string> {
	readonly kind: "hasRole";
	readonly roleName: TRoleName;
}
export interface HasAttributePolicy<TAttribute extends string = string> {
	readonly kind: "hasAttribute";
	readonly attribute: TAttribute;
	readonly matcher: MatcherExpression;
	readonly fields?: ReadonlyArray<string>;
}
export interface HasResourceAttributePolicy<TAttribute extends string = string> {
	readonly kind: "hasResourceAttribute";
	readonly attribute: TAttribute;
	readonly matcher: MatcherExpression;
	readonly fields?: ReadonlyArray<string>;
}
export interface HasSignaturePolicy<TMeaning extends string = string> {
	readonly kind: "hasSignature";
	readonly meaning: TMeaning;
	readonly signerRole?: string;
}
export interface HasRelationshipPolicy<TRelation extends string = string> {
	readonly kind: "hasRelationship";
	readonly relation: TRelation;
	readonly resourceType?: string;
	readonly depth?: number;
	readonly fields?: ReadonlyArray<string>;
}
export interface AllOfPolicy<TPolicies extends readonly PolicyConstraint[] = readonly PolicyConstraint[]> {
	readonly kind: "allOf";
	readonly policies: TPolicies;
	/** Field merge strategy. Default: "intersection" (least-privilege). */
	readonly fieldStrategy?: FieldStrategy;
}
export interface AnyOfPolicy<TPolicies extends readonly PolicyConstraint[] = readonly PolicyConstraint[]> {
	readonly kind: "anyOf";
	readonly policies: TPolicies;
	/**
	 * Field merge strategy. Default: "first" (short-circuit).
	 * Use "union" to evaluate ALL children and merge their field sets.
	 */
	readonly fieldStrategy?: FieldStrategy;
}
export interface NotPolicy<TPolicy extends PolicyConstraint = PolicyConstraint> {
	readonly kind: "not";
	readonly policy: TPolicy;
}
export interface LabeledPolicy<TPolicy extends PolicyConstraint = PolicyConstraint> {
	readonly kind: "labeled";
	readonly label: string;
	readonly policy: TPolicy;
}
/**
 * Union of all policy types.
 */
export type Policy = HasPermissionPolicy | HasRolePolicy | HasAttributePolicy | HasResourceAttributePolicy | HasSignaturePolicy | HasRelationshipPolicy | AllOfPolicy | AnyOfPolicy | NotPolicy | LabeledPolicy;
/**
 * Type guard: narrows a PolicyConstraint to the full Policy discriminated union.
 * Enables switch-case exhaustiveness checking without casts.
 */
export declare function isPolicy(p: PolicyConstraint): p is Policy;
/** Creates a reference to a subject field by dot-path. */
export declare function subject(path: string): SubjectRef;
/** Creates a reference to a resource field by dot-path. */
export declare function resource(path: string): ResourceRef;
/** Creates a literal value reference. */
export declare function literal(value: unknown): LiteralRef;
/** Creates an equality matcher: attribute === ref value. */
export declare function eq(ref: SubjectRef | ResourceRef | LiteralRef): EqMatcher;
/** Creates an inequality matcher: attribute !== ref value. */
export declare function neq(ref: SubjectRef | ResourceRef | LiteralRef): NeqMatcher;
/** Creates an inclusion matcher: attribute is in the given values array. */
export declare function inArray(values: readonly unknown[]): InMatcher;
/** Creates an existence matcher: attribute is not null or undefined. */
export declare function exists(): ExistsMatcher;
/** Creates a field-match matcher: matches a nested field of an object attribute. */
export declare function fieldMatch(field: string, matcher: MatcherExpression): FieldMatchMatcher;
/** Creates a >= numeric matcher. */
export declare function gte(value: number): GteMatcher;
/** Creates a < numeric matcher. */
export declare function lt(value: number): LtMatcher;
/** Creates a some-match matcher for arrays: any element satisfies the matcher. */
export declare function someMatch(matcher: MatcherExpression): SomeMatchMatcher;
/** Creates a contains matcher: array/string contains the value. */
export declare function contains(value: unknown): ContainsMatcher;
/** Creates an every-match matcher for arrays: all elements satisfy the matcher. */
export declare function everyMatch(matcher: MatcherExpression): EveryMatchMatcher;
/** Creates a size matcher: applies matcher to the length of an array or string. */
export declare function size(matcher: MatcherExpression): SizeMatcher;
/**
 * Options for combinator policies (allOf, anyOf).
 */
export interface CombinatorOptions {
	/** Strategy for merging visible field sets across child policies. */
	readonly fieldStrategy?: FieldStrategy;
}
/**
 * Creates a hasPermission policy.
 */
export declare function hasPermission<TPermission extends PermissionConstraint>(permission: TPermission, options?: {
	readonly fields?: ReadonlyArray<string>;
}): HasPermissionPolicy<TPermission>;
/**
 * Creates a hasRole policy.
 */
export declare function hasRole<const TRoleName extends string>(roleName: TRoleName): HasRolePolicy<TRoleName>;
/**
 * Creates a hasAttribute policy using the matcher DSL.
 */
export declare function hasAttribute<const TAttribute extends string>(attribute: TAttribute, matcher: MatcherExpression, options?: {
	readonly fields?: ReadonlyArray<string>;
}): HasAttributePolicy<TAttribute>;
/**
 * Creates a hasResourceAttribute policy using the matcher DSL.
 */
export declare function hasResourceAttribute<const TAttribute extends string>(attribute: TAttribute, matcher: MatcherExpression, options?: {
	readonly fields?: ReadonlyArray<string>;
}): HasResourceAttributePolicy<TAttribute>;
/**
 * Creates a hasSignature policy for 21 CFR Part 11 compliance.
 */
export declare function hasSignature<const TMeaning extends string>(meaning: TMeaning, options?: {
	readonly signerRole?: string;
}): HasSignaturePolicy<TMeaning>;
/**
 * Creates a hasRelationship policy for graph-traversal relationship checks.
 */
export declare function hasRelationship<const TRelation extends string>(relation: TRelation, options?: {
	readonly resourceType?: string;
	readonly depth?: number;
	readonly fields?: ReadonlyArray<string>;
}): HasRelationshipPolicy<TRelation>;
/**
 * Creates an allOf policy: ALL child policies must pass.
 * Accepts an optional trailing CombinatorOptions to configure field strategy.
 */
export declare function allOf<const TPolicies extends readonly PolicyConstraint[]>(...policies: TPolicies): AllOfPolicy<TPolicies>;
export declare function allOf<const TPolicies extends readonly PolicyConstraint[]>(...args: [
	...TPolicies,
	CombinatorOptions
]): AllOfPolicy<TPolicies>;
/**
 * Creates an anyOf policy: ANY child policy must pass.
 * Accepts an optional trailing CombinatorOptions to configure field strategy.
 * With \`fieldStrategy: "union"\`, evaluates ALL children even after first allow.
 */
export declare function anyOf<const TPolicies extends readonly PolicyConstraint[]>(...policies: TPolicies): AnyOfPolicy<TPolicies>;
export declare function anyOf<const TPolicies extends readonly PolicyConstraint[]>(...args: [
	...TPolicies,
	CombinatorOptions
]): AnyOfPolicy<TPolicies>;
/**
 * Creates a not policy: negates the child policy.
 */
export declare function not<const TPolicy extends PolicyConstraint>(policy: TPolicy): NotPolicy<TPolicy>;
/**
 * Creates a labeled policy: wraps a policy with a human-readable name.
 */
export declare function withLabel<const TPolicy extends PolicyConstraint>(label: string, policy: TPolicy): LabeledPolicy<TPolicy>;
/**
 * Creates an anyOf policy from a list of roles.
 * The subject must have at least one of the listed roles.
 * Accepts either role names (strings) or role tokens.
 */
export declare function anyOfRoles(roles: readonly (string | RoleConstraint)[]): AnyOfPolicy<readonly HasRolePolicy[]>;
/**
 * Trace of a single policy node evaluation.
 */
export interface EvaluationTrace {
	readonly policyKind: string;
	readonly label?: string;
	readonly result: "allow" | "deny";
	readonly reason?: string;
	readonly durationMs: number;
	readonly children?: readonly EvaluationTrace[];
	/** Field-level visibility set propagated from leaf policies. */
	readonly visibleFields?: ReadonlyArray<string>;
}
/**
 * An Allow decision with full context.
 */
export interface Allow {
	readonly kind: "allow";
	readonly evaluationId: string;
	readonly evaluatedAt: string;
	readonly subjectId: string;
	readonly policy: PolicyConstraint;
	readonly trace: EvaluationTrace;
	readonly durationMs: number;
	readonly visibleFields?: ReadonlyArray<string>;
}
/**
 * A Deny decision with full context.
 */
export interface Deny {
	readonly kind: "deny";
	readonly evaluationId: string;
	readonly evaluatedAt: string;
	readonly subjectId: string;
	readonly policy: PolicyConstraint;
	readonly trace: EvaluationTrace;
	readonly durationMs: number;
	readonly reason: string;
}
/** Union of Allow and Deny. */
export type Decision = Allow | Deny;
/**
 * Builds an EvaluationTrace node.
 */
export declare function buildTrace(options: {
	readonly policyKind: string;
	readonly label?: string;
	readonly result: "allow" | "deny";
	readonly reason?: string;
	readonly durationMs: number;
	readonly children?: readonly EvaluationTrace[];
	readonly visibleFields?: ReadonlyArray<string>;
}): EvaluationTrace;
/**
 * Creates a PolicyEvaluationError.
 */
export declare function createPolicyEvaluationError(policy: PolicyConstraint, cause: unknown): PolicyEvaluationError;
/**
 * AuthSubject interface — the entity being authorized.
 */
export interface AuthSubject {
	readonly id: string;
	readonly roles: readonly string[];
	/** Flattened permission set for O(1) lookup: "resource:action" strings. */
	readonly permissions: ReadonlySet<string>;
	readonly attributes: Readonly<Record<string, unknown>>;
	readonly authenticationMethod: string;
	readonly authenticatedAt: string;
	readonly identityProvider?: string;
	readonly sessionId?: string;
}
/**
 * A pre-computed subject with additional type-safe attributes.
 */
export interface PrecomputedSubject extends AuthSubject {
	readonly _precomputed: true;
}
/**
 * Creates a new AuthSubject with additional attributes merged in.
 */
export declare function withAttributes(subject: AuthSubject, attributes: Readonly<Record<string, unknown>>): AuthSubject;
/**
 * Gets an attribute from a subject by key.
 * Returns undefined if the attribute is not present.
 */
export declare function getAttribute(subject: AuthSubject, key: string): unknown;
/**
 * Creates a minimal AuthSubject with all required fields.
 */
export declare function createAuthSubject(id: string, roles: readonly string[], permissions: ReadonlySet<string>, attributes?: Readonly<Record<string, unknown>>, authenticationMethod?: string, authenticatedAt?: string): AuthSubject;
/**
 * Interface for synchronous relationship-based access control checks.
 * Implement this to support graph-traversal authorization (ReBAC).
 */
export interface RelationshipResolver {
	/**
	 * Synchronously checks whether a subject has a relationship to a resource.
	 * @param subjectId - The subject identifier
	 * @param relation - The relationship name (e.g., "owner", "member", "viewer")
	 * @param resourceId - The resource identifier
	 * @param options - Optional check options
	 */
	check(subjectId: string, relation: string, resourceId: string, options?: {
		readonly depth?: number;
	}): boolean;
	/**
	 * Asynchronously checks whether a subject has a relationship to a resource.
	 * Used by evaluateAsync().
	 */
	checkAsync(subjectId: string, relation: string, resourceId: string, options?: {
		readonly depth?: number;
	}): Promise<boolean>;
}
/**
 * Port type for the RelationshipResolver.
 */
export type RelationshipResolverPort = RelationshipResolver;
/**
 * A no-op relationship resolver that always denies relationships.
 * Not suitable for production use.
 */
export declare const NoopRelationshipResolver: RelationshipResolver;
/** Arbitrary resource attributes for attribute-based policies. */
export type Resource = Readonly<Record<string, unknown>>;
/**
 * A validated electronic signature attached to the evaluation context.
 */
export interface ValidatedSignature {
	readonly signerId: string;
	readonly signedAt: string;
	readonly meaning: string;
	readonly validated: boolean;
	readonly reauthenticated: boolean;
	readonly signerRoles?: ReadonlyArray<string>;
}
/**
 * The context provided to the evaluate function.
 */
export interface EvaluationContext {
	readonly subject: AuthSubject;
	readonly resource?: Resource;
	readonly signatures?: ReadonlyArray<ValidatedSignature>;
	readonly evaluationId?: string;
	readonly evaluatedAt?: string;
	/** Optional relationship resolver for ReBAC policies. */
	readonly relationshipResolver?: RelationshipResolver;
}
/**
 * Options for evaluation behavior.
 */
export interface EvaluateOptions {
	readonly maxDepth?: number;
}
/**
 * A record mapping named keys to policies.
 */
export type PoliciesMap = Readonly<Record<string, PolicyConstraint>>;
/**
 * Computes the intersection of two visible field sets.
 * \`undefined\` is treated as the universal set (all fields allowed).
 * The intersection of universal and any set S is S.
 * The intersection of two concrete sets is their overlap.
 */
export declare function intersectVisibleFields(a: ReadonlyArray<string> | undefined, b: ReadonlyArray<string> | undefined): ReadonlyArray<string> | undefined;
/**
 * Merges multiple visible field sets using the specified strategy.
 *
 * - \`"intersection"\`: fields present in ALL non-undefined sets
 * - \`"union"\`: fields present in ANY set
 * - \`"first"\`: first non-undefined set
 *
 * \`undefined\` is treated as the universal set (all fields allowed).
 */
export declare function mergeVisibleFields(strategy: FieldStrategy, ...fieldSets: ReadonlyArray<ReadonlyArray<string> | undefined>): ReadonlyArray<string> | undefined;
/**
 * Evaluates an authorization policy against a subject and optional resource context.
 *
 * Returns Result<Decision, PolicyEvaluationError>. This function is synchronous
 * and deterministic with respect to policy logic.
 */
export declare function evaluate(policy: PolicyConstraint, context: EvaluationContext, options?: EvaluateOptions): Result<Decision, PolicyEvaluationError>;
/**
 * Evaluates a named map of policies and returns a decisions record.
 */
export declare function evaluateBatch(policies: PoliciesMap, context: EvaluationContext, options?: EvaluateOptions): Readonly<Record<string, Result<Decision, PolicyEvaluationError>>>;
/**
 * Interface for resolving subject or resource attributes asynchronously.
 * Used with evaluateAsync() to support dynamic attribute lookups.
 */
export interface AttributeResolver {
	/**
	 * Resolves the value of an attribute for a given subject.
	 * @param subjectId - The subject identifier
	 * @param attribute - The attribute name to resolve
	 * @param resource - Optional resource context for resource-scoped attributes
	 */
	resolve(subjectId: string, attribute: string, resource?: Readonly<Record<string, unknown>>): Promise<unknown>;
}
/**
 * Options for async evaluation.
 */
export interface AsyncEvaluateOptions extends EvaluateOptions {
	/** Timeout in milliseconds for attribute resolution. Default: 5000ms. */
	readonly resolverTimeoutMs?: number;
	/** Maximum number of concurrent attribute resolutions. Default: 10. */
	readonly maxConcurrentResolutions?: number;
}
/**
 * Error union for async evaluation failures.
 */
export type AsyncEvaluationError = PolicyEvaluationError | AttributeResolveTimeoutError | AttributeResolveError;
/**
 * Evaluates an authorization policy asynchronously, resolving dynamic attributes
 * via the provided AttributeResolver before calling the synchronous evaluate().
 *
 * - \`evaluatedAt\` is captured BEFORE async resolution begins (GxP requirement)
 * - Resolved attributes are merged into the subject's attributes for the evaluation
 * - Short-circuit preservation: the resolver is invoked for all attributes found
 *   in the policy tree, then synchronous evaluate() handles the rest
 */
export declare function evaluateAsync(policy: PolicyConstraint, context: EvaluationContext, resolver: AttributeResolver, options?: AsyncEvaluateOptions): Promise<Result<Decision, AsyncEvaluationError>>;
/**
 * A branded port type that serves as a compile-time contract for a service interface.
 *
 * The Port type uses TypeScript's structural typing with a branded property
 * to achieve nominal typing. Two ports are only compatible if they have:
 * 1. The same service interface type \`T\`
 * 2. The same port name \`TName\`
 *
 * @typeParam TName - The literal string type for the port name (defaults to \`string\`)
 * @typeParam T - The service interface type (phantom type - exists only at compile time)
 *
 * @remarks
 * - The \`__brand\` property carries both the service type and name in a tuple
 * - The \`__portName\` property exposes the name for debugging and error messages
 * - Both properties are readonly to prevent modification
 * - The brand symbol value is \`undefined\` at runtime (zero overhead)
 *
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link InferService} - Utility to extract the service type from a port
 * @see {@link InferPortName} - Utility to extract the name type from a port
 *
 * @example Direct type usage
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * // Create typed port tokens
 * type ConsoleLoggerPort = Port<'ConsoleLogger', Logger>;
 * type FileLoggerPort = Port<'FileLogger', Logger>;
 *
 * // These are type-incompatible despite same interface
 * declare const consolePort: ConsoleLoggerPort;
 * declare const filePort: FileLoggerPort;
 * // consolePort = filePort; // Type error!
 * \`\`\`
 *
 * @example With createPort (recommended)
 * \`\`\`typescript
 * // Use createPort for value + type duality
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerPortType = typeof LoggerPort;
 * \`\`\`
 */
export type Port<TName extends string, T> = {
	/**
	 * Brand property for nominal typing.
	 * Contains a tuple of [PortName, ServiceType] at the type level.
	 * Value is undefined at runtime.
	 */
	readonly __brand: [
		TName,
		T
	];
	/**
	 * The port name, exposed for debugging and error messages.
	 */
	readonly __portName: TName;
};
declare const __metadataKey: unique symbol;
/**
 * Discriminator for hexagonal architecture port types.
 *
 * - \`'inbound'\` - Driving ports (use cases, primary adapters)
 * - \`'outbound'\` - Driven ports (infrastructure, secondary adapters)
 *
 * @see {@link DirectedPort} - The port type that carries direction
 * @see {@link createInboundPort} - Factory for inbound ports
 * @see {@link createOutboundPort} - Factory for outbound ports
 */
export type PortDirection = "inbound" | "outbound";
/**
 * Optional metadata for documenting ports.
 *
 * Metadata provides human-readable documentation that can be used for:
 * - IDE tooltips and documentation
 * - Dependency graph visualization
 * - API documentation generation
 *
 * All properties are optional and readonly.
 *
 * @example
 * \`\`\`typescript
 * const UserServicePort = createInboundPort<'UserService', UserService>({
 *   name: 'UserService',
 *   description: 'Handles user CRUD operations',
 *   category: 'domain',
 *   tags: ['user', 'crud', 'core'],
 * });
 * \`\`\`
 */
export interface PortMetadata {
	/** Human-readable description of the port's purpose */
	readonly description?: string;
	/** Categorical grouping for organization */
	readonly category?: string;
	/** Searchable tags for filtering and discovery */
	readonly tags?: readonly string[];
}
/**
 * A port with hexagonal architecture direction and optional metadata.
 *
 * DirectedPort extends the base Port type with additional type-level branding:
 * - \`TDirection\` - Whether this is an inbound (driving) or outbound (driven) port
 * - Metadata association for documentation purposes
 *
 * DirectedPorts are structurally compatible with base Ports, enabling gradual
 * adoption without breaking existing code.
 *
 * @typeParam TName - The literal string type for the port name
 * @typeParam TService - The service interface type (phantom type)
 * @typeParam TDirection - 'inbound' or 'outbound'
 *
 * @see {@link InboundPort} - Convenience alias for inbound directed ports
 * @see {@link OutboundPort} - Convenience alias for outbound directed ports
 * @see {@link createInboundPort} - Factory for creating inbound ports
 * @see {@link createOutboundPort} - Factory for creating outbound ports
 *
 * @example
 * \`\`\`typescript
 * // DirectedPort is assignable to Port (backward compatible)
 * const port: DirectedPort<'Logger', Logger, 'inbound'> = createInboundPort({
 *   name: 'Logger',
 * });
 * const basePort: Port<'Logger', Logger> = port; // OK
 * \`\`\`
 */
export type DirectedPort<TName extends string, TService, TDirection extends PortDirection, TCategory extends string = string> = Port<TName, TService> & {
	readonly __directionBrand: TDirection;
	readonly __metadataKey: PortMetadata;
	readonly __categoryBrand: TCategory;
};
/**
 * Port providing the current authorization subject for a request scope.
 *
 * This is a scoped outbound port: each request scope resolves a fresh
 * subject from the identity infrastructure (JWT, session, API key, etc.).
 */
export declare const SubjectProviderPort: DirectedPort<"SubjectProvider", AuthSubject, "outbound", string>;
/**
 * Creates a simple static subject adapter factory.
 *
 * This is a convenience for testing and simple use cases where
 * the subject is known at construction time.
 */
export declare function createSubjectAdapter(subject: AuthSubject): () => AuthSubject;
/**
 * A map of method names to their per-method authorization policies.
 */
export type MethodPolicyMap<TKeys extends string = string> = Readonly<Partial<Record<TKeys, PolicyConstraint>>>;
/**
 * Options for the guard() factory.
 */
export interface GuardOptions {
	readonly resolve: PolicyConstraint;
	readonly methodPolicies?: MethodPolicyMap;
	/** When true, audit write failure throws AuditTrailWriteError. Default: true. */
	readonly failOnAuditError?: boolean;
	/**
	 * Optional callback adapter for receiving field-level visibility context.
	 * Called when an Allow decision carries \`visibleFields\`.
	 * Use this to register a FieldMaskContextPort in the enclosing DI scope.
	 */
	readonly fieldMaskAdapter?: {
		readonly onVisibleFields: (fields: ReadonlyArray<string>, evaluationId: string) => void;
	};
}
/**
 * A single audit trail entry recording an authorization decision.
 */
export interface AuditEntry {
	readonly evaluationId: string;
	readonly timestamp: string;
	readonly subjectId: string;
	readonly authenticationMethod: string;
	readonly policy: string;
	readonly decision: "allow" | "deny";
	readonly portName: string;
	readonly scopeId: string;
	readonly reason: string;
	readonly durationMs: number;
	readonly schemaVersion: number;
	readonly sessionId?: string;
	readonly identityProvider?: string;
	readonly sequenceNumber?: number;
	readonly traceDigest?: string;
	readonly policySnapshot?: string;
	readonly tenantId?: string;
}
/**
 * Service interface for recording authorization audit entries.
 */
export interface AuditTrail {
	record(entry: AuditEntry): Result<void, AuditTrailWriteError>;
}
/**
 * Port for the audit trail service.
 */
export interface AuditTrailPort {
	record(entry: AuditEntry): Result<void, AuditTrailWriteError>;
}
/**
 * A clock source for timestamping.
 */
export interface ClockSource {
	now(): string;
}
/**
 * System clock implementation using Date.toISOString().
 * Produces ISO 8601 UTC timestamps suitable for audit entries.
 * @warning Not suitable for GxP environments without NTP synchronization.
 */
export declare class SystemClock implements ClockSource {
	now(): string;
}
/**
 * An electronic signature captured for a policy evaluation.
 */
export interface ElectronicSignature {
	readonly signerId: string;
	readonly signerName?: string;
	readonly signedAt: string;
	readonly meaning: string;
	readonly validated: boolean;
	readonly reauthenticated: boolean;
	readonly signerRoles?: ReadonlyArray<string>;
	readonly algorithm?: string;
}
/**
 * Service interface for capturing and validating electronic signatures.
 */
export interface SignatureService {
	capture(meaning: string, signerRole?: string): Promise<ElectronicSignature>;
	validate(signature: ElectronicSignature): boolean;
}
/**
 * Port for the signature service.
 */
export type SignatureServicePort = SignatureService;
/**
 * Error produced when the guard denies access.
 */
export interface GuardAccessDeniedError extends Error {
	readonly code: "ACL001";
	readonly policy: PolicyConstraint;
	readonly decision: Deny;
	readonly portName: string;
	readonly subjectId: string;
}
/**
 * GxP-specific audit entry extension with required integrity fields.
 *
 * In GxP environments all three hash/signature fields must be populated
 * for ALCOA+ compliance. Use \`createNoopAuditTrailAdapter()\` only in
 * non-GxP test environments — production systems must provide a
 * cryptographically sound AuditTrail implementation.
 */
export interface GxPAuditEntry extends AuditEntry {
	readonly integrityHash: string;
	readonly previousHash: string;
	readonly signature: string;
	readonly hashChain?: string;
	readonly electronicSignature?: ElectronicSignature;
	readonly sequenceNumber: number;
	readonly traceDigest: string;
	readonly policySnapshot: string;
	readonly hashAlgorithm?: string;
}
/**
 * Port for providing field-level visibility context.
 * Registered in scope when an Allow decision carries \`visibleFields\`.
 */
export interface FieldMaskContextPort {
	/** Returns the set of fields visible for the current authorization context. */
	getVisibleFields(): ReadonlyArray<string>;
}
/**
 * Audit entry recording a policy configuration change event.
 * Used for change-control traceability in GxP-regulated systems.
 */
export interface PolicyChangeAuditEntry extends AuditEntry {
	readonly changeType: "create" | "update" | "delete" | "activate" | "deactivate";
	readonly changeControlId?: string;
	readonly previousPolicyHash?: string;
	readonly newPolicyHash?: string;
	readonly approvedBy?: string;
}
/**
 * Result from the guard health check.
 */
export interface GuardHealthCheckResult {
	readonly healthy: boolean;
	readonly auditTrailReachable: boolean;
	readonly checkedAt: string;
	readonly latencyMs: number;
	readonly errors: readonly string[];
}
/**
 * Port for querying the audit trail.
 */
export interface AuditQueryPort {
	queryByEvaluationId(id: string): AuditEntry | undefined;
	queryBySubjectId(subjectId: string, options?: {
		readonly from?: string;
		readonly to?: string;
	}): readonly AuditEntry[];
	queryByTimeRange(from: string, to: string, options?: {
		readonly decision?: "allow" | "deny";
	}): readonly AuditEntry[];
	queryByPortName(portName: string, options?: {
		readonly from?: string;
		readonly to?: string;
	}): readonly AuditEntry[];
	exportEntries(options?: {
		readonly format?: "json" | "jsonl" | "csv";
	}): string;
}
/**
 * Error thrown when guard() denies access during adapter resolution.
 */
declare class AccessDeniedError\$1 extends Error {
	readonly policy: PolicyConstraint;
	readonly decision: Decision & {
		kind: "deny";
	};
	readonly portName: string;
	readonly subjectId: string;
	readonly code: "ACL001";
	constructor(policy: PolicyConstraint, decision: Decision & {
		kind: "deny";
	}, portName: string, subjectId: string);
}
/**
 * Error thrown when an audit trail write fails and failOnAuditError is true.
 */
export declare class AuditWriteFailedError extends Error {
	readonly writeError: AuditTrailWriteError;
	readonly code: "ACL008";
	constructor(writeError: AuditTrailWriteError);
}
/**
 * Discriminated union of errors returned by enforcePolicy().
 */
export type EnforcePolicyError = AccessDeniedError\$1 | AuditWriteFailedError | PolicyEvaluationError;
/**
 * Enforces a policy before delegating to the subject factory.
 *
 * This is the core enforcement logic called by guard adapters.
 * It is synchronous by design.
 */
export declare function enforcePolicy(options: {
	readonly policy: PolicyConstraint;
	readonly subject: AuthSubject;
	readonly portName: string;
	readonly scopeId: string;
	readonly auditTrail: AuditTrail | null;
	readonly failOnAuditError: boolean;
	readonly resource?: Readonly<Record<string, unknown>>;
	readonly fieldMaskAdapter?: {
		readonly onVisibleFields: (fields: ReadonlyArray<string>, evaluationId: string) => void;
	};
}): Result<void, EnforcePolicyError>;
/**
 * Creates a no-op audit trail adapter that discards all entries.
 *
 * @gxpWarning NOT SUITABLE FOR GxP-REGULATED ENVIRONMENTS.
 * This adapter discards all audit entries without persisting them.
 * Production systems must provide a cryptographically sound AuditTrail
 * implementation that meets ALCOA+ requirements.
 */
export declare function createNoopAuditTrailAdapter(): AuditTrailPort;
/**
 * Guard graph descriptor returned by createGuardGraph().
 * Provides factory methods for constructing guard infrastructure.
 */
export interface GuardGraph {
	/** Creates a noop audit trail for non-GxP environments. */
	readonly noopAuditTrail: AuditTrailPort;
	/** Runs the policy enforcer inline for testing. */
	enforce(options: {
		readonly policy: PolicyConstraint;
		readonly subject: AuthSubject;
		readonly portName: string;
		readonly scopeId: string;
		readonly auditTrail?: AuditTrail;
		readonly failOnAuditError?: boolean;
		readonly resource?: Readonly<Record<string, unknown>>;
	}): Result<void, EnforcePolicyError>;
}
/**
 * Creates a self-contained guard graph with the given configuration.
 * This is the primary factory for composing guard infrastructure in application graphs.
 *
 * @example
 * \`\`\`ts
 * const guard = createGuardGraph();
 * guard.enforce({ policy, subject, portName: "UserPort", scopeId: scope.id });
 * \`\`\`
 */
export declare function createGuardGraph(): GuardGraph;
/**
 * Runs a health check against the guard infrastructure.
 * Tests audit trail reachability with a probe entry.
 */
export declare function createGuardHealthCheck(auditTrail: AuditTrailPort): () => GuardHealthCheckResult;
/**
 * Tracks port resolution vs audit entry counts for completeness monitoring.
 */
export interface CompletenessMonitor {
	recordResolution(portName: string): void;
	recordAuditEntry(portName: string): void;
	queryCompleteness(portName: string): {
		readonly resolutions: number;
		readonly auditEntries: number;
		readonly discrepancy: number;
	};
	readonly portNames: readonly string[];
}
/**
 * Creates a completeness monitor for tracking resolution/audit parity.
 * GxP REQUIRED when gxp: true.
 */
export declare function createCompletenessMonitor(): CompletenessMonitor;
/**
 * Creates a PolicyChangeAuditEntry for recording policy administration events.
 * All required AuditEntry fields are populated with sensible defaults.
 *
 * @example
 * \`\`\`ts
 * const entry = createPolicyChangeAuditEntry({
 *   subjectId: "admin-1",
 *   changeType: "update",
 *   changeControlId: "CCR-2024-001",
 *   portName: "PolicyPort",
 *   scopeId: scope.id,
 * });
 * \`\`\`
 */
export declare function createPolicyChangeAuditEntry(options: {
	readonly subjectId: string;
	readonly changeType: PolicyChangeAuditEntry["changeType"];
	readonly portName: string;
	readonly scopeId: string;
	readonly changeControlId?: string;
	readonly previousPolicyHash?: string;
	readonly newPolicyHash?: string;
	readonly approvedBy?: string;
	readonly authenticationMethod?: string;
	readonly sessionId?: string;
	readonly identityProvider?: string;
	readonly evaluationId?: string;
	readonly timestamp?: string;
	readonly reason?: string;
}): PolicyChangeAuditEntry;
/**
 * An event emitted when a guard evaluation allows access.
 */
export interface GuardAllowEvent {
	readonly kind: "guard.allow";
	readonly evaluationId: string;
	readonly portName: string;
	readonly subjectId: string;
	readonly decision: Decision & {
		kind: "allow";
	};
	readonly timestamp: string;
}
/**
 * An event emitted when a guard evaluation denies access.
 */
export interface GuardDenyEvent {
	readonly kind: "guard.deny";
	readonly evaluationId: string;
	readonly portName: string;
	readonly subjectId: string;
	readonly decision: Decision & {
		kind: "deny";
	};
	readonly timestamp: string;
}
/**
 * An event emitted when a guard encounters an error (ACL008, ACL018, ACL009, ACL014).
 */
export interface GuardErrorEvent {
	readonly kind: "guard.error";
	readonly evaluationId: string;
	readonly portName: string;
	readonly subjectId: string;
	readonly errorCode: string;
	readonly message: string;
	readonly timestamp: string;
}
/**
 * Discriminated union of all guard events.
 */
export type GuardEvent = GuardAllowEvent | GuardDenyEvent | GuardErrorEvent;
/**
 * Sink interface for receiving guard events.
 */
export interface GuardEventSink {
	emit(event: GuardEvent): void;
}
/**
 * Port for the guard event sink.
 */
export type GuardEventSinkPort = GuardEventSink;
/**
 * A no-operation event sink that discards all events.
 * Zero overhead when registered; use when event emission is not required.
 */
export declare const NoopGuardEventSink: GuardEventSink;
/**
 * Attributes attached to a guard evaluation span.
 */
export interface GuardSpanAttributes {
	readonly "hex-di.guard.evaluationId": string;
	readonly "hex-di.guard.portName": string;
	readonly "hex-di.guard.subjectId": string;
	readonly "hex-di.guard.decision": "allow" | "deny";
	readonly "hex-di.guard.policyKind": string;
	readonly "hex-di.guard.durationMs": number;
	readonly "hex-di.guard.scopeId": string;
}
/**
 * Handle for a live guard evaluation span.
 */
export interface GuardSpanHandle {
	end(): void;
	setError(message: string): void;
	setAttribute(key: string, value: string | number | boolean): void;
}
/**
 * Sink interface for receiving guard evaluation spans.
 */
export interface GuardSpanSink {
	startSpan(name: string, attributes: Partial<GuardSpanAttributes>): GuardSpanHandle;
}
/**
 * Port for the guard span sink.
 */
export type GuardSpanSinkPort = GuardSpanSink;
/**
 * A no-operation span sink that creates no-op span handles.
 * Zero overhead when registered; use when span emission is not required.
 */
export declare const NoopGuardSpanSink: GuardSpanSink;
/**
 * A write-ahead log entry wrapping an audit entry with commit state.
 */
export interface WalEntry {
	readonly id: string;
	readonly timestamp: string;
	readonly entry: AuditEntry;
	readonly committed: boolean;
}
/**
 * Error type returned by WAL operations.
 */
export interface WalError {
	readonly code: typeof ACL010;
	readonly message: string;
	readonly cause?: unknown;
}
/**
 * A write-ahead log for durable audit entry persistence.
 * Uncommitted entries survive logical process restart (via recover()).
 */
export interface WriteAheadLog {
	/** Appends an audit entry to the WAL. Returns the WAL entry id. */
	append(entry: AuditEntry): Result<string, WalError>;
	/** Marks a WAL entry as committed (permanently persisted). */
	commit(id: string): Result<void, WalError>;
	/** Rolls back (removes) an uncommitted WAL entry. */
	rollback(id: string): Result<void, WalError>;
	/** Returns all uncommitted entries (for crash recovery). */
	recover(): readonly WalEntry[];
	/** Returns all entries (committed and uncommitted). */
	entries(): readonly WalEntry[];
}
/**
 * Creates an in-memory write-ahead log.
 * Uncommitted entries are recoverable via recover().
 */
export declare function createWriteAheadLog(): WriteAheadLog;
/**
 * Possible states of a circuit breaker.
 */
export type CircuitBreakerState = "closed" | "open" | "half-open";
/**
 * Options for creating a circuit breaker.
 */
export interface CircuitBreakerOptions {
	/** Number of consecutive failures before opening the circuit. */
	readonly failureThreshold: number;
	/** Time in milliseconds before attempting to reset from open to half-open. */
	readonly resetTimeoutMs: number;
}
/**
 * A circuit breaker that protects a resource from cascading failures.
 */
export interface CircuitBreaker {
	/** Returns the current state of the circuit. */
	readonly state: CircuitBreakerState;
	/**
	 * Records a successful operation. If in half-open, transitions to closed.
	 */
	recordSuccess(): void;
	/**
	 * Records a failed operation. Increments failure count; opens circuit if threshold reached.
	 */
	recordFailure(): void;
	/**
	 * Returns a CircuitOpenError if the circuit is open, undefined otherwise.
	 * In half-open state, allows one probe through (returns undefined).
	 */
	check(): CircuitOpenError | undefined;
}
/**
 * Creates a circuit breaker with the given options.
 *
 * State transitions:
 * - closed → open: after \`failureThreshold\` consecutive failures
 * - open → half-open: after \`resetTimeoutMs\` ms
 * - half-open → closed: on next success
 * - half-open → open: on next failure
 */
export declare function createCircuitBreaker(options: CircuitBreakerOptions): CircuitBreaker;
/**
 * Result from scope disposal chain verification.
 */
export interface DisposalChainResult {
	readonly verified: boolean;
	readonly undisposed: readonly string[];
}
/**
 * Tracks scope disposal state and verifies disposal chains.
 */
export interface ScopeDisposalVerifier {
	/** Registers a scope as requiring disposal. */
	register(scopeId: string): void;
	/** Marks a scope as disposed. */
	dispose(scopeId: string): void;
	/** Returns true if the given scope has been disposed. */
	isDisposed(scopeId: string): boolean;
	/** Verifies that all registered scopes have been disposed. */
	verifyAll(): DisposalChainResult;
	/** Verifies that the specified scopes have all been disposed. */
	verify(scopeIds: readonly string[]): DisposalChainResult;
}
/**
 * Creates a scope disposal verifier that tracks which scopes have been disposed.
 */
export declare function createScopeDisposalVerifier(): ScopeDisposalVerifier;
/**
 * Detects clock drift between the system clock and an external reference time.
 *
 * @param systemTimeMs - Current system time in milliseconds (Date.now())
 * @param externalTimeMs - External reference time in milliseconds
 * @returns The absolute drift in milliseconds
 */
export declare function detectClockDrift(systemTimeMs: number, externalTimeMs: number): number;
/**
 * Checks for clock drift and returns a ClockDriftWarning if the drift exceeds the threshold.
 *
 * @param systemTimeMs - Current system time in milliseconds
 * @param externalTimeMs - External reference time in milliseconds
 * @param thresholdMs - Drift threshold in milliseconds (default: 1000ms)
 * @returns A ClockDriftWarning if drift exceeds threshold, undefined otherwise
 */
export declare function checkClockDrift(systemTimeMs: number, externalTimeMs: number, thresholdMs?: number): ClockDriftWarning | undefined;
/**
 * Policy for data retention enforcement.
 */
export interface RetentionPolicy {
	/** Maximum age of entries in days. Entries older than this are removed. */
	readonly maxAgeDays: number;
	/** Maximum total number of entries to retain. Oldest are removed first. */
	readonly maxEntries?: number;
}
/**
 * Enforces a retention policy against a list of audit entries.
 * Returns the entries that should be retained (not purged).
 *
 * Entries are first filtered by age (maxAgeDays), then by count (maxEntries),
 * retaining the most recent entries when count exceeds the limit.
 */
export declare function enforceRetention(entries: readonly AuditEntry[], policy: RetentionPolicy): readonly AuditEntry[];
/**
 * Returns the entries that would be purged by the given retention policy.
 */
export declare function getPurgeableEntries(entries: readonly AuditEntry[], policy: RetentionPolicy): readonly AuditEntry[];
/**
 * An audit entry recording access to the audit trail itself (audit of audit).
 * Implements ALCOA+ requirement for complete and accurate audit records.
 */
export interface MetaAuditEntry {
	readonly _tag: "MetaAuditEntry";
	readonly metaAuditId: string;
	readonly timestamp: string;
	readonly actorId: string;
	readonly accessType: "read" | "export" | "verify" | "replay";
	readonly description: string;
	readonly entryCount: number;
	readonly simulated: boolean;
	readonly scope: string;
	readonly dataClassification?: string;
}
/**
 * An audit entry recording changes to the dataClassification field.
 */
export interface DataClassificationChangeEntry {
	readonly _tag: "DataClassificationChangeEntry";
	readonly changeId: string;
	readonly timestamp: string;
	readonly actorId: string;
	readonly scope: string;
	readonly previousClassification: string | undefined;
	readonly newClassification: string;
	readonly reason: string;
}
/**
 * Service interface for recording meta-audit entries.
 */
export interface MetaAuditTrail {
	recordAccess(entry: MetaAuditEntry): Result<void, MetaAuditWriteError>;
	recordClassificationChange(entry: DataClassificationChangeEntry): Result<void, MetaAuditWriteError>;
}
/**
 * Port for the meta-audit trail service.
 */
export type MetaAuditTrailPort = MetaAuditTrail;
/**
 * Creates a MetaAuditEntry with a generated ID and current timestamp.
 */
export declare function createMetaAuditEntry(options: {
	readonly actorId: string;
	readonly accessType: MetaAuditEntry["accessType"];
	readonly description: string;
	readonly entryCount: number;
	readonly scope: string;
	readonly simulated?: boolean;
	readonly dataClassification?: string;
}): MetaAuditEntry;
/**
 * Creates a DataClassificationChangeEntry.
 */
export declare function createDataClassificationChangeEntry(options: {
	readonly actorId: string;
	readonly scope: string;
	readonly previousClassification: string | undefined;
	readonly newClassification: string;
	readonly reason: string;
}): DataClassificationChangeEntry;
/**
 * Creates a no-op meta-audit trail that discards all entries.
 * Not suitable for GxP environments.
 */
export declare function createNoopMetaAuditTrail(): MetaAuditTrailPort;
/**
 * Archived audit trail following the guard-audit-archive schema.
 */
export interface GuardAuditArchive {
	readonly archiveVersion: "guard-audit-archive@1.0.0";
	readonly metadata: {
		readonly createdAt: string;
		readonly entryCount: number;
		readonly chainIntegrityVerified: boolean;
	};
	readonly chains: ReadonlyArray<{
		readonly scopeId: string;
		readonly entries: ReadonlyArray<AuditEntry>;
	}>;
	readonly keyMaterial?: ReadonlyArray<{
		readonly keyId: string;
		readonly algorithm: string;
		readonly publicKey: string;
	}>;
}
/**
 * A required step in the decommissioning checklist.
 */
export interface DecommissioningStep {
	readonly id: string;
	readonly description: string;
	readonly required: boolean;
	readonly completed: boolean;
	readonly completedAt?: string;
	readonly completedBy?: string;
}
/**
 * Decommissioning checklist ensuring all required steps are performed.
 */
export interface DecommissioningChecklist {
	readonly checklistId: string;
	readonly createdAt: string;
	readonly steps: ReadonlyArray<DecommissioningStep>;
	readonly allRequiredComplete: boolean;
}
/**
 * Options for archiving an audit trail.
 */
export interface ArchivalOptions {
	readonly keyMaterial?: ReadonlyArray<{
		readonly keyId: string;
		readonly algorithm: string;
		readonly publicKey: string;
	}>;
	/** Whether to skip chain integrity verification (not recommended). */
	readonly skipIntegrityVerification?: boolean;
}
/**
 * Archives an audit trail into a portable archive format.
 *
 * Verifies chain integrity before archival. Rejects if gaps are found
 * (unless skipIntegrityVerification is set).
 */
export declare function archiveAuditTrail(entries: readonly AuditEntry[], options?: ArchivalOptions): Result<GuardAuditArchive, ArchivalError | ChainIntegrityError>;
/**
 * Creates a decommissioning checklist with the standard required steps.
 */
export declare function createDecommissioningChecklist(): DecommissioningChecklist;
/**
 * Returns an updated checklist with the specified step marked as complete.
 */
export declare function completeDecommissioningStep(checklist: DecommissioningChecklist, stepId: string, completedBy: string): DecommissioningChecklist;
/**
 * Options for scope-level access control.
 */
export interface ScopeOptions {
	/** Time-to-live for the scope in milliseconds. Enforces calls before expiry. */
	readonly ttlMs?: number;
	/** Maximum number of calls allowed within the rate limit window. */
	readonly maxCallsPerWindow?: number;
	/** Rate limit window size in milliseconds. Default: 60000 (1 minute). */
	readonly windowMs?: number;
}
/**
 * Registry tracking per-scope call counts and creation timestamps.
 */
export interface ScopeRegistry {
	/**
	 * Registers a new scope with the given options.
	 * Must be called before checking scope validity.
	 */
	register(scopeId: string, options?: ScopeOptions): void;
	/**
	 * Checks scope validity and increments call count.
	 * Returns a ScopeExpiredError or RateLimitExceededError if the scope is invalid.
	 */
	check(scopeId: string): ScopeExpiredError | RateLimitExceededError | undefined;
	/** Removes a scope from the registry (called on dispose). */
	unregister(scopeId: string): void;
	/** Returns the registered options for a scope (for testing). */
	getOptions(scopeId: string): ScopeOptions | undefined;
	/**
	 * Disposes all scopes whose TTL has elapsed.
	 * Returns the number of scopes disposed.
	 * Callers (e.g. periodic timer) can use this to bound memory growth.
	 */
	disposeExpired(): number;
}
/**
 * Creates an in-memory scope registry for TTL and rate-limit enforcement.
 */
export declare function createScopeRegistry(): ScopeRegistry;
/**
 * A gate rule for a single port.
 */
export type PortGateRule = {
	readonly action: "deny";
	readonly reason: string;
} | {
	readonly action: "allow";
};
/**
 * Configuration for the port gate hook.
 */
export interface PortGateConfig {
	readonly [portName: string]: PortGateRule;
}
/**
 * Error thrown when a port gate denies resolution.
 */
export declare class PortGatedError extends Error {
	readonly portName: string;
	readonly reason: string;
	readonly code: "ACL031";
	constructor(portName: string, reason: string);
}
/**
 * Resolution hook interface — minimal subset needed for typing.
 */
export interface ResolutionHook {
	beforeResolve(context: {
		readonly portName: string;
	}): void;
}
/**
 * Creates a beforeResolve hook that gates port resolution based on
 * a static configuration map.
 *
 * @gxp-warning This hook operates at the infrastructure level — it fires
 * BEFORE subject resolution and guard evaluation. Use it for coarse-grained
 * feature flags and environment-level port disabling. It does NOT produce
 * audit trail entries; for GxP-compliant access control, use enforcePolicy().
 */
export declare function createPortGateHook(config: PortGateConfig): ResolutionHook;
/**
 * Result from a GxP readiness check of port gating coverage.
 */
export interface GxPReadinessResult {
	readonly ready: boolean;
	readonly issues: readonly string[];
}
/**
 * Checks GxP readiness by verifying that every port with a gate
 * also has a guard() adapter registered.
 *
 * In GxP-regulated systems, coarse-grained port gates alone are
 * insufficient for audit compliance. Each gated port must also be
 * wrapped with enforcePolicy() (a guard adapter) to produce the
 * required ALCOA+ audit trail entries.
 *
 * @param portNamesWithGate - Port names that have a PortGateHook configured
 * @param portNamesWithGuard - Port names wrapped with a guard() adapter
 */
export declare function checkGxPReadiness(portNamesWithGate: readonly string[], portNamesWithGuard: readonly string[]): GxPReadinessResult;
/**
 * Error thrown when a role gate denies access.
 */
export declare class RoleGateError extends Error {
	readonly roleName: string;
	readonly subjectId: string;
	readonly code: "ACL007";
	constructor(roleName: string, subjectId: string);
}
/**
 * Resolution hook interface — minimal subset needed for typing.
 */
export interface RoleResolutionHook {
	beforeResolve(context: {
		readonly portName: string;
		readonly subject?: AuthSubject;
	}): void;
}
/**
 * Creates a beforeResolve hook that enforces a single role requirement
 * on every port resolution.
 *
 * The hook checks that the subject obtained from the context has the
 * specified role before allowing the resolution to proceed.
 *
 * @example
 * \`\`\`ts
 * const hook = createRoleGate("admin");
 * // Wire into the DI container's beforeResolve hook
 * \`\`\`
 */
export declare function createRoleGate(roleName: string): RoleResolutionHook;
export interface HashDigest {
	readonly sha256Hex: (data: string) => string;
	readonly timingSafeEqual: (a: string, b: string) => boolean;
}
/**
 * Serializes a policy tree to a deterministic JSON string.
 */
export declare function serializePolicy(policy: PolicyConstraint): string;
/**
 * Computes a deterministic SHA-256 hash of a policy tree.
 * Keys are sorted before hashing to ensure consistency regardless of
 * object property insertion order.
 *
 * @returns A hex-encoded SHA-256 digest string.
 */
export declare function hashPolicy(policy: PolicyConstraint, digest: HashDigest): string;
/**
 * Serializes an AuditEntry to a JSON string.
 */
export declare function serializeAuditEntry(entry: AuditEntry): string;
/**
 * Verifies the integrity of an audit chain.
 * Each entry's integrityHash should cover all required fields.
 * Returns true if all entries pass validation (no hash checking for basic AuditEntry,
 * but verifies sequenceNumber monotonicity and no gaps).
 */
export declare function verifyAuditChain(entries: readonly AuditEntry[]): boolean;
/**
 * Computes an audit chain integrity hash for a GxP audit entry.
 * Covers all required fields to satisfy ALCOA+ requirements.
 */
export declare function computeAuditEntryHash(entry: AuditEntry, previousHash: string, digest: HashDigest): string;
/**
 * Creates an audit export manifest for a set of audit entries.
 * \`chainIntegrityVerified\` is true when every entry carries an
 * \`integrityHash\` (i.e. all entries are GxPAuditEntry instances).
 */
export declare function createAuditExportManifest(options: {
	readonly entries: readonly AuditEntry[];
	readonly exportedAt: string;
	readonly exportedBy: string;
}): string;
/**
 * Deserializes a JSON string into a PolicyConstraint.
 * Returns Err(PolicyDeserializationError) if the JSON is invalid.
 */
export declare function deserializePolicy(json: string): Result<PolicyConstraint, PolicyDeserializationError>;
/**
 * Deserializes a JSON string into an AuditEntry.
 */
export declare function deserializeAuditEntry(json: string): Result<AuditEntry, AuditEntryParseError>;
/**
 * Produces a human-readable explanation of a policy tree.
 */
export declare function explainPolicy(policy: PolicyConstraint, indent?: number): string;
/**
 * Electronic signature types for 21 CFR Part 11 compliance.
 */
interface ElectronicSignature\$1 {
	readonly signerId: string;
	readonly signerName?: string;
	readonly signedAt: string;
	readonly meaning: string;
	readonly validated: boolean;
	readonly reauthenticated: boolean;
	readonly signerRoles?: ReadonlyArray<string>;
	readonly keyId?: string;
	readonly algorithm?: string;
}
export interface SignatureCaptureRequest {
	readonly meaning: string;
	readonly signerRole?: string;
	readonly resourceId?: string;
	readonly resourceType?: string;
}
export interface ReauthenticationChallenge {
	readonly challengeId: string;
	readonly challengeType: "password" | "mfa" | "certificate";
	readonly issuedAt: string;
	readonly expiresAt: string;
}
export interface ReauthenticationToken {
	readonly challengeId: string;
	readonly completedAt: string;
	readonly method: string;
}
export interface SignatureValidationResult {
	readonly valid: boolean;
	readonly reason?: string;
	readonly validatedAt: string;
}
/**
 * Service interface for capturing and validating electronic signatures.
 */
interface SignatureServicePort\$1 {
	capture(request: SignatureCaptureRequest): Promise<ElectronicSignature\$1>;
	validate(signature: ElectronicSignature\$1): Promise<SignatureValidationResult>;
}
/**
 * A no-op signature service that always validates successfully.
 * For use in non-regulated environments only.
 */
export declare const NoopSignatureService: SignatureServicePort\$1;
/**
 * Standard electronic signature meaning constants.
 *
 * These are the recommended vocabulary for hasSignature policy \`meaning\` fields.
 * Organizations may extend this with site-specific meanings.
 */
export declare const SIGNATURE_MEANINGS: Readonly<{
	/** The signer authored/created the record. */
	readonly AUTHORED: "authored";
	/** The signer reviewed the record. */
	readonly REVIEWED: "reviewed";
	/** The signer approved the record. */
	readonly APPROVED: "approved";
	/** The signer rejected the record. */
	readonly REJECTED: "rejected";
	/** A second signer verified the record (counter-signature). */
	readonly WITNESSED: "witnessed";
	/** The signer released the record for the next workflow stage. */
	readonly RELEASED: "released";
	/** The signer witnessed the destruction/disposal of the record. */
	readonly WITNESSED_DESTRUCTION: "witnessed-destruction";
}>;
export type SignatureMeaning = (typeof SIGNATURE_MEANINGS)[keyof typeof SIGNATURE_MEANINGS];
/**
 * Snapshot of guard runtime state for devtools display.
 */
export interface GuardInspectionSnapshot {
	readonly activePolicies: Readonly<Record<string, string>>;
	readonly recentDecisions: ReadonlyArray<{
		readonly evaluationId: string;
		readonly portName: string;
		readonly decision: "allow" | "deny";
		readonly subjectId: string;
		readonly evaluatedAt: string;
	}>;
	readonly permissionStats: Readonly<Record<string, {
		readonly allow: number;
		readonly deny: number;
	}>>;
}
/**
 * A listener function for guard inspection events.
 */
export type GuardInspectionEventListener = (event: GuardEvent) => void;
/**
 * DevTools inspector for the guard library.
 * Implements the LibraryInspector protocol for integration with HexDI DevTools.
 *
 * Call onEvent() from guard enforcement hooks to feed events into the inspector.
 */
export declare class GuardInspector {
	readonly name = "guard";
	private readonly _activePolicies;
	private readonly _recentDecisions;
	private readonly _permissionStats;
	private readonly _listeners;
	/**
	 * Returns a snapshot of the current guard state.
	 */
	getSnapshot(): GuardInspectionSnapshot;
	/**
	 * Subscribes to guard inspection events.
	 * Returns an unsubscribe function.
	 */
	subscribe(listener: GuardInspectionEventListener): () => void;
	/**
	 * Called by guard enforcement hooks to feed events into the inspector.
	 */
	onEvent(event: GuardEvent): void;
	/**
	 * Registers an active policy for a named port.
	 */
	registerPolicy(portName: string, policyKind: string): void;
	/**
	 * Clears all recorded state (useful for testing).
	 */
	reset(): void;
	private _recordDecision;
	private _recordStat;
}
/**
 * Infers the resource type from a Permission token.
 */
export type InferResource<P extends PermissionConstraint> = P extends Permission<infer R, string> ? R : never;
/**
 * Infers the action type from a Permission token.
 */
export type InferAction<P extends PermissionConstraint> = P extends Permission<string, infer A> ? A : never;
/**
 * Formats a Permission type as "resource:action" literal.
 */
export type FormatPermission<P extends PermissionConstraint> = P extends Permission<infer R, infer A> ? \`\${R}:\${A}\` : never;
/**
 * Infers all permissions from a Role token.
 */
export type InferPermissions<R extends RoleConstraint> = R extends Role<string, infer P, readonly RoleConstraint[]> ? P[number] : never;
/**
 * Infers the role name from a Role token.
 */
export type InferRoleName<R extends RoleConstraint> = R extends Role<infer N, readonly PermissionConstraint[], readonly RoleConstraint[]> ? N : never;
/**
 * Extracted requirements from a composite policy tree.
 */
export interface PolicyRequirements {
	readonly permissions: readonly PermissionConstraint[];
	readonly roleNames: readonly string[];
}
type Prev\$1 = [
	never,
	0,
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20
];
/**
 * Extracts all permission and role requirements from a composite policy tree
 * at the type level.
 */
export type InferPolicyRequirements<P extends PolicyConstraint, TDepth extends number = 20> = [
	TDepth
] extends [
	never
] ? PolicyRequirements : P extends HasPermissionPolicy<infer TPerm> ? {
	readonly permissions: readonly [
		TPerm
	];
	readonly roleNames: readonly [
	];
} : P extends HasRolePolicy<infer TRole> ? {
	readonly permissions: readonly [
	];
	readonly roleNames: readonly [
		TRole
	];
} : P extends AllOfPolicy<infer TPolicies> ? TPolicies extends readonly [
	infer H,
	...infer Tail
] ? H extends PolicyConstraint ? Tail extends readonly PolicyConstraint[] ? MergePolicyRequirements<InferPolicyRequirements<H, Prev\$1[TDepth]>, InferPolicyRequirements<AllOfPolicy<Tail>, Prev\$1[TDepth]>> : InferPolicyRequirements<H, Prev\$1[TDepth]> : PolicyRequirements : {
	readonly permissions: readonly [
	];
	readonly roleNames: readonly [
	];
} : P extends AnyOfPolicy<infer TPolicies> ? TPolicies extends readonly [
	infer H,
	...infer Tail
] ? H extends PolicyConstraint ? Tail extends readonly PolicyConstraint[] ? MergePolicyRequirements<InferPolicyRequirements<H, Prev\$1[TDepth]>, InferPolicyRequirements<AnyOfPolicy<Tail>, Prev\$1[TDepth]>> : InferPolicyRequirements<H, Prev\$1[TDepth]> : PolicyRequirements : {
	readonly permissions: readonly [
	];
	readonly roleNames: readonly [
	];
} : P extends NotPolicy<infer TInner> ? InferPolicyRequirements<TInner, Prev\$1[TDepth]> : P extends LabeledPolicy<infer TInner> ? InferPolicyRequirements<TInner, Prev\$1[TDepth]> : PolicyRequirements;
export type MergePolicyRequirements<A extends PolicyRequirements, B extends PolicyRequirements> = {
	readonly permissions: readonly [
		...A["permissions"],
		...B["permissions"]
	];
	readonly roleNames: readonly [
		...A["roleNames"],
		...B["roleNames"]
	];
};

export {
	AccessDeniedError as GuardAccessDeniedErrorType,
	AccessDeniedError\$1 as AccessDeniedError,
	ElectronicSignature\$1 as SignatureElectronicSignature,
	SignatureServicePort\$1 as SignaturePort,
};

export {};
}`;
