// Auto-generated by scripts/bundle-playground-types.ts
// Package: @hex-di/logger
export const dts = `declare module "@hex-di/logger" {
/**
 * Log level types and utilities.
 *
 * Defines the severity levels for log entries and provides
 * comparison utilities for level filtering.
 *
 * @packageDocumentation
 */
/**
 * Log level severity.
 */
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error" | "fatal";
/**
 * Numeric values for log levels, enabling comparison.
 */
export declare const LogLevelValue: Readonly<Record<LogLevel, number>>;
/**
 * Check if a level should be logged given a minimum level.
 *
 * @param level - The level of the log entry
 * @param minLevel - The minimum level threshold
 * @returns true if the entry level meets or exceeds the minimum
 */
export declare function shouldLog(level: LogLevel, minLevel: LogLevel): boolean;
/**
 * Log context carrying request-scoped data.
 */
export interface LogContext {
	readonly correlationId?: string;
	readonly requestId?: string;
	readonly userId?: string;
	readonly sessionId?: string;
	readonly scopeId?: string;
	readonly service?: string;
	readonly environment?: string;
	readonly [key: string]: unknown;
}
/**
 * Structured log entry.
 */
export interface LogEntry {
	readonly level: LogLevel;
	readonly message: string;
	readonly timestamp: number;
	/** Monotonic sequence number, unique per process. Enables ordering and gap detection. */
	readonly sequence: number;
	readonly context: LogContext;
	readonly annotations: Readonly<Record<string, unknown>>;
	readonly error?: Error;
	readonly spans?: ReadonlyArray<{
		readonly traceId: string;
		readonly spanId: string;
	}>;
	/** Optional tamper-evidence hash chain. Populated by withIntegrity() wrapper. */
	readonly integrity?: {
		readonly hash: string;
		readonly previousHash: string;
	};
}
/**
 * A branded port type that serves as a compile-time contract for a service interface.
 *
 * The Port type uses TypeScript's structural typing with a branded property
 * to achieve nominal typing. Two ports are only compatible if they have:
 * 1. The same service interface type \`T\`
 * 2. The same port name \`TName\`
 *
 * @typeParam TName - The literal string type for the port name (defaults to \`string\`)
 * @typeParam T - The service interface type (phantom type - exists only at compile time)
 *
 * @remarks
 * - The \`__brand\` property carries both the service type and name in a tuple
 * - The \`__portName\` property exposes the name for debugging and error messages
 * - Both properties are readonly to prevent modification
 * - The brand symbol value is \`undefined\` at runtime (zero overhead)
 *
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link InferService} - Utility to extract the service type from a port
 * @see {@link InferPortName} - Utility to extract the name type from a port
 *
 * @example Direct type usage
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * // Create typed port tokens
 * type ConsoleLoggerPort = Port<'ConsoleLogger', Logger>;
 * type FileLoggerPort = Port<'FileLogger', Logger>;
 *
 * // These are type-incompatible despite same interface
 * declare const consolePort: ConsoleLoggerPort;
 * declare const filePort: FileLoggerPort;
 * // consolePort = filePort; // Type error!
 * \`\`\`
 *
 * @example With createPort (recommended)
 * \`\`\`typescript
 * // Use createPort for value + type duality
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerPortType = typeof LoggerPort;
 * \`\`\`
 */
export type Port<TName extends string, T> = {
	/**
	 * Brand property for nominal typing.
	 * Contains a tuple of [PortName, ServiceType] at the type level.
	 * Value is undefined at runtime.
	 */
	readonly __brand: [
		TName,
		T
	];
	/**
	 * The port name, exposed for debugging and error messages.
	 */
	readonly __portName: TName;
};
/**
 * Error type returned when type inference utilities receive a non-Port type.
 *
 * This branded error provides actionable guidance in IDE tooltips when users
 * accidentally pass incorrect types to InferService or InferPortName.
 *
 * @typeParam T - The type that was passed (preserved for debugging)
 *
 * @remarks
 * Instead of returning opaque \`never\`, this error type provides:
 * - Clear error message explaining what was expected
 * - The actual type that was received (for debugging)
 * - A hint about common mistakes (e.g., forgetting \`typeof\`)
 *
 * @example IDE tooltip when misused
 * \`\`\`typescript
 * type Result = InferService<string>;
 * // Hovering shows:
 * // {
 * //   __errorBrand: "NotAPortError";
 * //   __message: "Expected a Port type created with createPort() or port()";
 * //   __received: string;
 * //   __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
 * // }
 * \`\`\`
 */
export type NotAPortError<T> = {
	readonly __errorBrand: "NotAPortError";
	readonly __message: "Expected a Port type created with createPort() or port()";
	readonly __received: T;
	readonly __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
};
/**
 * Extracts the service interface type from a Port type.
 *
 * This utility type uses conditional type inference to extract the phantom
 * type parameter \`T\` from a \`Port<TName, T>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the service from
 * @returns The service interface type \`T\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferPortName} - Companion utility to extract the port name
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerService = InferService<typeof LoggerPort>;
 * // LoggerService = Logger
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferService<string>;
 * // Invalid = NotAPortError<string>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferService<P> = P extends Port<infer _TName, infer T> ? T : NotAPortError<P>;
/**
 * Extracts the port name literal type from a Port type.
 *
 * This utility type uses conditional type inference to extract the name
 * type parameter \`TName\` from a \`Port<TName, T>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the name from
 * @returns The port name literal type \`TName\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferService} - Companion utility to extract the service type
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type PortName = InferPortName<typeof LoggerPort>;
 * // PortName = 'Logger'
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferPortName<number>;
 * // Invalid = NotAPortError<number>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferPortName<P> = P extends Port<infer TName, infer _T> ? TName : NotAPortError<P>;
declare const __metadataKey: unique symbol;
/**
 * Discriminator for hexagonal architecture port types.
 *
 * - \`'inbound'\` - Driving ports (use cases, primary adapters)
 * - \`'outbound'\` - Driven ports (infrastructure, secondary adapters)
 *
 * @see {@link DirectedPort} - The port type that carries direction
 * @see {@link createInboundPort} - Factory for inbound ports
 * @see {@link createOutboundPort} - Factory for outbound ports
 */
export type PortDirection = "inbound" | "outbound";
/**
 * Optional metadata for documenting ports.
 *
 * Metadata provides human-readable documentation that can be used for:
 * - IDE tooltips and documentation
 * - Dependency graph visualization
 * - API documentation generation
 *
 * All properties are optional and readonly.
 *
 * @example
 * \`\`\`typescript
 * const UserServicePort = createInboundPort<'UserService', UserService>({
 *   name: 'UserService',
 *   description: 'Handles user CRUD operations',
 *   category: 'domain',
 *   tags: ['user', 'crud', 'core'],
 * });
 * \`\`\`
 */
export interface PortMetadata {
	/** Human-readable description of the port's purpose */
	readonly description?: string;
	/** Categorical grouping for organization */
	readonly category?: string;
	/** Searchable tags for filtering and discovery */
	readonly tags?: readonly string[];
}
/**
 * A port with hexagonal architecture direction and optional metadata.
 *
 * DirectedPort extends the base Port type with additional type-level branding:
 * - \`TDirection\` - Whether this is an inbound (driving) or outbound (driven) port
 * - Metadata association for documentation purposes
 *
 * DirectedPorts are structurally compatible with base Ports, enabling gradual
 * adoption without breaking existing code.
 *
 * @typeParam TName - The literal string type for the port name
 * @typeParam TService - The service interface type (phantom type)
 * @typeParam TDirection - 'inbound' or 'outbound'
 *
 * @see {@link InboundPort} - Convenience alias for inbound directed ports
 * @see {@link OutboundPort} - Convenience alias for outbound directed ports
 * @see {@link createInboundPort} - Factory for creating inbound ports
 * @see {@link createOutboundPort} - Factory for creating outbound ports
 *
 * @example
 * \`\`\`typescript
 * // DirectedPort is assignable to Port (backward compatible)
 * const port: DirectedPort<'Logger', Logger, 'inbound'> = createInboundPort({
 *   name: 'Logger',
 * });
 * const basePort: Port<'Logger', Logger> = port; // OK
 * \`\`\`
 */
export type DirectedPort<TName extends string, TService, TDirection extends PortDirection, TCategory extends string = string> = Port<TName, TService> & {
	readonly __directionBrand: TDirection;
	readonly __metadataKey: PortMetadata;
	readonly __categoryBrand: TCategory;
};
/**
 * Discriminator for sync vs async factory functions.
 */
export type FactoryKind = "sync" | "async";
/**
 * Type representing empty dependencies (no required ports).
 *
 * This is a branded empty type that:
 * - IS assignable from empty object literals: \`const deps: EmptyDeps = {}\` ✓
 * - PREVENTS arbitrary key access: \`deps.nonExistent\` ✗ (type error)
 *
 * The brand uses \`?: never\` which means the property can only be satisfied
 * by omitting it entirely (since \`never\` has no values). This makes \`{}\`
 * assignable while preventing index access.
 */
export type EmptyDeps = {
	readonly __emptyDepsBrand?: never;
};
/**
 * Maps a union of Port types to an object type for dependency injection.
 *
 * When \`TRequires\` is \`never\` (no dependencies), returns \`EmptyDeps\` which
 * is a branded empty type that prevents arbitrary key access.
 *
 * When \`TRequires\` is a Port union, returns an object type with port names
 * as keys and service types as values.
 *
 * @example
 * \`\`\`typescript
 * // No dependencies - returns EmptyDeps (branded empty type)
 * type NoDeps = ResolvedDeps<never>;
 * const deps: NoDeps = {}; // ✓ OK
 * deps.anything; // ✗ Error: Property 'anything' does not exist
 *
 * // With dependencies - returns mapped object type
 * type WithDeps = ResolvedDeps<typeof LoggerPort | typeof DatabasePort>;
 * // { Logger: Logger; Database: Database }
 * \`\`\`
 */
export type ResolvedDeps<TRequires> = [
	TRequires
] extends [
	never
] ? EmptyDeps : {
	[TPort in TRequires as InferPortName<TPort> & string]: InferService<TPort>;
};
/**
 * A branded adapter type that captures the complete contract for a service implementation.
 *
 * ## Type Parameter Constraints
 *
 * | Parameter     | Constraint           | Purpose                                    |
 * |---------------|----------------------|--------------------------------------------|
 * | \`TProvides\`   | \`out\` (covariant)    | Port type this adapter implements          |
 * | \`TRequires\`   | invariant            | Union of required port types               |
 * | \`TLifetime\`   | \`extends Lifetime\`   | Declared lifetime (normalized for async) |
 * | \`TFactoryKind\`| \`extends FactoryKind\`| Must be "sync" | "async"                   |
 * | \`TClonable\`   | \`extends boolean\`    | Literal \`true\` or \`false\`                  |
 * | \`TRequiresTuple\`| derived            | Computed from TRequires for runtime array  |
 *
 * ## Variance Annotations
 *
 * The \`out\` modifier on \`TProvides\`, \`TFactoryKind\`, \`TClonable\`, and \`TRequiresTuple\`
 * marks them as covariant-only. This means:
 * - \`Adapter<DerivedPort, ...>\` is assignable to \`Adapter<BasePort, ...>\`
 * - Enables correct subtyping for adapters in collections
 *
 * \`TRequires\` is invariant (no modifier) because:
 * - The factory function both reads (contravariant) and returns (covariant) based on it
 * - Changing \`TRequires\` changes the factory signature bidirectionally
 *
 * ## Example
 *
 * \`\`\`typescript
 * // Full type signature of an adapter:
 * type LoggerAdapter = Adapter<
 *   typeof LoggerPort,  // TProvides: the port being implemented
 *   never,              // TRequires: no dependencies (never = empty union)
 *   "singleton",        // TLifetime: instance lifetime
 *   "sync",             // TFactoryKind: synchronous factory
 *   false,              // TClonable: not safe to shallow-clone
 *   readonly [],        // TRequiresTuple: empty tuple (computed from TRequires)
 *   never               // TError: no error channel (infallible factory)
 * >;
 * \`\`\`
 */
export type Adapter<out TProvides, TRequires, TLifetime extends string, // Widened to accept error message strings
out TFactoryKind extends FactoryKind = "sync", out TClonable extends boolean = false, out TRequiresTuple extends readonly unknown[] = [
	TRequires
] extends [
	never
] ? readonly [
] : readonly TRequires[], out TError = never> = {
	/**
	 * Brand property for nominal typing.
	 */
	readonly __adapterBrand?: [
		TProvides,
		TRequires,
		TLifetime,
		TFactoryKind,
		TClonable,
		TError
	];
	/**
	 * The port this adapter provides/implements.
	 */
	readonly provides: TProvides;
	/**
	 * The ports this adapter depends on.
	 */
	readonly requires: TRequiresTuple;
	/**
	 * The lifetime scope for this adapter's service instances.
	 *
	 * For sync factories, this is the declared lifetime.
	 * For async factories, this is either "singleton" (valid) or an error message
	 * string (invalid - when non-singleton lifetime was specified with async factory).
	 *
	 * The error string makes the adapter unusable with GraphBuilder, producing
	 * a compile-time error.
	 */
	readonly lifetime: TLifetime;
	/**
	 * The factory kind discriminator.
	 */
	readonly factoryKind: TFactoryKind;
	/**
	 * Factory function that creates the service instance.
	 */
	readonly factory: TFactoryKind extends "async" ? (deps: ResolvedDeps<TRequires>) => Promise<InferService<TProvides>> : (deps: ResolvedDeps<TRequires>) => InferService<TProvides>;
	/**
	 * Whether this adapter's service can be safely shallow-cloned.
	 *
	 * When \`true\`, the adapter's instances can be used with forked inheritance mode,
	 * which creates a shallow clone for child containers.
	 *
	 * When \`false\` (default), forked inheritance mode will fail at compile time,
	 * requiring the use of shared or isolated mode instead.
	 *
	 * @remarks
	 * Mark as clonable only for services that:
	 * - Have no resource handles (sockets, file handles, connections)
	 * - Have no external references that would become shared
	 * - Are value-like objects where shallow cloning produces valid instances
	 *
	 * @default false
	 */
	readonly clonable: TClonable;
	/**
	 * Optional finalizer function called during disposal.
	 */
	finalizer?(instance: InferService<TProvides>): void | Promise<void>;
};
/**
 * Event emitted by a library inspector.
 *
 * Wraps library-specific events with source identification for the
 * container's unified event stream.
 */
export interface LibraryEvent {
	/** Library name (matches LibraryInspector.name) */
	readonly source: string;
	/** Library-specific event type string */
	readonly type: string;
	/** Library-specific event payload */
	readonly payload: Readonly<Record<string, unknown>>;
	/** Event timestamp (Date.now()) */
	readonly timestamp: number;
}
/**
 * Listener callback for library inspector events.
 */
export type LibraryEventListener = (event: LibraryEvent) => void;
/**
 * Protocol that all library inspectors implement to participate
 * in the container's unified inspection system.
 *
 * Libraries implement this interface to make their domain-specific
 * inspection data discoverable and queryable through the container.
 */
export interface LibraryInspector {
	/** Unique library identifier. Must be lowercase kebab-case. */
	readonly name: string;
	/**
	 * Returns a frozen snapshot of the library's current state.
	 * The shape is library-specific but always a frozen record.
	 */
	getSnapshot(): Readonly<Record<string, unknown>>;
	/**
	 * Subscribe to library-specific events.
	 * Returns an unsubscribe function.
	 * Optional -- libraries without push-based events omit this.
	 */
	subscribe?(listener: LibraryEventListener): () => void;
	/**
	 * Dispose the library inspector and clean up resources.
	 * Optional -- called when the container disposes.
	 */
	dispose?(): void;
}
/**
 * Context variable types and factory functions.
 *
 * Context variables enable type-safe dependency injection scenarios
 * where configuration or runtime values need to be passed through
 * the dependency graph.
 *
 * @packageDocumentation
 */
/**
 * A type-safe context variable that can be used to store and retrieve
 * values in a dependency injection context.
 *
 * @typeParam T - The type of value stored in this context variable
 *
 * @example
 * \`\`\`typescript
 * const requestId = createContextVariable<string>('requestId');
 * const timeout = createContextVariable('timeout', 5000);
 * \`\`\`
 */
export interface ContextVariable<T> {
	/**
	 * Unique identifier for this context variable.
	 * Using a Symbol ensures variables with the same name don't collide.
	 */
	readonly id: symbol;
	/**
	 * Optional default value when the context variable is not set.
	 */
	readonly defaultValue?: T;
}
/**
 * Logger interface for structured logging.
 *
 * Provides level-based logging methods with support for annotations,
 * child loggers, and timed operations.
 */
export interface Logger {
	/**
	 * Log at trace level.
	 */
	trace(message: string, annotations?: Record<string, unknown>): void;
	/**
	 * Log at debug level.
	 */
	debug(message: string, annotations?: Record<string, unknown>): void;
	/**
	 * Log at info level.
	 */
	info(message: string, annotations?: Record<string, unknown>): void;
	/**
	 * Log at warn level.
	 */
	warn(message: string, annotations?: Record<string, unknown>): void;
	/**
	 * Log at error level.
	 */
	error(message: string, annotations?: Record<string, unknown>): void;
	error(message: string, error: Error, annotations?: Record<string, unknown>): void;
	/**
	 * Log at fatal level.
	 */
	fatal(message: string, annotations?: Record<string, unknown>): void;
	fatal(message: string, error: Error, annotations?: Record<string, unknown>): void;
	/**
	 * Create a child logger with additional context.
	 */
	child(context: Partial<LogContext>): Logger;
	/**
	 * Create a child logger with annotations.
	 */
	withAnnotations(annotations: Record<string, unknown>): Logger;
	/**
	 * Check if a level is enabled.
	 */
	isLevelEnabled(level: LogLevel): boolean;
	/**
	 * Get current log context.
	 */
	getContext(): LogContext;
	/**
	 * Time a synchronous operation and log duration.
	 */
	time<T>(name: string, fn: () => T): T;
	/**
	 * Time an asynchronous operation and log duration.
	 */
	timeAsync<T>(name: string, fn: () => Promise<T>): Promise<T>;
}
/**
 * Logger port for DI registration.
 */
export declare const LoggerPort: DirectedPort<"Logger", Logger, "outbound", "logger/logger">;
/**
 * Handler that processes log entries.
 */
export interface LogHandler {
	/**
	 * Handle a log entry.
	 *
	 * **Error contract:** Implementations SHOULD NOT throw from this method.
	 * If an error occurs during handling, implementations should either:
	 * 1. Swallow the error and increment an internal counter (preferred)
	 * 2. Throw the error (will be caught by logger and reported to stderr)
	 *
	 * Callers MUST wrap calls to handle() in try/catch.
	 */
	handle(entry: LogEntry): void;
	/**
	 * Flush pending log entries.
	 *
	 * **Contract:** Non-destructive and re-entrant. Handler remains
	 * usable after flush() returns.
	 */
	flush(): Promise<void>;
	/**
	 * Shutdown handler and release resources.
	 *
	 * **Contract:** Terminal operation. May reject subsequent handle() calls.
	 * Should flush before releasing resources.
	 */
	shutdown(): Promise<void>;
}
/**
 * Log handler port for DI registration.
 */
export declare const LogHandlerPort: DirectedPort<"LogHandler", LogHandler, "outbound", "logger/handler">;
/**
 * Formatter for log entries.
 */
export interface LogFormatter {
	/**
	 * Format a log entry to string.
	 */
	format(entry: LogEntry): string;
}
/**
 * Log formatter port for DI registration.
 */
export declare const LogFormatterPort: DirectedPort<"LogFormatter", LogFormatter, "outbound", "logger/formatter">;
/**
 * Built-in formatter types.
 */
export type FormatterType = "json" | "pretty" | "minimal";
/**
 * NoOpLoggerAdapter - Zero-overhead logger adapter for disabled logging.
 *
 * @packageDocumentation
 */
/**
 * Adapter that provides a zero-overhead NoOp logger implementation.
 *
 * All logging operations are no-ops, ensuring zero performance impact
 * when logging is disabled.
 */
export declare const NoOpLoggerAdapter: Adapter<DirectedPort<"Logger", Logger, "outbound", "logger/logger">, never, "singleton", "sync", false, readonly [
], never>;
/**
 * Singleton no-op logger that does nothing.
 * Zero runtime overhead when logging is disabled.
 */
export declare const NOOP_LOGGER: Logger;
/**
 * MemoryLoggerAdapter - DI adapter for the memory logger.
 *
 * Provides the MemoryLogger implementation as a LoggerPort adapter
 * for dependency injection. Useful for testing.
 *
 * @packageDocumentation
 */
/**
 * MemoryLoggerAdapter - DI adapter for the memory logger.
 *
 * Provides LoggerPort implementation with in-memory log collection.
 * Uses transient lifetime for test isolation.
 */
export declare const MemoryLoggerAdapter: Adapter<DirectedPort<"Logger", Logger, "outbound", "logger/logger">, never, "transient", "sync", false, readonly [
], never>;
/**
 * Extended Logger interface with testing methods.
 */
export interface MemoryLogger extends Logger {
	/** Get all collected log entries. */
	getEntries(): ReadonlyArray<LogEntry>;
	/** Get entries filtered by level. */
	getEntriesByLevel(level: LogLevel): ReadonlyArray<LogEntry>;
	/** Clear all collected entries. */
	clear(): void;
	/** Find an entry matching a predicate. */
	findEntry(predicate: (entry: LogEntry) => boolean): LogEntry | undefined;
}
/**
 * Creates a new MemoryLogger instance.
 *
 * Convenience factory for creating memory loggers in tests.
 *
 * @param minLevel - Minimum log level (default: "trace")
 * @returns A new MemoryLogger instance
 */
export declare function createMemoryLogger(minLevel?: LogLevel, options?: {
	maxEntries?: number;
}): MemoryLogger;
/**
 * ConsoleLoggerAdapter - DI adapter for the console logger.
 *
 * @packageDocumentation
 */
/**
 * ConsoleLoggerAdapter - DI adapter for the console logger.
 *
 * Provides LoggerPort implementation with console output for development.
 */
export declare const ConsoleLoggerAdapter: Adapter<DirectedPort<"Logger", Logger, "outbound", "logger/logger">, never, "singleton", "sync", false, readonly [
], never>;
/**
 * Console logger options.
 */
export interface ConsoleLoggerOptions {
	readonly level?: LogLevel;
	readonly formatter?: LogFormatter;
	readonly formatterType?: "json" | "pretty" | "minimal";
}
/**
 * Creates a new ConsoleLogger instance.
 *
 * @param options - Console logger configuration
 * @returns A new ConsoleLogger instance
 */
export declare function createConsoleLogger(options?: ConsoleLoggerOptions): Logger;
/**
 * ScopedLoggerAdapter - DI adapter for handler-backed scoped logger.
 *
 * Provides a Logger implementation that delegates to a LogHandler,
 * with scoped lifetime for request-level isolation.
 *
 * @packageDocumentation
 */
/**
 * ScopedLoggerAdapter - DI adapter for handler-backed scoped logger.
 *
 * Provides LoggerPort implementation backed by a LogHandler.
 * Uses scoped lifetime for request-level isolation.
 */
export declare const ScopedLoggerAdapter: Adapter<DirectedPort<"Logger", Logger, "outbound", "logger/logger">, DirectedPort<"LogHandler", LogHandler, "outbound", "logger/handler">, "scoped", "sync", false, readonly [
	DirectedPort<"LogHandler", LogHandler, "outbound", "logger/handler">
], never>;
/**
 * Creates a new handler-backed Logger instance.
 *
 * The logger delegates all log entry processing to the provided LogHandler,
 * enabling flexible routing to any backend.
 *
 * @param handler - The LogHandler to delegate entries to
 * @param options - Optional configuration for level, context, and annotations
 * @returns A new Logger instance backed by the handler
 */
export declare function createHandlerLogger(handler: LogHandler, options?: {
	level?: LogLevel;
	context?: LogContext;
	annotations?: Record<string, unknown>;
}): Logger;
/**
 * Context variable for log context propagation.
 *
 * Carries the current log context (correlationId, requestId, etc.)
 * through DI resolution.
 */
export declare const LogContextVar: ContextVariable<LogContext>;
/**
 * Context variable for log annotations propagation.
 *
 * Carries persistent annotations that should be included
 * in all log entries within a scope.
 */
export declare const LogAnnotationsVar: ContextVariable<Record<string, unknown>>;
/**
 * Get a built-in formatter by type name.
 *
 * @param type - The formatter type
 * @returns The corresponding LogFormatter
 */
export declare function getFormatter(type: FormatterType): LogFormatter;
/**
 * Standard header names for context extraction.
 */
export declare const CORRELATION_ID_HEADER = "x-correlation-id";
export declare const REQUEST_ID_HEADER = "x-request-id";
/**
 * Merge base context with override values.
 *
 * @param base - The base log context
 * @param override - Values to merge into the base
 * @returns A new merged LogContext
 */
export declare function mergeContext(base: LogContext, override: Partial<LogContext>): LogContext;
/**
 * Extract log context from request headers.
 *
 * Header values are validated and sanitized:
 * - Maximum length of 256 characters
 * - Unsafe characters replaced with underscores
 *
 * @param headers - Request headers
 * @returns Extracted partial log context
 */
export declare function extractContextFromHeaders(headers: Record<string, string | undefined>): Partial<LogContext>;
/**
 * Stderr fallback utility for GxP compliance.
 *
 * Provides a safe way to output diagnostic messages when the
 * normal logging pipeline fails. Falls back through:
 * process.stderr -> console.error -> silent
 *
 * @packageDocumentation
 */
/**
 * Returns a function that writes to stderr, or undefined if unavailable.
 *
 * Falls back through: process.stderr.write -> console.error -> undefined
 */
export declare function getStderr(): ((message: string) => void) | undefined;
/**
 * Configuration for redaction behavior.
 */
export interface RedactionConfig {
	readonly paths: ReadonlyArray<string>;
	readonly censor?: string | ((value: unknown) => unknown);
	/** Regular expression patterns to redact within log messages. */
	readonly messagePatterns?: ReadonlyArray<RegExp>;
}
/**
 * Create a Logger wrapper that redacts sensitive fields.
 *
 * @param logger - The logger to wrap
 * @param config - Redaction configuration
 * @returns A new Logger with redaction applied
 */
export declare function withRedaction(logger: Logger, config: RedactionConfig): Logger;
/**
 * Configuration for sampling behavior.
 */
export interface SamplingConfig {
	readonly rate: number;
	readonly perLevel?: Partial<Record<LogLevel, number>>;
	readonly alwaysLogErrors?: boolean;
	/** Seedable random function for deterministic testing. Defaults to Math.random. */
	readonly randomFn?: () => number;
	/** Called when an entry is dropped by sampling. */
	readonly onDrop?: (level: LogLevel, count: number) => void;
}
/**
 * Create a Logger wrapper that probabilistically samples log entries.
 *
 * @param logger - The logger to wrap
 * @param config - Sampling configuration
 * @returns A new Logger with sampling applied
 */
export declare function withSampling(logger: Logger, config: SamplingConfig): Logger;
/**
 * Configuration for rate limiting behavior.
 */
export interface RateLimitConfig {
	readonly maxEntries: number;
	readonly windowMs: number;
	readonly perLevel?: Partial<Record<LogLevel, number>>;
	readonly strategy?: "drop" | "sample";
	/** Seedable random function for deterministic testing. Defaults to Math.random. */
	readonly randomFn?: () => number;
	/** Called when an entry is dropped by rate limiting. */
	readonly onDrop?: (count: number, windowMs: number) => void;
}
/**
 * Create a Logger wrapper that enforces rate limits.
 *
 * @param logger - The logger to wrap
 * @param config - Rate limit configuration
 * @returns A new Logger with rate limiting applied
 */
export declare function withRateLimit(logger: Logger, config: RateLimitConfig): Logger;
/**
 * Log injection prevention utilities.
 *
 * Sanitizes log messages to prevent ANSI escape injection,
 * newline injection, and control character injection.
 *
 * @packageDocumentation
 */
/**
 * Sanitizes a log message to prevent log injection attacks.
 *
 * Removes ANSI escape sequences, escapes newlines, and strips
 * control characters that could be used for log forging.
 *
 * @param message - The raw log message
 * @returns The sanitized message safe for log output
 */
export declare function sanitizeMessage(message: string): string;
/**
 * Sanitizes a string value within annotations.
 *
 * Applies the same sanitization as messages to prevent
 * injection through annotation values.
 *
 * @param value - The string value to sanitize
 * @returns The sanitized string
 */
export declare function sanitizeStringValue(value: string): string;
/**
 * Annotation validation utilities for GxP compliance.
 *
 * Validates and sanitizes log annotation values to ensure they are
 * serializable, non-circular, and within size limits.
 *
 * @packageDocumentation
 */
/**
 * Configuration for annotation validation.
 */
export interface ValidationConfig {
	/** Maximum object nesting depth. Defaults to 10. */
	readonly maxDepth: number;
	/** Maximum total keys across all levels. Defaults to 100. */
	readonly maxKeys: number;
}
/**
 * Sanitizes annotation values to ensure they are safe for serialization.
 *
 * Removes:
 * - Functions (with stderr warning)
 * - Symbols (with stderr warning)
 * - BigInt values (with stderr warning)
 * - Circular references
 *
 * Enforces:
 * - Max nesting depth
 * - Max total key count
 *
 * Converts:
 * - undefined -> null
 *
 * @param annotations - The raw annotation record
 * @param config - Optional validation configuration
 * @returns A sanitized copy of the annotations
 */
export declare function sanitizeAnnotations(annotations: Record<string, unknown>, config?: ValidationConfig): Record<string, unknown>;
/**
 * Monotonic sequence number generator for log entries.
 *
 * Provides globally unique, strictly increasing sequence numbers
 * for ordering log entries within a process. Essential for GxP
 * audit trail completeness where timestamp alone is insufficient.
 *
 * @packageDocumentation
 */
/**
 * Returns the next monotonic sequence number.
 *
 * Thread-safe in single-threaded JavaScript runtimes. Each call
 * returns a strictly increasing integer starting from 1.
 *
 * @returns The next sequence number
 */
export declare function nextSequence(): number;
/**
 * Resets the sequence counter to 0.
 *
 * Intended for test teardown only. Must not be called in production.
 *
 * @internal
 */
export declare function resetSequence(): void;
/**
 * Configuration for integrity hashing.
 */
export interface IntegrityConfig {
	readonly enabled: boolean;
}
/**
 * Integrity metadata attached to a log entry.
 */
export interface IntegrityInfo {
	readonly hash: string;
	readonly previousHash: string;
}
/**
 * Computes a hash for a log entry based on its canonical fields
 * and the previous entry's hash, forming a hash chain.
 *
 * @param entry - Canonical fields of the entry
 * @param previousHash - Hash of the previous entry (or "0" for first)
 * @returns The computed hash string
 */
export declare function computeEntryHash(entry: {
	level: string;
	message: string;
	timestamp: number;
	sequence: number;
}, previousHash: string): string;
/**
 * Creates a Logger wrapper that computes and attaches integrity hashes
 * to log entry annotations.
 *
 * Each entry's hash is computed from its canonical fields and the
 * previous entry's hash, forming a chain. Any gap or mutation
 * breaks the chain, enabling detection.
 *
 * @param logger - The logger to wrap
 * @param _config - Integrity configuration (reserved for future options)
 * @returns A Logger that attaches integrity metadata to annotations
 */
export declare function withIntegrity(logger: Logger, _config?: IntegrityConfig): Logger;
/**
 * Options for automatic container resolution logging.
 */
export interface AutoLogOptions {
	/** Log level for successful resolutions (default: "debug"). */
	readonly resolutionLevel?: LogLevel;
	/** Log level for resolution errors (default: "error"). */
	readonly errorLevel?: LogLevel;
	/** Filter which ports to log. Returns true to include (default: skips Logger and LogHandler). */
	readonly portFilter?: (portName: string) => boolean;
	/** Whether to include timing information for resolutions. */
	readonly includeTiming?: boolean;
	/** Minimum resolution duration in ms before logging (only when includeTiming is true). */
	readonly minDurationMs?: number;
	/** Whether to log scope lifecycle events (creation/disposal). */
	readonly logScopeLifecycle?: boolean;
}
/**
 * Hook object for container resolution lifecycle events.
 */
export interface LoggingHook {
	readonly beforeResolve?: (portName: string) => void;
	readonly afterResolve?: (portName: string, instance: unknown) => void;
	readonly onError?: (portName: string, error: Error) => void;
}
/**
 * Minimal container interface for instrumentation.
 *
 * Uses structural typing so the logger package does not depend on @hex-di/runtime.
 */
export interface InstrumentableContainer {
	readonly resolve: (port: unknown) => unknown;
	readonly onResolve?: (hook: (portName: string, instance: unknown) => void) => () => void;
	readonly onResolveError?: (hook: (portName: string, error: Error) => void) => () => void;
	readonly onScopeCreate?: (hook: (scopeId: string) => void) => () => void;
	readonly onScopeDispose?: (hook: (scopeId: string, resolvedCount: number) => void) => () => void;
}
/**
 * Instruments a container to automatically log resolution events.
 *
 * The logger instance is captured at instrumentation time, not resolved per-event.
 * Returns a cleanup function that removes all hooks when called.
 *
 * @param container - Container with hook support
 * @param logger - Logger instance to use for logging
 * @param options - Configuration options
 * @returns A cleanup function that removes all installed hooks
 */
export declare function instrumentContainer(container: InstrumentableContainer, logger: Logger, options?: AutoLogOptions): () => void;
/**
 * Creates a logging hook that logs container resolution events.
 *
 * The hook respects the provided options for filtering and log levels.
 * Includes a reentrance guard to prevent infinite loops when the logger
 * itself triggers a resolution.
 *
 * @param logger - Logger instance to use for logging
 * @param options - Configuration options
 * @returns A hook object with lifecycle methods
 */
export declare function createLoggingHook(logger: Logger, options?: AutoLogOptions): LoggingHook;
/**
 * Minimal Hono context type for structural compatibility.
 * Avoids importing from hono directly since it's an optional dependency.
 */
export interface HonoContext {
	readonly req: {
		readonly method: string;
		readonly path: string;
		header(name: string): string | undefined;
		readonly url: string;
	};
	readonly res: {
		readonly status: number;
	};
	set(key: string, value: unknown): void;
	get(key: string): unknown;
}
/**
 * Hono next function type.
 */
export type NextFunction = () => Promise<void>;
/**
 * Hono middleware handler type.
 */
export type MiddlewareHandler = (c: HonoContext, next: NextFunction) => Promise<void>;
/**
 * Configuration options for the logging middleware.
 */
export interface HonoLoggingOptions {
	/** The logger instance to use. */
	readonly logger: Logger;
	/** Default log level for successful requests. Defaults to "info". */
	readonly level?: LogLevel;
	/** Whether to include request body in logs. */
	readonly includeRequestBody?: boolean;
	/** Whether to include response body in logs. */
	readonly includeResponseBody?: boolean;
	/** Header names to redact from logs. */
	readonly redactHeaders?: ReadonlyArray<string>;
	/** URL paths to redact from logs. */
	readonly redactPaths?: ReadonlyArray<string>;
	/** URL paths to skip logging entirely. */
	readonly skipPaths?: ReadonlyArray<string>;
}
/**
 * Creates a Hono middleware that provides request-scoped structured logging.
 *
 * The middleware:
 * 1. Extracts correlation/request IDs from headers
 * 2. Creates a child logger with request context
 * 3. Makes the child logger available via \`c.get("logger")\`
 * 4. Logs request start and completion with timing
 *
 * @param options - Middleware configuration
 * @returns A Hono middleware handler
 */
export declare function loggingMiddleware(options: HonoLoggingOptions): MiddlewareHandler;
/**
 * Span information for log entry correlation.
 */
export interface SpanInfo {
	readonly traceId: string;
	readonly spanId: string;
}
/**
 * A function that retrieves active span information.
 * Returns undefined if no span is active or tracing is not available.
 */
export type SpanProvider = () => ReadonlyArray<SpanInfo> | undefined;
/**
 * Create a span provider that attempts to read the active tracing context.
 *
 * Since @hex-di/tracing cannot be dynamically imported at runtime easily,
 * this returns a no-op provider by default. Users should wire up their own
 * SpanProvider if tracing context is available.
 *
 * @returns A SpanProvider (defaults to no-op)
 */
export declare function createSpanProvider(): SpanProvider;
/**
 * Create a Logger wrapper that injects active trace spans into log entries.
 *
 * When a span is active (the provider returns span info), the traceId and spanId
 * are injected into the log annotations. When no span is active, logging
 * proceeds without modification.
 *
 * @param logger - The logger to wrap
 * @param spanProvider - Function to get active spans (defaults to auto-detect via createSpanProvider)
 * @returns Logger that includes span info in entries
 */
export declare function withSpanInjection(logger: Logger, spanProvider?: SpanProvider): Logger;
/**
 * Complete snapshot of the logging system state.
 */
export interface LoggingSnapshot {
	readonly timestamp: number;
	readonly totalEntries: number;
	readonly entriesByLevel: Readonly<Record<LogLevel, number>>;
	readonly errorRate: number;
	readonly handlers: readonly HandlerInfo[];
	readonly samplingActive: boolean;
	readonly redactionActive: boolean;
	readonly contextDepth: number;
}
/**
 * Metadata about a registered log handler.
 */
export interface HandlerInfo {
	readonly type: string;
	readonly name: string;
	readonly active: boolean;
	readonly entryCount: number;
	readonly formatterType?: string;
	readonly minLevel?: LogLevel;
}
/**
 * Statistics about sampling behavior.
 */
export interface SamplingStatistics {
	readonly active: boolean;
	readonly byLevel: Readonly<Record<LogLevel, {
		readonly received: number;
		readonly accepted: number;
		readonly dropped: number;
	}>>;
	readonly acceptanceRate: number;
}
/**
 * Statistics about redaction behavior.
 */
export interface RedactionStatistics {
	readonly active: boolean;
	readonly totalRedactions: number;
	readonly fieldFrequency: Readonly<Record<string, number>>;
	readonly patternMatches: number;
}
/**
 * Statistics about context variable usage.
 */
export interface ContextUsageStatistics {
	readonly activeVariables: number;
	readonly fieldFrequency: Readonly<Record<string, number>>;
	readonly maxChildDepth: number;
}
/**
 * Options for time-windowed calculations.
 */
export interface TimeWindowOptions {
	readonly windowMs?: number;
}
/**
 * Options for querying recent log entries.
 */
export interface RecentEntriesOptions {
	readonly limit?: number;
	readonly level?: LogLevel;
	readonly since?: number;
}
/**
 * Events emitted by the logger inspector.
 *
 * Discriminated union on the \`type\` field.
 */
export type LoggerInspectorEvent = {
	readonly type: "entry-logged";
	readonly level: LogLevel;
	readonly message: string;
	readonly timestamp: number;
} | {
	readonly type: "error-rate-threshold";
	readonly errorRate: number;
	readonly threshold: number;
	readonly windowMs: number;
} | {
	readonly type: "handler-error";
	readonly handlerName: string;
	readonly error: Error;
} | {
	readonly type: "sampling-dropped";
	readonly level: LogLevel;
	readonly dropCount: number;
} | {
	readonly type: "redaction-applied";
	readonly fieldPath: string;
	readonly count: number;
} | {
	readonly type: "handler-added";
	readonly handler: HandlerInfo;
} | {
	readonly type: "handler-removed";
	readonly handlerName: string;
} | {
	readonly type: "snapshot-changed";
} | {
	readonly type: "entries-dropped";
	readonly count: number;
	readonly reason: "rate-limit" | "console-unavailable" | "handler-error";
} | {
	readonly type: "tracing-context-missing";
	readonly field: "correlationId" | "traceId" | "spanId";
} | {
	readonly type: "validation-warning";
	readonly field: string;
	readonly reason: string;
};
/**
 * Listener callback for logger inspector events.
 */
export type LoggerInspectorListener = (event: LoggerInspectorEvent) => void;
/**
 * Logger inspector interface for observing logging system state.
 */
export interface LoggerInspector {
	readonly libraryName: "logging";
	getSnapshot(): LoggingSnapshot;
	getEntryCounts(): Readonly<Record<LogLevel, number>>;
	getErrorRate(options?: TimeWindowOptions): number;
	getHandlerInfo(): readonly HandlerInfo[];
	getSamplingStatistics(): SamplingStatistics;
	getRedactionStatistics(): RedactionStatistics;
	getRecentEntries(options?: RecentEntriesOptions): readonly LogEntry[];
	getContextUsage(): ContextUsageStatistics;
	subscribe(listener: LoggerInspectorListener): () => void;
}
/**
 * Options for creating a LoggerInspector adapter.
 */
export interface CreateLoggerInspectorOptions {
	readonly handlers?: readonly HandlerInfo[];
	readonly samplingConfig?: SamplingConfig;
	readonly redactionConfig?: RedactionConfig;
	readonly errorRateThreshold?: number;
	readonly errorRateWindowMs?: number;
	readonly recentEntriesCapacity?: number;
	readonly contextDepth?: number;
}
/**
 * Internal inspector adapter with instrumentation hooks.
 */
export interface LoggerInspectorAdapter extends LoggerInspector {
	/**
	 * Called by the logging pipeline to record an entry.
	 */
	recordEntry(entry: LogEntry): void;
	/**
	 * Record that a sampling decision dropped an entry.
	 */
	recordSamplingDrop(level: LogLevel): void;
	/**
	 * Record that a redaction was applied.
	 */
	recordRedaction(fieldPath: string): void;
	/**
	 * Record context field usage from a log entry.
	 */
	recordContextUsage(fields: readonly string[], childDepth: number): void;
}
/**
 * Creates a LoggerInspector adapter with instrumentation hooks.
 */
export declare function createLoggerInspectorAdapter(options?: CreateLoggerInspectorOptions): LoggerInspectorAdapter;
/**
 * Port for the LoggerInspector service.
 */
export declare const LoggerInspectorPort: DirectedPort<"LoggerInspector", LoggerInspector, "outbound", "logger/inspector">;
/**
 * Port for the Logger library inspector bridge.
 */
export declare const LoggerLibraryInspectorPort: DirectedPort<"LoggerLibraryInspector", LibraryInspector, "outbound", "library-inspector">;
/**
 * Creates a LibraryInspector that bridges the LoggerInspector
 * into the container's unified inspection protocol.
 *
 * @param loggerInspector - The LoggerInspector instance to bridge
 * @returns A LibraryInspector compatible with the container registry
 */
export declare function createLoggerLibraryInspector(loggerInspector: LoggerInspector): LibraryInspector;
/**
 * Pre-built frozen adapter for LoggerLibraryInspectorPort.
 *
 * Depends on LoggerInspectorPort and produces a LibraryInspector bridge
 * via createLoggerLibraryInspector. Because LoggerLibraryInspectorPort
 * has \`category: "library-inspector"\`, the container's afterResolve hook
 * will auto-register it with the unified inspection protocol.
 */
export declare const LoggerLibraryInspectorAdapter: Adapter<typeof LoggerLibraryInspectorPort, typeof LoggerInspectorPort, "singleton", "sync", false, readonly [
	typeof LoggerInspectorPort
]>;
/**
 * Creates a lazy logger inspector that initializes on first access.
 *
 * @param options - Options forwarded to createLoggerInspectorAdapter
 * @returns A factory function that returns the inspector, creating it if needed
 */
export declare function createLazyLoggerInspector(options?: CreateLoggerInspectorOptions): () => LoggerInspectorAdapter;
/**
 * Matcher for finding log entries in test assertions.
 */
export interface LogEntryMatcher {
	readonly level?: LogLevel;
	readonly message?: string | RegExp;
	readonly annotations?: Record<string, unknown>;
	readonly context?: Partial<LogContext>;
	readonly hasError?: boolean;
}
/**
 * Assert that a log entry matching the given criteria exists.
 *
 * @param entries - Array of log entries to search
 * @param matcher - Criteria to match against
 * @returns The matching log entry
 * @throws Error if no matching entry is found
 */
export declare function assertLogEntry(entries: ReadonlyArray<LogEntry>, matcher: LogEntryMatcher): LogEntry;

export {};
}`;
