// Auto-generated by scripts/bundle-playground-types.ts
// Package: @hex-di/saga
export const dts = `declare module "@hex-di/saga" {
/**
 * A branded port type that serves as a compile-time contract for a service interface.
 *
 * The Port type uses TypeScript's structural typing with a branded property
 * to achieve nominal typing. Two ports are only compatible if they have:
 * 1. The same service interface type \`T\`
 * 2. The same port name \`TName\`
 *
 * @typeParam TName - The literal string type for the port name (defaults to \`string\`)
 * @typeParam T - The service interface type (phantom type - exists only at compile time)
 *
 * @remarks
 * - The \`__brand\` property carries both the service type and name in a tuple
 * - The \`__portName\` property exposes the name for debugging and error messages
 * - Both properties are readonly to prevent modification
 * - The brand symbol value is \`undefined\` at runtime (zero overhead)
 *
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link InferService} - Utility to extract the service type from a port
 * @see {@link InferPortName} - Utility to extract the name type from a port
 *
 * @example Direct type usage
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * // Create typed port tokens
 * type ConsoleLoggerPort = Port<'ConsoleLogger', Logger>;
 * type FileLoggerPort = Port<'FileLogger', Logger>;
 *
 * // These are type-incompatible despite same interface
 * declare const consolePort: ConsoleLoggerPort;
 * declare const filePort: FileLoggerPort;
 * // consolePort = filePort; // Type error!
 * \`\`\`
 *
 * @example With createPort (recommended)
 * \`\`\`typescript
 * // Use createPort for value + type duality
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerPortType = typeof LoggerPort;
 * \`\`\`
 */
export type Port<TName extends string, T> = {
	/**
	 * Brand property for nominal typing.
	 * Contains a tuple of [PortName, ServiceType] at the type level.
	 * Value is undefined at runtime.
	 */
	readonly __brand: [
		TName,
		T
	];
	/**
	 * The port name, exposed for debugging and error messages.
	 */
	readonly __portName: TName;
};
/**
 * Error type returned when type inference utilities receive a non-Port type.
 *
 * This branded error provides actionable guidance in IDE tooltips when users
 * accidentally pass incorrect types to InferService or InferPortName.
 *
 * @typeParam T - The type that was passed (preserved for debugging)
 *
 * @remarks
 * Instead of returning opaque \`never\`, this error type provides:
 * - Clear error message explaining what was expected
 * - The actual type that was received (for debugging)
 * - A hint about common mistakes (e.g., forgetting \`typeof\`)
 *
 * @example IDE tooltip when misused
 * \`\`\`typescript
 * type Result = InferService<string>;
 * // Hovering shows:
 * // {
 * //   __errorBrand: "NotAPortError";
 * //   __message: "Expected a Port type created with createPort() or port()";
 * //   __received: string;
 * //   __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
 * // }
 * \`\`\`
 */
export type NotAPortError<T> = {
	readonly __errorBrand: "NotAPortError";
	readonly __message: "Expected a Port type created with createPort() or port()";
	readonly __received: T;
	readonly __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
};
/**
 * Extracts the service interface type from a Port type.
 *
 * This utility type uses conditional type inference to extract the phantom
 * type parameter \`T\` from a \`Port<TName, T>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the service from
 * @returns The service interface type \`T\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferPortName} - Companion utility to extract the port name
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerService = InferService<typeof LoggerPort>;
 * // LoggerService = Logger
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferService<string>;
 * // Invalid = NotAPortError<string>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferService<P> = P extends Port<infer _TName, infer T> ? T : NotAPortError<P>;
/**
 * Extracts the port name literal type from a Port type.
 *
 * This utility type uses conditional type inference to extract the name
 * type parameter \`TName\` from a \`Port<TName, T>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the name from
 * @returns The port name literal type \`TName\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferService} - Companion utility to extract the service type
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type PortName = InferPortName<typeof LoggerPort>;
 * // PortName = 'Logger'
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferPortName<number>;
 * // Invalid = NotAPortError<number>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferPortName<P> = P extends Port<infer TName, infer _T> ? TName : NotAPortError<P>;
declare const __metadataKey: unique symbol;
/**
 * Discriminator for hexagonal architecture port types.
 *
 * - \`'inbound'\` - Driving ports (use cases, primary adapters)
 * - \`'outbound'\` - Driven ports (infrastructure, secondary adapters)
 *
 * @see {@link DirectedPort} - The port type that carries direction
 * @see {@link createInboundPort} - Factory for inbound ports
 * @see {@link createOutboundPort} - Factory for outbound ports
 */
export type PortDirection = "inbound" | "outbound";
/**
 * Optional metadata for documenting ports.
 *
 * Metadata provides human-readable documentation that can be used for:
 * - IDE tooltips and documentation
 * - Dependency graph visualization
 * - API documentation generation
 *
 * All properties are optional and readonly.
 *
 * @example
 * \`\`\`typescript
 * const UserServicePort = createInboundPort<'UserService', UserService>({
 *   name: 'UserService',
 *   description: 'Handles user CRUD operations',
 *   category: 'domain',
 *   tags: ['user', 'crud', 'core'],
 * });
 * \`\`\`
 */
export interface PortMetadata {
	/** Human-readable description of the port's purpose */
	readonly description?: string;
	/** Categorical grouping for organization */
	readonly category?: string;
	/** Searchable tags for filtering and discovery */
	readonly tags?: readonly string[];
}
/**
 * A port with hexagonal architecture direction and optional metadata.
 *
 * DirectedPort extends the base Port type with additional type-level branding:
 * - \`TDirection\` - Whether this is an inbound (driving) or outbound (driven) port
 * - Metadata association for documentation purposes
 *
 * DirectedPorts are structurally compatible with base Ports, enabling gradual
 * adoption without breaking existing code.
 *
 * @typeParam TName - The literal string type for the port name
 * @typeParam TService - The service interface type (phantom type)
 * @typeParam TDirection - 'inbound' or 'outbound'
 *
 * @see {@link InboundPort} - Convenience alias for inbound directed ports
 * @see {@link OutboundPort} - Convenience alias for outbound directed ports
 * @see {@link createInboundPort} - Factory for creating inbound ports
 * @see {@link createOutboundPort} - Factory for creating outbound ports
 *
 * @example
 * \`\`\`typescript
 * // DirectedPort is assignable to Port (backward compatible)
 * const port: DirectedPort<'Logger', Logger, 'inbound'> = createInboundPort({
 *   name: 'Logger',
 * });
 * const basePort: Port<'Logger', Logger> = port; // OK
 * \`\`\`
 */
export type DirectedPort<TName extends string, TService, TDirection extends PortDirection, TCategory extends string = string> = Port<TName, TService> & {
	readonly __directionBrand: TDirection;
	readonly __metadataKey: PortMetadata;
	readonly __categoryBrand: TCategory;
};
/**
 * Discriminator for sync vs async factory functions.
 */
export type FactoryKind = "sync" | "async";
/**
 * Type representing empty dependencies (no required ports).
 *
 * This is a branded empty type that:
 * - IS assignable from empty object literals: \`const deps: EmptyDeps = {}\` ✓
 * - PREVENTS arbitrary key access: \`deps.nonExistent\` ✗ (type error)
 *
 * The brand uses \`?: never\` which means the property can only be satisfied
 * by omitting it entirely (since \`never\` has no values). This makes \`{}\`
 * assignable while preventing index access.
 */
export type EmptyDeps = {
	readonly __emptyDepsBrand?: never;
};
/**
 * Maps a union of Port types to an object type for dependency injection.
 *
 * When \`TRequires\` is \`never\` (no dependencies), returns \`EmptyDeps\` which
 * is a branded empty type that prevents arbitrary key access.
 *
 * When \`TRequires\` is a Port union, returns an object type with port names
 * as keys and service types as values.
 *
 * @example
 * \`\`\`typescript
 * // No dependencies - returns EmptyDeps (branded empty type)
 * type NoDeps = ResolvedDeps<never>;
 * const deps: NoDeps = {}; // ✓ OK
 * deps.anything; // ✗ Error: Property 'anything' does not exist
 *
 * // With dependencies - returns mapped object type
 * type WithDeps = ResolvedDeps<typeof LoggerPort | typeof DatabasePort>;
 * // { Logger: Logger; Database: Database }
 * \`\`\`
 */
export type ResolvedDeps<TRequires> = [
	TRequires
] extends [
	never
] ? EmptyDeps : {
	[TPort in TRequires as InferPortName<TPort> & string]: InferService<TPort>;
};
/**
 * A branded adapter type that captures the complete contract for a service implementation.
 *
 * ## Type Parameter Constraints
 *
 * | Parameter     | Constraint           | Purpose                                    |
 * |---------------|----------------------|--------------------------------------------|
 * | \`TProvides\`   | \`out\` (covariant)    | Port type this adapter implements          |
 * | \`TRequires\`   | invariant            | Union of required port types               |
 * | \`TLifetime\`   | \`extends Lifetime\`   | Declared lifetime (normalized for async) |
 * | \`TFactoryKind\`| \`extends FactoryKind\`| Must be "sync" | "async"                   |
 * | \`TClonable\`   | \`extends boolean\`    | Literal \`true\` or \`false\`                  |
 * | \`TRequiresTuple\`| derived            | Computed from TRequires for runtime array  |
 *
 * ## Variance Annotations
 *
 * The \`out\` modifier on \`TProvides\`, \`TFactoryKind\`, \`TClonable\`, and \`TRequiresTuple\`
 * marks them as covariant-only. This means:
 * - \`Adapter<DerivedPort, ...>\` is assignable to \`Adapter<BasePort, ...>\`
 * - Enables correct subtyping for adapters in collections
 *
 * \`TRequires\` is invariant (no modifier) because:
 * - The factory function both reads (contravariant) and returns (covariant) based on it
 * - Changing \`TRequires\` changes the factory signature bidirectionally
 *
 * ## Example
 *
 * \`\`\`typescript
 * // Full type signature of an adapter:
 * type LoggerAdapter = Adapter<
 *   typeof LoggerPort,  // TProvides: the port being implemented
 *   never,              // TRequires: no dependencies (never = empty union)
 *   "singleton",        // TLifetime: instance lifetime
 *   "sync",             // TFactoryKind: synchronous factory
 *   false,              // TClonable: not safe to shallow-clone
 *   readonly [],        // TRequiresTuple: empty tuple (computed from TRequires)
 *   never               // TError: no error channel (infallible factory)
 * >;
 * \`\`\`
 */
export type Adapter<out TProvides, TRequires, TLifetime extends string, // Widened to accept error message strings
out TFactoryKind extends FactoryKind = "sync", out TClonable extends boolean = false, out TRequiresTuple extends readonly unknown[] = [
	TRequires
] extends [
	never
] ? readonly [
] : readonly TRequires[], out TError = never> = {
	/**
	 * Brand property for nominal typing.
	 */
	readonly __adapterBrand?: [
		TProvides,
		TRequires,
		TLifetime,
		TFactoryKind,
		TClonable,
		TError
	];
	/**
	 * The port this adapter provides/implements.
	 */
	readonly provides: TProvides;
	/**
	 * The ports this adapter depends on.
	 */
	readonly requires: TRequiresTuple;
	/**
	 * The lifetime scope for this adapter's service instances.
	 *
	 * For sync factories, this is the declared lifetime.
	 * For async factories, this is either "singleton" (valid) or an error message
	 * string (invalid - when non-singleton lifetime was specified with async factory).
	 *
	 * The error string makes the adapter unusable with GraphBuilder, producing
	 * a compile-time error.
	 */
	readonly lifetime: TLifetime;
	/**
	 * The factory kind discriminator.
	 */
	readonly factoryKind: TFactoryKind;
	/**
	 * Factory function that creates the service instance.
	 */
	readonly factory: TFactoryKind extends "async" ? (deps: ResolvedDeps<TRequires>) => Promise<InferService<TProvides>> : (deps: ResolvedDeps<TRequires>) => InferService<TProvides>;
	/**
	 * Whether this adapter's service can be safely shallow-cloned.
	 *
	 * When \`true\`, the adapter's instances can be used with forked inheritance mode,
	 * which creates a shallow clone for child containers.
	 *
	 * When \`false\` (default), forked inheritance mode will fail at compile time,
	 * requiring the use of shared or isolated mode instead.
	 *
	 * @remarks
	 * Mark as clonable only for services that:
	 * - Have no resource handles (sockets, file handles, connections)
	 * - Have no external references that would become shared
	 * - Are value-like objects where shallow cloning produces valid instances
	 *
	 * @default false
	 */
	readonly clonable: TClonable;
	/**
	 * Optional finalizer function called during disposal.
	 */
	finalizer?(instance: InferService<TProvides>): void | Promise<void>;
};
/**
 * Event emitted by a library inspector.
 *
 * Wraps library-specific events with source identification for the
 * container's unified event stream.
 */
export interface LibraryEvent {
	/** Library name (matches LibraryInspector.name) */
	readonly source: string;
	/** Library-specific event type string */
	readonly type: string;
	/** Library-specific event payload */
	readonly payload: Readonly<Record<string, unknown>>;
	/** Event timestamp (Date.now()) */
	readonly timestamp: number;
}
/**
 * Listener callback for library inspector events.
 */
export type LibraryEventListener = (event: LibraryEvent) => void;
/**
 * Protocol that all library inspectors implement to participate
 * in the container's unified inspection system.
 *
 * Libraries implement this interface to make their domain-specific
 * inspection data discoverable and queryable through the container.
 */
export interface LibraryInspector {
	/** Unique library identifier. Must be lowercase kebab-case. */
	readonly name: string;
	/**
	 * Returns a frozen snapshot of the library's current state.
	 * The shape is library-specific but always a frozen record.
	 */
	getSnapshot(): Readonly<Record<string, unknown>>;
	/**
	 * Subscribe to library-specific events.
	 * Returns an unsubscribe function.
	 * Optional -- libraries without push-based events omit this.
	 */
	subscribe?(listener: LibraryEventListener): () => void;
	/**
	 * Dispose the library inspector and clean up resources.
	 * Optional -- called when the container disposes.
	 */
	dispose?(): void;
}
declare const __stepInput: unique symbol;
declare const __stepAccumulated: unique symbol;
declare const __stepOutput: unique symbol;
declare const __stepError: unique symbol;
/** Context provided to step invoke and condition mappers */
export interface StepContext<TInput, TAccumulated> {
	readonly input: TInput;
	readonly results: TAccumulated;
	readonly stepIndex: number;
	readonly executionId: string;
}
/** Context provided to compensation mappers */
export interface CompensationContext<TInput, TAccumulated, TStepOutput, TError> extends StepContext<TInput, TAccumulated> {
	/** The successful output of this step that needs to be undone */
	readonly stepResult: TStepOutput;
	/** The typed error that triggered the compensation chain */
	readonly error: TError;
	/** Index (0-based) of the step whose failure triggered compensation */
	readonly failedStepIndex: number;
	/** Name of the step whose failure triggered compensation */
	readonly failedStepName: string;
}
export interface RetryConfig<TError = unknown> {
	/** Maximum number of retry attempts (default: 0, meaning no retries) */
	readonly maxAttempts: number;
	/** Delay between retries in ms, or a function for custom backoff strategies */
	readonly delay: number | ((attempt: number, error: TError) => number);
	/** Predicate to determine if an error is retryable; defaults to retrying all errors */
	readonly retryIf?: (error: TError) => boolean;
}
export interface StepOptions<TError = unknown> {
	/** Retry configuration for transient failures */
	readonly retry?: RetryConfig<TError>;
	/** Timeout in milliseconds for the forward invocation */
	readonly timeout?: number;
	/** When true, this step is excluded from compensation on saga failure */
	readonly skipCompensation?: boolean;
	/** Custom metadata attached to tracing spans */
	readonly metadata?: Record<string, unknown>;
}
/**
 * A step definition carries phantom type parameters for TInput, TAccumulated,
 * TOutput, and TError. The runtime fields (invoke, compensate, condition) use
 * \`unknown\` parameters so that StepDefinition is covariant in all type params
 * and \`StepDefinition<..., TInput, ...>\` is assignable to \`AnyStepDefinition\`.
 *
 * Type safety is enforced by the builder at construction time.
 */
export interface StepDefinition<TName extends string, TInput, TAccumulated, TOutput, TError, TPort extends Port<string, unknown>> {
	/** Unique step name, used as the key in accumulated results */
	readonly name: TName;
	/** Port to invoke for the forward action */
	readonly port: TPort;
	/** Map saga context to port input for the forward invocation */
	readonly invoke: (ctx: StepContext<unknown, unknown>) => unknown;
	/** Map saga context to port input for the compensation invocation (optional) */
	readonly compensate: ((ctx: CompensationContext<unknown, unknown, unknown, unknown>) => unknown) | null;
	/** Predicate controlling whether this step executes (optional) */
	readonly condition: ((ctx: StepContext<unknown, unknown>) => boolean) | null;
	/** Step configuration options */
	readonly options: StepOptions<unknown>;
	readonly __stepInput?: TInput;
	readonly __stepAccumulated?: TAccumulated;
	readonly __stepOutput?: TOutput;
	readonly __stepError?: TError;
}
/** Type alias erasing all type parameters for use in generic contexts */
export type AnyStepDefinition = StepDefinition<string, unknown, unknown, unknown, unknown, Port<string, unknown>>;
/** Structured error type for invalid StepDefinition inputs */
export type NotAStepDefinitionError<T> = {
	readonly __errorBrand: "NotAStepDefinitionError";
	readonly __message: "Expected a StepDefinition type created with defineStep().build()";
	readonly __received: T;
	readonly __hint: "Use InferStepOutput<typeof YourStep>, not InferStepOutput<YourStep>";
};
/** Extract the step name literal type */
export type InferStepName<S> = S extends StepDefinition<infer N, unknown, unknown, unknown, unknown, Port<string, unknown>> ? N : NotAStepDefinitionError<S>;
/** Extract the step output type */
export type InferStepOutput<S> = S extends StepDefinition<string, unknown, unknown, infer O, unknown, Port<string, unknown>> ? O : NotAStepDefinitionError<S>;
/** Extract the step input type */
export type InferStepInput<S> = S extends StepDefinition<string, infer I, unknown, unknown, unknown, Port<string, unknown>> ? I : NotAStepDefinitionError<S>;
/** Extract the step error type */
export type InferStepError<S> = S extends StepDefinition<string, unknown, unknown, unknown, infer E, Port<string, unknown>> ? E : NotAStepDefinitionError<S>;
/** Extract the port type used by the step */
export type InferStepPort<S> = S extends StepDefinition<string, unknown, unknown, unknown, unknown, infer P> ? P : NotAStepDefinitionError<S>;
/** Recursively collect port types from a tuple of step definitions */
export type CollectStepPorts<TSteps extends readonly AnyStepDefinition[]> = TSteps extends readonly [
	infer Head extends AnyStepDefinition,
	...infer Tail extends readonly AnyStepDefinition[]
] ? InferStepPort<Head> | CollectStepPorts<Tail> : never;
/** Structured error listing which step ports are missing from the graph */
export type MissingSagaStepPortsError<TMissing> = {
	readonly __errorBrand: "MissingSagaStepPortsError";
	readonly __message: "Ports required by saga steps are missing from the graph";
	readonly __received: TMissing;
	readonly __hint: "Register adapters for these ports in the GraphBuilder";
};
/** Validate that all ports required by saga steps are provided in the graph */
export type ValidateSagaPorts<TSteps extends readonly AnyStepDefinition[], TProvided extends Port<string, unknown>> = Exclude<CollectStepPorts<TSteps>, TProvided> extends never ? true : MissingSagaStepPortsError<Exclude<CollectStepPorts<TSteps>, TProvided>>;
/** Stage 1: Name declared, awaiting I/O types */
export interface StepBuilder<TName extends string> {
	io<TInput, TOutput, TError = never>(): StepBuilderWithIO<TName, TInput, TOutput, TError>;
}
/** Stage 2: I/O declared, awaiting port + mapper */
export interface StepBuilderWithIO<TName extends string, TInput, TOutput, TError> {
	invoke<TPort extends Port<string, unknown>>(port: TPort, mapper: (ctx: StepContext<TInput, unknown>) => unknown): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
}
/** Stage 3: Port + mapper set, compensation and options available */
export interface StepBuilderWithInvocation<TName extends string, TInput, TOutput, TError, TPort extends Port<string, unknown>> {
	compensate(mapper: (ctx: CompensationContext<TInput, unknown, TOutput, TError>) => unknown): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	skipCompensation(): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	when(predicate: (ctx: StepContext<TInput, unknown>) => boolean): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	retry(config: RetryConfig<TError>): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	timeout(ms: number): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	options(opts: Partial<StepOptions<TError>>): StepBuilderWithInvocation<TName, TInput, TOutput, TError, TPort>;
	build(): StepDefinition<TName, TInput, unknown, TOutput, TError, TPort>;
}
/**
 * Entry point for creating step definitions.
 *
 * @param name - Unique step name, used as the key in accumulated results
 * @returns A StepBuilder for progressive configuration
 *
 * @example
 * \`\`\`typescript
 * const ReserveStockStep = defineStep("ReserveStock")
 *   .io<{ productId: string }, { reservationId: string }>()
 *   .invoke(InventoryPort, ctx => ({
 *     action: "reserve",
 *     productId: ctx.input.productId,
 *   }))
 *   .compensate(ctx => ({
 *     action: "release",
 *     reservationId: ctx.stepResult.reservationId,
 *   }))
 *   .build();
 * \`\`\`
 */
export declare function defineStep<TName extends string>(name: TName): StepBuilder<TName>;
export interface StepHookContext {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly executionId: string;
	readonly sagaName: string;
	readonly isCompensation: boolean;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface StepHookResultContext {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly result: unknown;
	readonly error: unknown | undefined;
	readonly durationMs: number;
	readonly attemptCount: number;
	readonly executionId: string;
	readonly sagaName: string;
	readonly isCompensation: boolean;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface CompensationHookContext {
	readonly failedStepName: string;
	readonly stepsToCompensate: number;
	readonly executionId: string;
	readonly sagaName: string;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface CompensationResultHookContext {
	readonly compensatedSteps: readonly string[];
	readonly failedSteps: readonly string[];
	readonly executionId: string;
	readonly sagaName: string;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface SagaHooks {
	/** Called before each step executes */
	readonly beforeStep?: (ctx: StepHookContext) => void;
	/** Called after each step completes (success or failure) */
	readonly afterStep?: (ctx: StepHookResultContext) => void;
	/** Called before compensation starts */
	readonly beforeCompensation?: (ctx: CompensationHookContext) => void;
	/** Called after compensation completes */
	readonly afterCompensation?: (ctx: CompensationResultHookContext) => void;
}
export interface SagaOptions {
	/** How to handle compensation failures: sequential, parallel, or best-effort */
	readonly compensationStrategy: "sequential" | "parallel" | "best-effort";
	/** Enable persistence for long-running saga resumption */
	readonly persistent?: boolean;
	/** Maximum concurrent steps (for parallel sections) */
	readonly maxConcurrency?: number;
	/** Global timeout for entire saga in ms */
	readonly timeout?: number;
	/** Cross-cutting hooks for step lifecycle events */
	readonly hooks?: SagaHooks;
	/** Custom metadata for tracing and diagnostics */
	readonly metadata?: Record<string, unknown>;
}
/** Recursive deep readonly utility (local to avoid cross-package dependency) */
export type DeepReadonly<T> = T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepReadonly<U>> : T extends object ? {
	readonly [K in keyof T]: DeepReadonly<T[K]>;
} : T;
/** Compute accumulated results type from a tuple of step definitions */
export type AccumulatedResults<TSteps extends readonly AnyStepDefinition[]> = DeepReadonly<{
	[S in TSteps[number] as InferStepName<S>]: InferStepOutput<S>;
}>;
/** Compute the union of all step error types from step definitions */
export type AccumulatedErrors<TSteps> = TSteps extends readonly (infer S)[] ? InferStepError<S> : never;
declare const __sagaInput: unique symbol;
declare const __sagaErrors: unique symbol;
export interface SagaDefinition<TName extends string, TInput, TOutput, TSteps extends readonly AnyStepDefinition[], TErrors> {
	/** Unique saga name */
	readonly name: TName;
	/** Ordered list of steps */
	readonly steps: TSteps;
	/** Map accumulated results to saga output */
	readonly outputMapper: (results: AccumulatedResults<TSteps>) => TOutput;
	/** Saga configuration options */
	readonly options: SagaOptions;
	/** @internal Phantom type carrier for TInput */
	readonly __sagaInput?: TInput;
	/** @internal Phantom type carrier for TErrors */
	readonly __sagaErrors?: TErrors;
}
/** Saga definition with all type parameters erased */
export type AnySagaDefinition = SagaDefinition<string, unknown, unknown, readonly AnyStepDefinition[], unknown>;
export type BranchAccumulatedResults<TKey extends string, TBranches extends Record<TKey, readonly AnyStepDefinition[]>> = {
	readonly __selectedBranch: TKey;
} & {
	[K in TBranches[TKey][number] as InferStepName<K>]?: InferStepOutput<K>;
};
export type BranchAccumulatedErrors<TKey extends string, TBranches extends Record<TKey, readonly AnyStepDefinition[]>> = AccumulatedErrors<TBranches[TKey]>;
/** Structured error type for invalid SagaDefinition inputs */
export type NotASagaDefinitionError<T> = {
	readonly __errorBrand: "NotASagaDefinitionError";
	readonly __message: "Expected a SagaDefinition type created with defineSaga().build()";
	readonly __received: T;
	readonly __hint: "Use InferSagaInput<typeof YourSaga>, not InferSagaInput<YourSaga>";
};
/** Extract saga name literal type */
export type InferSagaName<S> = S extends SagaDefinition<infer N, unknown, unknown, readonly AnyStepDefinition[], unknown> ? N : NotASagaDefinitionError<S>;
/** Extract saga input type */
export type InferSagaInput<S> = S extends SagaDefinition<string, infer I, unknown, readonly AnyStepDefinition[], unknown> ? I : NotASagaDefinitionError<S>;
/** Extract saga output type */
export type InferSagaOutput<S> = S extends SagaDefinition<string, unknown, infer O, readonly AnyStepDefinition[], unknown> ? O : NotASagaDefinitionError<S>;
/** Extract saga steps tuple */
export type InferSagaSteps<S> = S extends SagaDefinition<string, unknown, unknown, infer Steps, unknown> ? Steps : NotASagaDefinitionError<S>;
/** Extract the accumulated error union from a saga definition */
export type InferSagaErrors<S> = S extends SagaDefinition<string, unknown, unknown, infer Steps extends readonly AnyStepDefinition[], unknown> ? AccumulatedErrors<Steps> : NotASagaDefinitionError<S>;
/** Extract a step's output type by step name from a saga */
export type InferStepOutputByName<TSaga extends AnySagaDefinition, TName extends string> = InferSagaSteps<TSaga> extends readonly (infer S extends AnyStepDefinition)[] ? S extends {
	readonly name: TName;
} ? InferStepOutput<S> : never : never;
/** Check whether a step name already exists in the accumulated steps */
export type HasStepName<TSteps extends readonly AnyStepDefinition[], TName extends string> = TName extends InferStepName<TSteps[number]> ? true : false;
/** Structured error returned when a duplicate step name is detected */
export type StepNameAlreadyExistsError<TName extends string> = {
	readonly __errorBrand: "StepNameAlreadyExistsError";
	readonly __message: "Duplicate step name detected. Each step must have a unique name.";
	readonly __received: TName;
	readonly __hint: "The accumulated results map uses step names as keys, so duplicates would silently overwrite earlier results.";
};
/** Stage 1: Name declared, awaiting input type */
export interface SagaBuilder<TName extends string> {
	input<TInput>(): SagaBuilderWithInput<TName, TInput, [
	], never>;
}
/** Stage 2: Input declared, steps can be added */
export interface SagaBuilderWithInput<TName extends string, TInput, TSteps extends readonly AnyStepDefinition[], TErrors> {
	step<S extends StepDefinition<string, TInput, unknown, unknown, unknown, Port<string, unknown>>>(...args: HasStepName<TSteps, InferStepName<S>> extends true ? [
		step: StepNameAlreadyExistsError<InferStepName<S>>
	] : [
		step: S
	]): SagaBuilderWithInput<TName, TInput, [
		...TSteps,
		S
	], TErrors | InferStepError<S>>;
	parallel<PSteps extends readonly StepDefinition<string, TInput, unknown, unknown, unknown, Port<string, unknown>>[]>(steps: PSteps): SagaBuilderWithInput<TName, TInput, [
		...TSteps,
		...PSteps
	], TErrors | AccumulatedErrors<PSteps>>;
	branch<TKey extends string, TBranches extends Record<TKey, readonly StepDefinition<string, TInput, unknown, unknown, unknown, Port<string, unknown>>[]>>(selector: (ctx: StepContext<TInput, AccumulatedResults<TSteps>>) => TKey, branches: TBranches): SagaBuilderWithInput<TName, TInput, [
		...TSteps,
		StepDefinition<"__branch", TInput, unknown, BranchAccumulatedResults<TKey, TBranches>, BranchAccumulatedErrors<TKey, TBranches>, Port<string, unknown>>
	], TErrors | BranchAccumulatedErrors<TKey, TBranches>>;
	saga<TSaga extends AnySagaDefinition>(saga: TSaga, mapper: (ctx: StepContext<TInput, AccumulatedResults<TSteps>>) => InferSagaInput<TSaga>): SagaBuilderWithInput<TName, TInput, [
		...TSteps,
		StepDefinition<InferSagaName<TSaga> & string, TInput, unknown, InferSagaOutput<TSaga>, InferSagaErrors<TSaga>, Port<string, unknown>>
	], TErrors | InferSagaErrors<TSaga>>;
	output<TOutput>(mapper: (results: AccumulatedResults<TSteps>) => TOutput): SagaBuilderWithOutput<TName, TInput, TOutput, TSteps, TErrors>;
}
/** Stage 3: Output mapper declared, awaiting options and build */
export interface SagaBuilderWithOutput<TName extends string, TInput, TOutput, TSteps extends readonly AnyStepDefinition[], TErrors> {
	options(opts: SagaOptions): SagaBuilderWithOutput<TName, TInput, TOutput, TSteps, TErrors>;
	build(): SagaDefinition<TName, TInput, TOutput, TSteps, TErrors>;
}
/**
 * Entry point for creating saga definitions.
 *
 * @param name - Unique saga name, used for identification and tracing
 * @returns A SagaBuilder for progressive configuration
 *
 * @example
 * \`\`\`typescript
 * const OrderSaga = defineSaga("OrderSaga")
 *   .input<OrderInput>()
 *   .step(ValidateOrderStep)
 *   .step(ReserveStockStep)
 *   .step(ChargePaymentStep)
 *   .output(results => ({
 *     orderId: results.ValidateOrder.orderId,
 *     transactionId: results.ChargePayment.transactionId,
 *   }))
 *   .options({ compensationStrategy: "sequential" })
 *   .build();
 * \`\`\`
 */
export declare function defineSaga<TName extends string>(name: TName): SagaBuilder<TName>;
declare const RESULT_BRAND: unique symbol;
declare const OPTION_BRAND: unique symbol;
/**
 * The presence variant of \`Option\`. Represents a value that exists.
 *
 * \`Some<T>\` carries a \`value\` of type \`T\` and provides transformation,
 * chaining, extraction, and conversion methods. Instances are created
 * via the \`some()\` factory and are frozen plain objects branded with \`OPTION_BRAND\`.
 *
 * @example
 * \`\`\`ts
 * import { some } from '@hex-di/result';
 *
 * const opt = some(42);
 * opt.isSome();      // true
 * opt.map(x => x * 2); // Some(84)
 * opt.unwrapOr(0);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-002
 */
export interface Some<T> {
	readonly _tag: "Some";
	readonly value: T;
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<T>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: T) => boolean): boolean;
	map<U>(f: (value: T) => U): Some<U>;
	filter(predicate: (value: T) => boolean): Option\$1<T>;
	flatten<U>(this: Some<Option\$1<U>>): Option\$1<U>;
	zip<U>(other: Option\$1<U>): Option\$1<[
		T,
		U
	]>;
	zipWith<U, R>(other: Option\$1<U>, f: (a: T, b: U) => R): Option\$1<R>;
	andThen<U>(f: (value: T) => Option\$1<U>): Option\$1<U>;
	orElse(f: () => Option\$1<T>): Some<T>;
	match<A, B>(onSome: (value: T) => A, onNone: () => B): A;
	unwrapOr<U>(defaultValue: U): T;
	expect(message: string): T;
	toResult<E>(onNone: () => E): Ok<T, E>;
	toNullable(): T;
	toUndefined(): T;
	toJSON(): {
		_tag: "Some";
		_schemaVersion: 1;
		value: T;
	};
	transpose<U, E>(this: Some<Result<U, E>>): Result<Some<U>, E>;
}
/**
 * The absence variant of \`Option\`. Represents the lack of a value.
 *
 * \`None\` carries no value and short-circuits all transformations and chaining operations.
 * Extraction methods return defaults or throw. A single frozen singleton is reused
 * for all \`none()\` calls.
 *
 * @example
 * \`\`\`ts
 * import { none } from '@hex-di/result';
 *
 * const opt = none();
 * opt.isNone();      // true
 * opt.map(x => x * 2); // None
 * opt.unwrapOr(0);   // 0
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-003
 */
export interface None {
	readonly _tag: "None";
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<never>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: never) => boolean): boolean;
	map<U>(f: (value: never) => U): None;
	filter(predicate: (value: never) => boolean): None;
	flatten(): None;
	zip<U>(other: Option\$1<U>): None;
	zipWith<U, R>(other: Option\$1<U>, f: (a: never, b: U) => R): None;
	andThen<U>(f: (value: never) => Option\$1<U>): None;
	orElse<T>(f: () => Option\$1<T>): Option\$1<T>;
	match<A, B>(onSome: (value: never) => A, onNone: () => B): B;
	unwrapOr<U>(defaultValue: U): U;
	expect(message: string): never;
	toResult<E>(onNone: () => E): Err<never, E>;
	toNullable(): null;
	toUndefined(): undefined;
	toJSON(): {
		_tag: "None";
		_schemaVersion: 1;
	};
	transpose(): Ok<None, never>;
}
type Option\$1<T> = Some<T> | None;
export interface ResultAsync<T, E> extends PromiseLike<Result<T, E>> {
	map<U>(f: (value: T) => U | Promise<U>): ResultAsync<U, E>;
	mapErr<F>(f: (error: E) => F | Promise<F>): ResultAsync<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U | Promise<U>, onErr: (error: E) => F | Promise<F>): ResultAsync<U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F> | ResultAsync<U, F>): ResultAsync<T | U, F>;
	andTee(f: (value: T) => void | Promise<void>): ResultAsync<T, E>;
	orTee(f: (error: E) => void | Promise<void>): ResultAsync<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F> | ResultAsync<unknown, F>): ResultAsync<T, E | F>;
	inspect(f: (value: T) => void): ResultAsync<T, E>;
	inspectErr(f: (error: E) => void): ResultAsync<T, E>;
	match<A, B>(onOk: (value: T) => A | Promise<A>, onErr: (error: E) => B | Promise<B>): Promise<A | B>;
	unwrapOr<U>(defaultValue: U): Promise<T | U>;
	unwrapOrElse<U>(f: (error: E) => U): Promise<T | U>;
	orDie(): Promise<T>;
	toNullable(): Promise<T | null>;
	toUndefined(): Promise<T | undefined>;
	intoTuple(): Promise<[
		null,
		T
	] | [
		E,
		null
	]>;
	merge(): Promise<T | E>;
	flatten<U>(this: ResultAsync<Result<U, E>, E>): ResultAsync<U, E>;
	flip(): ResultAsync<E, T>;
	toJSON(): Promise<{
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	} | {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	}>;
}
/**
 * The success variant of {@link Result}. Contains a \`value\` of type \`T\`.
 *
 * \`Ok\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link ok} factory function. The phantom type parameter \`E\` has no runtime
 * representation; the \`ok()\` factory produces \`Ok<T, never>\`, where \`never\` extends any \`E\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error (phantom on Ok; defaults to \`never\` from the factory).
 *
 * @example
 * \`\`\`ts
 * import { ok } from '@hex-di/result';
 *
 * const result = ok(42);
 * console.log(result.isOk());  // true
 * console.log(result.value);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-004}
 */
export interface Ok<T, E> {
	readonly _tag: "Ok";
	readonly value: T;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Ok<U, E>;
	mapErr<F>(f: (error: E) => F): Ok<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Ok<U, F>;
	flatten<U, E2>(this: Ok<Result<U, E2>, E>): Result<U, E | E2>;
	flip(): Err<E, T>;
	and<U, F>(other: Result<U, F>): Result<U, E | F>;
	or<U, F>(other: Result<U, F>): Ok<T, E>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Result<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Ok<T, E>;
	andTee(f: (value: T) => void): Ok<T, E>;
	orTee(f: (error: E) => void): Ok<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Result<T, E | F>;
	inspect(f: (value: T) => void): Ok<T, E>;
	inspectErr(f: (error: E) => void): Ok<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): A;
	unwrapOr<U>(defaultValue: U): T;
	unwrapOrElse<U>(f: (error: E) => U): T;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): T;
	expectErr(message: string): never;
	orDie(): T;
	toNullable(): T;
	toUndefined(): T;
	intoTuple(): [
		null,
		T
	];
	merge(): T;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): Some<T>;
	toOptionErr(): None;
	transpose<U>(this: Ok<Option\$1<U>, E>): Option\$1<Result<U, E>>;
	toJSON(): {
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	};
	[Symbol.iterator](): Generator<never, T, unknown>;
}
/**
 * The failure variant of {@link Result}. Contains an \`error\` of type \`E\`.
 *
 * \`Err\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link err} factory function. The phantom type parameter \`T\` has no runtime
 * representation; the \`err()\` factory produces \`Err<never, E>\`, where \`never\` extends any \`T\`.
 *
 * @typeParam T - The type of the success value (phantom on Err; defaults to \`never\` from the factory).
 * @typeParam E - The type of the error.
 *
 * @example
 * \`\`\`ts
 * import { err } from '@hex-di/result';
 *
 * const result = err('not found');
 * console.log(result.isErr());  // true
 * console.log(result.error);    // 'not found'
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-005}
 */
export interface Err<T, E> {
	readonly _tag: "Err";
	readonly error: E;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Err<U, E>;
	mapErr<F>(f: (error: E) => F): Err<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Err<U, F>;
	flatten<U, E2>(this: Err<Result<U, E2>, E>): Err<U, E>;
	flip(): Ok<E, T>;
	and<U, F>(other: Result<U, F>): Err<U, E>;
	or<U, F>(other: Result<U, F>): Result<T | U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Err<U, E>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Result<T | U, F>;
	andTee(f: (value: T) => void): Err<T, E>;
	orTee(f: (error: E) => void): Err<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Err<T, E>;
	inspect(f: (value: T) => void): Err<T, E>;
	inspectErr(f: (error: E) => void): Err<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): B;
	unwrapOr<U>(defaultValue: U): U;
	unwrapOrElse<U>(f: (error: E) => U): U;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): never;
	expectErr(message: string): E;
	orDie(): never;
	toNullable(): null;
	toUndefined(): undefined;
	intoTuple(): [
		E,
		null
	];
	merge(): E;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): None;
	toOptionErr(): Some<E>;
	transpose(): Some<Err<never, E>>;
	toJSON(): {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	};
	[Symbol.iterator](): Generator<Err<never, E>, never, unknown>;
}
/**
 * A discriminated union of {@link Ok} and {@link Err}.
 *
 * \`Result<T, E>\` represents either a success (\`Ok\`) holding a value of type \`T\`,
 * or a failure (\`Err\`) holding an error of type \`E\`. TypeScript narrows to the
 * correct variant after checking \`_tag\`, \`isOk()\`, or \`isErr()\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error value.
 *
 * @example
 * \`\`\`ts
 * import { ok, err, type Result } from '@hex-di/result';
 *
 * function divide(a: number, b: number): Result<number, string> {
 *   if (b === 0) return err('division by zero');
 *   return ok(a / b);
 * }
 *
 * const result = divide(10, 2);
 * if (result.isOk()) {
 *   console.log(result.value); // 5
 * }
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-006}
 */
export type Result<T, E> = Ok<T, E> | Err<T, E>;
/**
 * Extracts the success type \`T\` from a \`Result<T, E>\` or \`ResultAsync<T, E>\`.
 *
 * @example
 * \`\`\`ts
 * import { ok } from '@hex-di/result';
 * import type { InferOk } from '@hex-di/result';
 *
 * type R = ReturnType<typeof ok<number>>;
 * type T = InferOk<R>; // number
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOk<R> = R extends Result<infer T, unknown> ? T : R extends ResultAsync<infer T, unknown> ? T : never;
/**
 * Extracts the error type \`E\` from a \`Result<T, E>\` or \`ResultAsync<T, E>\`.
 *
 * @example
 * \`\`\`ts
 * import { err } from '@hex-di/result';
 * import type { InferErr } from '@hex-di/result';
 *
 * type R = ReturnType<typeof err<string>>;
 * type E = InferErr<R>; // string
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErr<R> = R extends Result<unknown, infer E> ? E : R extends ResultAsync<unknown, infer E> ? E : never;
/**
 * Extracts the \`Ok\` types from a tuple of \`Result\` or \`ResultAsync\` values as a mapped tuple.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferOkTuple } from '@hex-di/result';
 *
 * type Rs = [Result<number, string>, Result<boolean, Error>];
 * type Oks = InferOkTuple<Rs>; // [number, boolean]
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOkTuple<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = {
	[K in keyof T]: InferOk<T[K]>;
};
/**
 * Extracts the union of all \`Err\` types from a tuple of \`Result\` or \`ResultAsync\` values.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferErrUnion } from '@hex-di/result';
 *
 * type Rs = [Result<number, "a">, Result<boolean, "b">];
 * type Errs = InferErrUnion<Rs>; // "a" | "b"
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErrUnion<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = InferErr<T[number]>;
/**
 * Extracts the union of \`Ok\` types from a tuple of \`Result\` or \`ResultAsync\` values.
 * Useful for \`Result.any\` which returns a single Ok from the first success.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferOkUnion } from '@hex-di/result';
 *
 * type Rs = [Result<number, string>, Result<boolean, string>];
 * type OkU = InferOkUnion<Rs>; // number | boolean
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOkUnion<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = InferOk<T[number]>;
/**
 * A non-empty array type that guarantees at least one element.
 * The first element is always present (\`T\`), followed by zero or more additional elements.
 *
 * @example
 * \`\`\`ts
 * import type { NonEmptyArray } from '@hex-di/result';
 *
 * const valid: NonEmptyArray<number> = [1, 2, 3]; // ok
 * // const invalid: NonEmptyArray<number> = [];    // type error
 *
 * function head<T>(arr: NonEmptyArray<T>): T {
 *   return arr[0]; // T, not T | undefined
 * }
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type NonEmptyArray<T> = [
	T,
	...T[]
];
/**
 * Extracts the \`Err\` types from a tuple of \`Result\` or \`ResultAsync\` values as a mapped tuple.
 * Useful for \`Result.any\` error collection.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferErrTuple } from '@hex-di/result';
 *
 * type Rs = [Result<number, "a">, Result<boolean, "b">];
 * type Errs = InferErrTuple<Rs>; // ["a", "b"]
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErrTuple<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = {
	[K in keyof T]: InferErr<T[K]>;
};
declare function all<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, InferErrUnion<R>>;
declare function allSettled<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, InferErrUnion<R>[]>;
declare function any<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkUnion<R>, InferErrTuple<R>>;
export type InferErrUnionFromRecord<R extends Record<string, Result<unknown, unknown>>> = InferErr<R[keyof R]>;
declare function collect<R extends Record<string, Result<unknown, unknown>>>(results: R): Result<{
	[K in keyof R]: InferOk<R[K]>;
}, InferErrUnionFromRecord<R>>;
declare function partition<T, E>(results: readonly Result<T, E>[]): [
	T[],
	E[]
];
declare function forEach<T, U, E>(items: readonly T[], f: (item: T, index: number) => Result<U, E>): Result<U[], E>;
declare function zipOrAccumulate<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, NonEmptyArray<InferErrUnion<R>>>;
declare class ResultAsync\$1<T, E> implements ResultAsync<T, E> {
	#private;
	private constructor();
	/**
	 * Creates a \`ResultAsync\` wrapping an \`Ok\` value.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.ok(42);
	 * const inner = await result; // Ok(42)
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static ok<T>(value: T): ResultAsync\$1<T, never>;
	/**
	 * Creates a \`ResultAsync\` wrapping an \`Err\` value.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.err("not found");
	 * const inner = await result; // Err("not found")
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static err<E>(error: E): ResultAsync\$1<never, E>;
	/**
	 * Wraps a \`Promise<T>\` that might reject into a \`ResultAsync\`.
	 *
	 * Resolution produces \`Ok(value)\`. Rejection produces \`Err(mapErr(reason))\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.fromPromise(
	 *   fetch("/api/users").then(r => r.json()),
	 *   (error) => \`Request failed: \${error}\`
	 * );
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromPromise<T, E>(promise: Promise<T>, mapErr: (error: unknown) => E): ResultAsync\$1<T, E>;
	/**
	 * Wraps a \`Promise<T>\` that is guaranteed to never reject into a \`ResultAsync\`.
	 *
	 * Resolution produces \`Ok(value)\`. Since the promise never rejects, the error
	 * type is \`never\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.fromSafePromise(Promise.resolve(42));
	 * const inner = await result; // Ok(42)
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromSafePromise<T>(promise: Promise<T>): ResultAsync\$1<T, never>;
	/**
	 * Creates a ResultAsync from a Promise that resolves to a Result.
	 *
	 * This is useful when you have an async function that already returns Result
	 * values (e.g., sequential effect execution loops that check \`_tag\` and return
	 * early on error). It avoids the need for \`andThen\` flattening, which has
	 * inference issues in TypeScript 5.9.
	 *
	 * The promise must never reject — it should always resolve to either
	 * ok(value) or err(error).
	 *
	 * @param promise - A Promise that resolves to a Result<T, E>
	 * @returns A ResultAsync<T, E> wrapping the promise
	 */
	static fromResult<T, E>(promise: Promise<Result<T, E>>): ResultAsync\$1<T, E>;
	/**
	 * Wraps an async function that might throw into a function returning \`ResultAsync\`.
	 *
	 * Returns a new function with the same parameter types that returns \`ResultAsync\`
	 * instead of \`Promise\`. Rejections are caught and mapped via \`mapErr\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const safeReadFile = ResultAsync.fromThrowable(
	 *   async (path: string) => fs.promises.readFile(path, "utf-8"),
	 *   (error) => \`Read failed: \${error}\`
	 * );
	 *
	 * const result = safeReadFile("config.json");
	 * // ResultAsync<string, string>
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromThrowable<A extends readonly unknown[], T, E>(fn: (...args: A) => Promise<T>, mapErr: (error: unknown) => E): (...args: A) => ResultAsync\$1<T, E>;
	static fromCallback<T, E>(fn: (callback: (error: E | null, value: T) => void) => void): ResultAsync\$1<T, E>;
	static race<R extends readonly ResultAsync\$1<unknown, unknown>[]>(...results: R): ResultAsync\$1<InferOkUnion<R>, InferErrUnion<R>>;
	static all: typeof all;
	static allSettled: typeof allSettled;
	static any: typeof any;
	static collect: typeof collect;
	static partition: typeof partition;
	static forEach: typeof forEach;
	static zipOrAccumulate: typeof zipOrAccumulate;
	then<A = Result<T, E>, B = never>(onfulfilled?: ((value: Result<T, E>) => A | PromiseLike<A>) | null | undefined, onrejected?: ((reason: unknown) => B | PromiseLike<B>) | null | undefined): PromiseLike<A | B>;
	map<U>(f: (value: T) => U | Promise<U>): ResultAsync\$1<U, E>;
	mapErr<F>(f: (error: E) => F | Promise<F>): ResultAsync\$1<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U | Promise<U>, onErr: (error: E) => F | Promise<F>): ResultAsync\$1<U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync\$1<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F> | ResultAsync<U, F>): ResultAsync\$1<T | U, F>;
	andTee(f: (value: T) => void | Promise<void>): ResultAsync\$1<T, E>;
	orTee(f: (error: E) => void | Promise<void>): ResultAsync\$1<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F> | ResultAsync<unknown, F>): ResultAsync\$1<T, E | F>;
	inspect(f: (value: T) => void): ResultAsync\$1<T, E>;
	inspectErr(f: (error: E) => void): ResultAsync\$1<T, E>;
	match<A, B>(onOk: (value: T) => A | Promise<A>, onErr: (error: E) => B | Promise<B>): Promise<A | B>;
	unwrapOr<U>(defaultValue: U): Promise<T | U>;
	unwrapOrElse<U>(f: (error: E) => U): Promise<T | U>;
	orDie(): Promise<T>;
	toNullable(): Promise<T | null>;
	toUndefined(): Promise<T | undefined>;
	intoTuple(): Promise<[
		null,
		T
	] | [
		E,
		null
	]>;
	merge(): Promise<T | E>;
	flatten<U>(this: ResultAsync\$1<Result<U, E>, E>): ResultAsync\$1<U, E>;
	flip(): ResultAsync\$1<E, T>;
	toJSON(): Promise<{
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	} | {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	}>;
}
/**
 * Saga Error Types
 *
 * Defines the SagaError tagged union and all error variants.
 * All saga failures are represented as tagged union members with
 * full diagnostic context.
 *
 * @packageDocumentation
 */
/**
 * Base interface shared by all SagaError variants.
 * Provides diagnostic context for every saga failure.
 */
export interface SagaErrorBase {
	/** Unique execution ID for correlating with tracing spans and persistence records */
	readonly executionId: string;
	/** Name of the saga definition that failed */
	readonly sagaName: string;
	/** Name of the step that caused the failure */
	readonly stepName: string;
	/** Zero-based position of the failing step in the saga */
	readonly stepIndex: number;
	/** Human-readable error message describing the failure */
	readonly message: string;
	/** Names of steps that completed successfully before the failure */
	readonly completedSteps: readonly string[];
	/** Names of steps that were successfully compensated after the failure */
	readonly compensatedSteps: readonly string[];
}
/** A forward step failed after retries exhausted; compensation succeeded fully */
export interface StepFailedError<TCause = unknown> extends SagaErrorBase {
	readonly _tag: "StepFailed";
	readonly cause: TCause;
}
/** A compensation handler itself failed -- system is in an inconsistent state */
export interface CompensationFailedError<TCause = unknown> extends SagaErrorBase {
	readonly _tag: "CompensationFailed";
	/** The original error that triggered the compensation chain */
	readonly cause: TCause;
	/** The error thrown by the compensation handler */
	readonly compensationCause: unknown;
	/** Steps whose compensation failed (includes the failing step) */
	readonly failedCompensationSteps: readonly string[];
}
/** A step or the entire saga exceeded its configured timeout */
export interface TimeoutError extends SagaErrorBase {
	readonly _tag: "Timeout";
	/** The configured timeout in milliseconds that was exceeded */
	readonly timeoutMs: number;
}
/** The saga was explicitly cancelled via the runtime API */
export interface CancelledError extends SagaErrorBase {
	readonly _tag: "Cancelled";
}
/** Input validation failed before any steps ran */
export interface ValidationFailedError extends SagaErrorBase {
	readonly _tag: "ValidationFailed";
	/** Validation error details */
	readonly cause: unknown;
}
/** A step references a port not registered in the container */
export interface PortNotFoundError extends SagaErrorBase {
	readonly _tag: "PortNotFound";
	/** The port name that was not found */
	readonly portName: string;
}
/** The persistence layer failed to save or load saga state */
export interface PersistenceFailedError extends SagaErrorBase {
	readonly _tag: "PersistenceFailed";
	/** The persistence operation that failed */
	readonly operation: "save" | "load" | "delete" | "update";
	/** The underlying persistence error */
	readonly cause: unknown;
}
/** Tagged union of all saga error variants */
export type SagaError<TCause = unknown> = StepFailedError<TCause> | CompensationFailedError<TCause> | TimeoutError | CancelledError | ValidationFailedError | PortNotFoundError | PersistenceFailedError;
/** Successful saga execution result */
export interface SagaSuccess<TOutput> {
	readonly output: TOutput;
	readonly executionId: string;
}
/** Tagged union for management operation failures */
export type ManagementError = {
	readonly _tag: "ExecutionNotFound";
	readonly message: string;
	readonly executionId: string;
} | {
	readonly _tag: "InvalidOperation";
	readonly message: string;
	readonly executionId: string;
	readonly currentState: SagaStatusType;
	readonly attemptedOperation: string;
} | {
	readonly _tag: "PersistenceFailed";
	readonly message: string;
	readonly operation: string;
	readonly cause: unknown;
};
export type SagaStatusType = "pending" | "running" | "compensating" | "completed" | "failed" | "cancelled";
export type SagaStatus = {
	readonly state: "pending";
	readonly executionId: string;
	readonly sagaName: string;
	readonly createdAt: number;
} | {
	readonly state: "running";
	readonly executionId: string;
	readonly sagaName: string;
	readonly currentStepIndex: number;
	readonly currentStepName: string;
	readonly completedSteps: ReadonlyArray<string>;
	readonly startedAt: number;
} | {
	readonly state: "compensating";
	readonly executionId: string;
	readonly sagaName: string;
	readonly failedStepName: string;
	readonly failedStepIndex: number;
	readonly compensatingStepIndex: number;
	readonly compensatingStepName: string;
	readonly compensatedSteps: ReadonlyArray<string>;
	readonly startedAt: number;
	readonly error: SagaError<unknown>;
} | {
	readonly state: "completed";
	readonly executionId: string;
	readonly sagaName: string;
	readonly completedSteps: ReadonlyArray<string>;
	readonly startedAt: number;
	readonly completedAt: number;
	readonly durationMs: number;
} | {
	readonly state: "failed";
	readonly executionId: string;
	readonly sagaName: string;
	readonly error: SagaError<unknown>;
	readonly failedStepName: string;
	readonly compensated: boolean;
	readonly compensatedSteps: ReadonlyArray<string>;
	readonly startedAt: number;
	readonly failedAt: number;
	readonly durationMs: number;
} | {
	readonly state: "cancelled";
	readonly executionId: string;
	readonly sagaName: string;
	readonly stepName: string;
	readonly compensated: boolean;
	readonly compensatedSteps: ReadonlyArray<string>;
	readonly startedAt: number;
	readonly cancelledAt: number;
};
declare const SagaPortSymbol: unique symbol;
declare const SagaManagementPortSymbol: unique symbol;
declare const __sagaInputType: unique symbol;
declare const __sagaOutputType: unique symbol;
declare const __sagaErrorType: unique symbol;
/** Domain port interface - trigger a saga execution */
export interface SagaExecutor<TInput, TOutput, TError> {
	execute(input: TInput): ResultAsync\$1<SagaSuccess<TOutput>, SagaError<TError>>;
}
/** Management/infrastructure port interface */
export interface SagaManagementExecutor<TOutput, TError> {
	resume(executionId: string): ResultAsync\$1<SagaSuccess<TOutput>, SagaError<TError>>;
	cancel(executionId: string): ResultAsync\$1<void, ManagementError>;
	getStatus(executionId: string): ResultAsync\$1<SagaStatus, ManagementError>;
	listExecutions(filters?: ExecutionFilters): ResultAsync\$1<SagaExecutionSummary[], ManagementError>;
}
export interface ExecutionFilters {
	readonly sagaName?: string;
	readonly status?: SagaStatusType;
	readonly limit?: number;
	readonly offset?: number;
}
export interface SagaExecutionSummary {
	readonly executionId: string;
	readonly sagaName: string;
	readonly status: SagaStatusType;
	readonly startedAt: number;
	readonly completedAt: number | null;
	readonly stepCount: number;
	readonly completedStepCount: number;
	readonly compensated: boolean;
}
/** Branded saga port that resolves to SagaExecutor */
export type SagaPort<TName extends string, TInput, TOutput, TError> = Port<TName, SagaExecutor<TInput, TOutput, TError>> & {
	readonly [SagaPortSymbol]: true;
	readonly __sagaInputType: TInput;
	readonly __sagaOutputType: TOutput;
	readonly __sagaErrorType: TError;
};
/** Branded management port that resolves to SagaManagementExecutor */
export type SagaManagementPort<TName extends string, TOutput, TError> = Port<TName, SagaManagementExecutor<TOutput, TError>> & {
	readonly [SagaManagementPortSymbol]: true;
	readonly __sagaOutputType: TOutput;
	readonly __sagaErrorType: TError;
};
export interface SagaPortConfig<TName extends string> {
	/** Unique port name */
	readonly name: TName;
	/** Human-readable description */
	readonly description?: string;
	/** Custom metadata for tracing */
	readonly metadata?: Record<string, unknown>;
}
/** Tagged union of persistence operation errors */
export type PersistenceError = {
	readonly _tag: "NotFound";
	readonly executionId: string;
} | {
	readonly _tag: "StorageFailure";
	readonly operation: string;
	readonly cause: unknown;
} | {
	readonly _tag: "SerializationFailure";
	readonly cause: unknown;
};
export interface CompletedStepState {
	readonly name: string;
	readonly index: number;
	readonly output: unknown;
	readonly skipped: boolean;
	readonly completedAt: string;
}
export interface CompensationState {
	readonly active: boolean;
	readonly compensatedSteps: readonly string[];
	readonly failedSteps: readonly string[];
	readonly triggeringStepIndex: number | null;
	readonly startedAt?: string;
	readonly completedAt?: string;
	readonly durationMs?: number;
}
export interface SerializedSagaError {
	readonly _tag: string;
	readonly name: string;
	readonly message: string;
	readonly stack: string | null;
	readonly code: string | null;
	readonly fields: Record<string, unknown>;
}
export interface SagaExecutionState {
	readonly executionId: string;
	readonly sagaName: string;
	readonly input: unknown;
	readonly currentStep: number;
	readonly completedSteps: readonly CompletedStepState[];
	readonly status: SagaStatusType;
	readonly error: SerializedSagaError | null;
	readonly compensation: CompensationState;
	readonly timestamps: {
		readonly startedAt: string;
		readonly updatedAt: string;
		readonly completedAt: string | null;
	};
	readonly metadata: Record<string, unknown>;
	readonly totalSteps?: number;
}
/** Persistence interface for saga state */
export interface SagaPersister {
	save(state: SagaExecutionState): ResultAsync\$1<void, PersistenceError>;
	load(executionId: string): ResultAsync\$1<SagaExecutionState | null, PersistenceError>;
	delete(executionId: string): ResultAsync\$1<void, PersistenceError>;
	list(filters?: PersisterFilters): ResultAsync\$1<SagaExecutionState[], PersistenceError>;
	update(executionId: string, updates: Partial<SagaExecutionState>): ResultAsync\$1<void, PersistenceError>;
}
export interface PersisterFilters {
	readonly sagaName?: string;
	readonly status?: SagaStatusType;
	readonly limit?: number;
}
/** Structured error for non-SagaPort types */
export type NotASagaPortError<T> = {
	readonly __errorBrand: "NotASagaPortError";
	readonly __message: "Expected a SagaPort type created with sagaPort()";
	readonly __received: T;
	readonly __hint: "Use InferSagaPortInput<typeof YourPort>, not InferSagaPortInput<YourPort>";
};
/** Structured error for non-SagaManagementPort types */
export type NotASagaManagementPortError<T> = {
	readonly __errorBrand: "NotASagaManagementPortError";
	readonly __message: "Expected a SagaManagementPort type created with sagaManagementPort()";
	readonly __received: T;
	readonly __hint: "Use InferSagaManagementPortOutput<typeof YourPort>, not InferSagaManagementPortOutput<YourPort>";
};
/** Extract the input type from a SagaPort */
export type InferSagaPortInput<T> = [
	T
] extends [
	SagaPort<string, infer TInput, unknown, unknown>
] ? TInput : NotASagaPortError<T>;
/** Extract the output type from a SagaPort */
export type InferSagaPortOutput<T> = [
	T
] extends [
	SagaPort<string, unknown, infer TOutput, unknown>
] ? TOutput : NotASagaPortError<T>;
/** Extract the error type from a SagaPort */
export type InferSagaPortError<T> = [
	T
] extends [
	SagaPort<string, unknown, unknown, infer TError>
] ? TError : NotASagaPortError<T>;
/** Extract the name literal type from a SagaPort */
export type InferSagaPortName<T> = [
	T
] extends [
	SagaPort<infer TName, unknown, unknown, unknown>
] ? TName : NotASagaPortError<T>;
/** Extract the output type from a SagaManagementPort */
export type InferSagaManagementPortOutput<T> = [
	T
] extends [
	SagaManagementPort<string, infer TOutput, unknown>
] ? TOutput : NotASagaManagementPortError<T>;
/** Extract the error type from a SagaManagementPort */
export type InferSagaManagementPortError<T> = [
	T
] extends [
	SagaManagementPort<string, unknown, infer TError>
] ? TError : NotASagaManagementPortError<T>;
/** Extract the name literal type from a SagaManagementPort */
export type InferSagaManagementPortName<T> = [
	T
] extends [
	SagaManagementPort<infer TName, unknown, unknown>
] ? TName : NotASagaManagementPortError<T>;
/** Error for singleton saga depending on scoped port */
export type CaptiveSagaDependencyError<TSagaName extends string, TPortName extends string> = {
	readonly __errorBrand: "CaptiveSagaDependencyError";
	readonly __message: "Saga is registered as singleton but depends on a scoped port";
	readonly __received: {
		sagaName: TSagaName;
		portName: TPortName;
	};
	readonly __hint: "Either change the saga adapter to scoped lifetime or ensure all step ports are singleton or transient.";
};
/**
 * Shared Tracing Types
 *
 * Extracted from introspection/types.ts to break the circular dependency
 * between runtime/types.ts and introspection/types.ts.
 *
 * @packageDocumentation
 */
/**
 * Minimal tracer interface for distributed tracing integration.
 *
 * Any tracing adapter (@hex-di/tracing-datadog, @hex-di/tracing-jaeger, etc.)
 * can provide a compatible object without @hex-di/saga depending on those packages.
 */
export interface TracerLike {
	pushSpan(name: string, attributes?: Record<string, string>): void;
	popSpan(status: "ok" | "error"): void;
}
/** Options for creating a SagaTracingHook */
export interface SagaTracingHookOptions {
	readonly tracer: TracerLike;
	readonly filter?: (sagaName: string) => boolean;
	/** Whether to trace compensation-level spans. Defaults to true. */
	readonly traceCompensation?: boolean;
	/** Optional scope ID to include in span attributes. */
	readonly scopeId?: string;
	/** Optional trace context entries to include in span attributes. */
	readonly traceContext?: Record<string, string>;
}
/** Hook for creating distributed tracing spans for saga steps and compensation */
export interface SagaTracingHook {
	onStepStart(sagaName: string, stepName: string, stepIndex: number): void;
	onStepEnd(sagaName: string, ok: boolean): void;
	onCompensationStart(sagaName: string, failedStepName: string): void;
	onCompensationEnd(sagaName: string, ok: boolean): void;
}
export interface SagaEventBase {
	readonly executionId: string;
	readonly sagaName: string;
	readonly timestamp: number;
}
export interface SagaStartedEvent extends SagaEventBase {
	readonly type: "saga:started";
	readonly input: unknown;
	readonly stepCount: number;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface StepStartedEvent extends SagaEventBase {
	readonly type: "step:started";
	readonly stepName: string;
	readonly stepIndex: number;
}
export interface StepCompletedEvent extends SagaEventBase {
	readonly type: "step:completed";
	readonly stepName: string;
	readonly stepIndex: number;
	readonly durationMs: number;
}
export interface StepFailedEvent extends SagaEventBase {
	readonly type: "step:failed";
	readonly stepName: string;
	readonly stepIndex: number;
	readonly error: unknown;
	readonly attemptCount: number;
	readonly retriesExhausted: boolean;
}
export interface StepSkippedEvent extends SagaEventBase {
	readonly type: "step:skipped";
	readonly stepName: string;
	readonly stepIndex: number;
	readonly reason: string;
}
export interface CompensationStartedEvent extends SagaEventBase {
	readonly type: "compensation:started";
	readonly failedStepName: string;
	readonly failedStepIndex: number;
	readonly stepsToCompensate: ReadonlyArray<string>;
}
export interface CompensationStepEvent extends SagaEventBase {
	readonly type: "compensation:step";
	readonly stepName: string;
	readonly stepIndex: number;
	readonly success: boolean;
	readonly error: unknown;
	readonly durationMs: number;
}
export interface CompensationCompletedEvent extends SagaEventBase {
	readonly type: "compensation:completed";
	readonly compensatedSteps: readonly string[];
	readonly totalDurationMs: number;
}
export interface CompensationFailedEvent extends SagaEventBase {
	readonly type: "compensation:failed";
	readonly failedCompensationStep: string;
	readonly error: unknown;
	readonly compensatedSteps: readonly string[];
	readonly remainingSteps: readonly string[];
}
export interface SagaCompletedEvent extends SagaEventBase {
	readonly type: "saga:completed";
	readonly totalDurationMs: number;
	readonly stepsExecuted: number;
	readonly stepsSkipped: number;
}
export interface SagaFailedEvent extends SagaEventBase {
	readonly type: "saga:failed";
	readonly error: unknown;
	readonly compensated: boolean;
	readonly failedStepName: string;
	readonly totalDurationMs: number;
}
export interface SagaCancelledEvent extends SagaEventBase {
	readonly type: "saga:cancelled";
	readonly stepName: string;
	readonly compensated: boolean;
}
export type SagaEvent = SagaStartedEvent | StepStartedEvent | StepCompletedEvent | StepFailedEvent | StepSkippedEvent | CompensationStartedEvent | CompensationStepEvent | CompensationCompletedEvent | CompensationFailedEvent | SagaCompletedEvent | SagaFailedEvent | SagaCancelledEvent;
export type SagaEventListener = (event: SagaEvent) => void;
export type Unsubscribe = () => void;
export type SagaProgressEvent = {
	readonly _tag: "StepStarted";
	readonly stepName: string;
	readonly stepIndex: number;
} | {
	readonly _tag: "StepCompleted";
	readonly stepName: string;
	readonly stepIndex: number;
	readonly totalSteps: number;
} | {
	readonly _tag: "CompensationStarted";
	readonly stepName: string;
} | {
	readonly _tag: "CompensationCompleted";
	readonly stepName: string;
};
export type SagaCompensationEvent = {
	readonly _tag: "CompensationTriggered";
	readonly failedStepName: string;
	readonly stepsToCompensate: number;
} | {
	readonly _tag: "CompensationStepFailed";
	readonly stepName: string;
	readonly cause: unknown;
};
export interface StepTrace {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly status: "completed" | "failed" | "skipped";
	readonly startedAt: number | undefined;
	readonly completedAt: number | undefined;
	readonly durationMs: number | undefined;
	readonly attemptCount: number;
	readonly error: unknown | undefined;
	readonly skippedReason: string | undefined;
}
export interface CompensationStepTrace {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly status: "completed" | "failed";
	readonly startedAt: number;
	readonly completedAt: number;
	readonly durationMs: number;
	readonly error: unknown | undefined;
}
export interface CompensationTrace {
	readonly triggeredBy: string;
	readonly triggeredByIndex: number;
	readonly steps: ReadonlyArray<CompensationStepTrace>;
	readonly status: "completed" | "failed";
	readonly startedAt: number;
	readonly completedAt: number;
	readonly totalDurationMs: number;
}
export interface ExecutionTrace {
	readonly executionId: string;
	readonly sagaName: string;
	readonly input: unknown;
	readonly status: "pending" | "running" | "compensating" | "completed" | "failed" | "cancelled";
	readonly steps: ReadonlyArray<StepTrace>;
	readonly compensation: CompensationTrace | undefined;
	readonly startedAt: number;
	readonly completedAt: number | undefined;
	readonly totalDurationMs: number | undefined;
	readonly metadata: Record<string, unknown> | undefined;
}
export interface ExecuteOptions {
	/** Custom execution ID (default: auto-generated) */
	readonly executionId?: string;
	/** Timeout in ms for the entire execution */
	readonly timeout?: number;
	/** AbortSignal for cancellation */
	readonly signal?: AbortSignal;
	/** Custom metadata attached to this execution */
	readonly metadata?: Record<string, unknown>;
	/** Pre-execution event listeners (captures events from the very start) */
	readonly listeners?: readonly SagaEventListener[];
}
/** Port resolver for the runtime */
export interface PortResolver {
	resolve(portName: string): unknown;
}
/** Configuration for createSagaRunner */
export interface SagaRunnerConfig {
	/** Optional persistence adapter for state checkpointing and resume */
	readonly persister?: SagaPersister;
	/** Optional tracing hook for distributed tracing spans.
	 * Takes precedence over \`tracer\` if both are provided. */
	readonly tracingHook?: SagaTracingHook;
	/**
	 * Shorthand: pass a TracerLike and a SagaTracingHook is auto-created.
	 * Ignored when \`tracingHook\` is already provided.
	 */
	readonly tracer?: TracerLike;
}
/**
 * Internal runner interface with erased types.
 * Use the typed \`executeSaga()\` wrapper for type-safe execution.
 */
export interface SagaRunner {
	execute(saga: AnySagaDefinition, input: unknown, options?: ExecuteOptions): ResultAsync\$1<SagaSuccess<unknown>, SagaError<unknown>>;
	resume(executionId: string): ResultAsync\$1<SagaSuccess<unknown>, SagaError<unknown>>;
	cancel(executionId: string): ResultAsync\$1<void, ManagementError>;
	getStatus(executionId: string): ResultAsync\$1<SagaStatus, ManagementError>;
	subscribe(executionId: string, listener: SagaEventListener): Unsubscribe;
	getTrace(executionId: string): ExecutionTrace | null;
}
/** Structural metadata for a registered saga definition */
export interface SagaDefinitionInfo {
	/** Saga name from defineSaga("name") */
	readonly name: string;
	/** Ordered list of steps with their structural metadata */
	readonly steps: readonly StepDefinitionInfo[];
	/** Saga-level configuration */
	readonly options: {
		readonly compensationStrategy: "sequential" | "parallel" | "best-effort";
		readonly timeout: number | undefined;
		readonly retryPolicy: RetryPolicyInfo | undefined;
	};
	/** All ports that this saga's steps depend on */
	readonly portDependencies: readonly string[];
}
/** Structural metadata for a step within a saga definition */
export interface StepDefinitionInfo {
	/** Step name from defineStep("name") */
	readonly name: string;
	/** Port name this step invokes */
	readonly port: string;
	/** Whether a compensation handler is defined for this step */
	readonly hasCompensation: boolean;
	/** Whether this step has a condition (may be skipped at runtime) */
	readonly isConditional: boolean;
	/** Step-level retry policy, if any */
	readonly retryPolicy: RetryPolicyInfo | undefined;
	/** Step-level timeout, if any */
	readonly timeout: number | undefined;
}
/** Retry policy information for display/diagnostics */
export interface RetryPolicyInfo {
	readonly maxAttempts: number;
	readonly backoffStrategy: "fixed" | "exponential" | "linear";
	readonly initialDelay: number;
}
/**
 * Extended execution summary for introspection.
 *
 * This is the rich version used by the SagaInspector, distinct from
 * the simpler SagaExecutionSummary in ports/types.ts.
 */
export interface InspectorSagaExecutionSummary {
	readonly executionId: string;
	readonly sagaName: string;
	readonly status: SagaStatusType;
	readonly currentStepName: string | null;
	readonly currentStepIndex: number;
	readonly totalSteps: number;
	readonly completedStepCount: number;
	readonly startedAt: string;
	readonly updatedAt: string;
	readonly completedAt: string | null;
	readonly durationMs: number | null;
	readonly error: {
		readonly _tag: string;
		readonly stepName: string;
		readonly causeTags: readonly string[];
	} | null;
	readonly compensationState: {
		readonly active: boolean;
		readonly compensatedSteps: readonly string[];
		readonly failedSteps: readonly string[];
	};
	readonly metadata: Record<string, unknown>;
}
/** Aggregated compensation metrics across all saga executions */
export interface CompensationStats {
	/** Total number of compensation events triggered */
	readonly totalCompensations: number;
	/** Compensations that completed all steps successfully */
	readonly successfulCompensations: number;
	/** Compensations where one or more steps failed */
	readonly failedCompensations: number;
	/** Average time (ms) to complete a full compensation chain */
	readonly averageCompensationTime: number;
	/** Saga definition with the most compensation events */
	readonly mostCompensatedSaga: string | null;
	/** Per-saga breakdown */
	readonly bySaga: readonly SagaCompensationBreakdown[];
}
/** Per-saga compensation breakdown */
export interface SagaCompensationBreakdown {
	readonly sagaName: string;
	readonly totalCompensations: number;
	readonly successRate: number;
	readonly averageCompensationTime: number;
	readonly mostFailedStep: string | null;
	/** Distribution of error _tag values across compensations for this saga */
	readonly errorTagDistribution: Readonly<Record<string, number>>;
}
/** Suggestion types aligned with GraphSuggestion type union */
export type SagaSuggestionType = "saga_step_without_compensation" | "saga_long_timeout_without_persistence" | "saga_no_retry_on_external_port" | "saga_singleton_with_scoped_deps";
/** MAPE-K suggestion for saga definition improvement */
export interface SagaSuggestion {
	readonly type: SagaSuggestionType;
	readonly sagaName: string;
	readonly stepName?: string;
	readonly message: string;
	readonly action: string;
}
/** Pull-based + push-based introspection API for saga state */
export interface SagaInspector {
	/** List all registered saga definitions with their step topology */
	getDefinitions(): readonly SagaDefinitionInfo[];
	/** Get all currently active (pending, running, compensating) executions */
	getActiveExecutions(): readonly InspectorSagaExecutionSummary[];
	/** Get execution history with optional filters (delegates to SagaPersister.list) */
	getHistory(filters?: PersisterFilters): ResultAsync\$1<readonly InspectorSagaExecutionSummary[], PersistenceError>;
	/** Get the detailed execution trace for a specific execution */
	getTrace(executionId: string): ExecutionTrace | null;
	/** Get aggregated compensation statistics */
	getCompensationStats(): CompensationStats;
	/** Get actionable suggestions for improving saga definitions */
	getSuggestions(): readonly SagaSuggestion[];
	/** Subscribe to saga lifecycle events across all executions */
	subscribe(listener: SagaEventListener): Unsubscribe;
}
/** Entry representing a live saga execution in the registry */
export interface SagaRegistryEntry {
	readonly sagaName: string;
	readonly executionId: string;
	readonly status: () => SagaStatusType;
	readonly currentStep: () => number;
	readonly trace: () => ExecutionTrace;
	readonly startedAt: number;
}
/** Event emitted by the SagaRegistry when executions are registered/unregistered */
export type SagaRegistryEvent = {
	readonly type: "execution-registered";
	readonly entry: SagaRegistryEntry;
} | {
	readonly type: "execution-unregistered";
	readonly executionId: string;
};
/** Listener callback for registry events */
export type SagaRegistryListener = (event: SagaRegistryEvent) => void;
/** Registry for tracking live saga executions */
export interface SagaRegistry {
	register(entry: SagaRegistryEntry): void;
	unregister(executionId: string): void;
	getAllExecutions(): readonly SagaRegistryEntry[];
	getExecution(executionId: string): SagaRegistryEntry | undefined;
	getExecutionsBySaga(sagaName: string): readonly SagaRegistryEntry[];
	getExecutionsByStatus(status: SagaStatusType): readonly SagaRegistryEntry[];
	subscribe(listener: SagaRegistryListener): Unsubscribe;
	dispose(): void;
}
/**
 * Creates a SagaPort token for domain-level saga execution.
 *
 * Uses the curried pattern: sagaPort<TInput, TOutput, TError>()({ name })
 * This preserves literal name inference from the config.
 *
 * @example
 * \`\`\`typescript
 * const OrderSagaPort = sagaPort<OrderInput, OrderOutput, OrderErrors>()({
 *   name: "OrderSaga",
 *   description: "Processes order checkout",
 * });
 * \`\`\`
 */
export declare function sagaPort<TInput, TOutput, TError = never>(): <const TName extends string>(config: SagaPortConfig<TName>) => SagaPort<TName, TInput, TOutput, TError>;
/**
 * Creates a SagaManagementPort for operational control of saga executions.
 *
 * @example
 * \`\`\`typescript
 * const OrderSagaManagementPort = sagaManagementPort<OrderOutput, OrderErrors>()({
 *   name: "OrderSagaManagement",
 * });
 * \`\`\`
 */
export declare function sagaManagementPort<TOutput, TError = never>(): <const TName extends string>(config: SagaPortConfig<TName>) => SagaManagementPort<TName, TOutput, TError>;
/**
 * Pre-defined port for the saga persistence adapter.
 */
export declare const SagaPersisterPort: DirectedPort<"SagaPersister", SagaPersister, "outbound", string>;
/**
 * Pre-defined port for the saga registry (live execution tracking).
 */
export declare const SagaRegistryPort: DirectedPort<"SagaRegistry", SagaRegistry, "outbound", string>;
/**
 * Pre-defined port for the saga inspector (introspection API).
 */
export declare const SagaInspectorPort: DirectedPort<"SagaInspector", SagaInspector, "outbound", string>;
/**
 * Runtime type guard that narrows a value to SagaPort.
 *
 * Checks both the \`__portName\` property (from createPort) and the
 * runtime kind symbol injected by brandAsSagaPort.
 */
export declare function isSagaPort(value: unknown): value is SagaPort<string, unknown, unknown, unknown>;
/**
 * Runtime type guard that narrows a value to SagaManagementPort.
 *
 * Checks both the \`__portName\` property (from createPort) and the
 * runtime kind symbol injected by brandAsSagaManagementPort.
 */
export declare function isSagaManagementPort(value: unknown): value is SagaManagementPort<string, unknown, unknown>;
export interface SagaAdapterConfig<TRequires extends readonly unknown[] = readonly [
]> {
	/** The saga definition to execute */
	readonly saga: AnySagaDefinition;
	/** Required ports that the saga's steps depend on */
	readonly requires?: TRequires;
	/** Adapter lifetime (default: "scoped") */
	readonly lifetime?: "singleton" | "scoped" | "transient";
}
export interface SagaAdapter<TPort extends SagaPort<string, unknown, unknown, unknown>> {
	readonly port: TPort;
	readonly saga: AnySagaDefinition;
	readonly requires: readonly unknown[];
	readonly lifetime: "singleton" | "scoped" | "transient";
}
/**
 * Creates a saga adapter that binds a saga definition to a SagaPort.
 *
 * @param port - The SagaPort this adapter satisfies
 * @param config - Configuration with the saga definition and dependencies
 * @returns A frozen SagaAdapter object
 *
 * @example
 * \`\`\`typescript
 * const OrderSagaAdapter = createSagaAdapter(OrderSagaPort, {
 *   saga: OrderSaga,
 *   requires: [InventoryPort, PaymentPort, ShippingPort],
 *   lifetime: "scoped",
 * });
 * \`\`\`
 */
export declare function createSagaAdapter<TPort extends SagaPort<string, unknown, unknown, unknown>, TRequires extends readonly unknown[] = readonly [
]>(port: TPort, config: SagaAdapterConfig<TRequires>): SagaAdapter<TPort>;
export type CompensationStrategy = "sequential" | "parallel" | "best-effort";
export interface CompensationResult {
	/** Names of steps that were successfully compensated */
	readonly compensatedSteps: readonly string[];
	/** Names of steps whose compensation failed */
	readonly failedSteps: readonly string[];
	/** Errors from failed compensation handlers */
	readonly errors: readonly CompensationStepError[];
	/** Whether all compensations succeeded */
	readonly allSucceeded: boolean;
}
export interface CompensationStepError {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly cause: unknown;
}
export interface CompensationPlan {
	/** Steps to compensate, in the order they completed (will be reversed for execution) */
	readonly completedSteps: readonly CompensationPlanStep[];
	/** Strategy to use for compensation */
	readonly strategy: CompensationStrategy;
}
export interface CompensationPlanStep {
	readonly stepName: string;
	readonly stepIndex: number;
	readonly result: unknown;
	readonly compensateFn: (ctx: CompensationContext<unknown, unknown, unknown, unknown>) => unknown;
}
/** Callback to resolve a port and invoke the compensation action */
export type CompensationInvoker = (step: CompensationPlanStep, params: unknown) => ResultAsync\$1<unknown, unknown>;
export interface CompensationEngineInput {
	readonly plan: {
		readonly completedSteps: readonly CompensationPlanStep[];
		readonly strategy: "sequential" | "parallel" | "best-effort";
	};
	readonly invoker: CompensationInvoker;
	readonly sagaInput: unknown;
	readonly accumulatedResults: Record<string, unknown>;
	readonly originalError: unknown;
	readonly failedStepIndex: number;
	readonly failedStepName: string;
	readonly executionId: string;
	readonly sagaName: string;
	readonly emitEvent?: (event: SagaEvent) => void;
}
/**
 * Execute a compensation plan using the specified strategy.
 *
 * @param input - All context needed for the compensation execution
 * @returns The compensation result with status of each step
 */
export declare function executeCompensation(input: CompensationEngineInput): Promise<CompensationResult>;
/**
 * Creates a SagaRunner that executes saga definitions.
 *
 * @param resolver - Port resolver (typically wraps a container)
 * @param config - Optional configuration (persister for resume support)
 * @returns A SagaRunner instance
 */
export declare function createSagaRunner(resolver: PortResolver, config?: SagaRunnerConfig): SagaRunner;
/**
 * Type-safe saga execution helper.
 *
 * Provides full generic type inference for saga input/output/error types
 * while delegating to the type-erased SagaRunner. This is the primary
 * entry point for executing sagas with typed results.
 *
 * @example
 * \`\`\`typescript
 * const result = await executeSaga(runner, OrderSaga, orderInput);
 * // result: Result<SagaSuccess<OrderOutput>, SagaError<OrderErrors>>
 * \`\`\`
 */
export declare function executeSaga<TSaga extends AnySagaDefinition>(runner: SagaRunner, saga: TSaga, input: InferSagaInput<TSaga>, options?: ExecuteOptions): ResultAsync\$1<SagaSuccess<InferSagaOutput<TSaga>>, SagaError<InferSagaErrors<TSaga>>>;
/**
 * Execution ID Generator
 *
 * Simple unique ID generation for saga executions.
 *
 * @packageDocumentation
 */
/**
 * Generate a unique execution ID.
 * Uses a combination of timestamp and counter for uniqueness.
 */
export declare function generateExecutionId(): string;
/**
 * Creates a SagaExecutor<TInput, TOutput, TError> that wraps a SagaRunner
 * with a specific saga definition. This is the service that resolves from a SagaPort.
 *
 * The type-erasure boundary cast from \`SagaRunner.execute()\` (which uses \`unknown\`)
 * to the typed executor is safe because the runtime produces values matching
 * the saga definition's generic types.
 */
export declare function createSagaExecutor<TInput, TOutput, TError>(runner: SagaRunner, saga: AnySagaDefinition, defaultOptions?: Partial<ExecuteOptions>): SagaExecutor<TInput, TOutput, TError>;
/**
 * Creates a SagaManagementExecutor<TOutput, TError> that wraps a SagaRunner
 * with management operations. This is the service that resolves from a SagaManagementPort.
 *
 * @param runner - The saga runner instance
 * @param persister - Optional persistence adapter for listExecutions support
 */
export declare function createSagaManagementExecutor<TOutput, TError>(runner: SagaRunner, persister?: SagaPersister): SagaManagementExecutor<TOutput, TError>;
/**
 * Creates a LibraryInspector that bridges SagaInspector
 * into the container's unified Library Inspector Protocol.
 *
 * The returned inspector:
 * - Reports \`name: "saga"\`
 * - Exposes definitions, active executions, compensation stats, and suggestions via \`getSnapshot()\`
 * - Forwards saga lifecycle events to subscribers as LibraryEvents
 * - \`dispose()\` is a no-op (SagaInspector has no cleanup)
 *
 * @param inspector - The SagaInspector instance to bridge
 * @returns A LibraryInspector for the saga library
 *
 * @example
 * \`\`\`typescript
 * const libraryInspector = createSagaLibraryInspector(sagaInspector);
 * container.inspector.registerLibrary(libraryInspector);
 *
 * const snapshot = libraryInspector.getSnapshot();
 * // { definitions: [...], activeExecutions: [...], compensationStats: {...}, suggestions: [...] }
 * \`\`\`
 */
export declare function createSagaLibraryInspector(inspector: SagaInspector): LibraryInspector;
/**
 * Configuration for creating a SagaInspector adapter.
 */
export interface SagaInspectorAdapterConfig {
	/** Registered saga definitions for introspection. */
	readonly definitions: readonly AnySagaDefinition[];
	/** Optional persister for historical execution queries. */
	readonly persister?: SagaPersister;
	/** Optional active traces for live execution tracking. */
	readonly activeTraces?: Readonly<Record<string, ExecutionTrace>>;
}
/**
 * The adapter type for SagaInspectorAdapter.
 */
export type SagaInspectorAdapterType = Adapter<typeof SagaInspectorPort, typeof SagaRegistryPort, "singleton", "sync", false, readonly [
	typeof SagaRegistryPort
]>;
/**
 * Creates a DI Adapter that provides a SagaInspector singleton.
 *
 * The SagaInspector requires a SagaRegistry (resolved from the container)
 * and saga definitions (provided in the config) for introspection.
 *
 * @param config - Configuration with definitions and optional persister/traces
 * @returns A frozen adapter for SagaInspectorPort
 *
 * @example
 * \`\`\`typescript
 * const SagaInspectorAdapter = createSagaInspectorAdapter({
 *   definitions: [orderSaga, paymentSaga],
 *   persister: myPersister,
 * });
 *
 * const graph = GraphBuilder.create()
 *   .provide(SagaRegistryAdapter)
 *   .provide(SagaInspectorAdapter)
 *   .build();
 *
 * const inspector = container.resolve(SagaInspectorPort);
 * const defs = inspector.getDefinitions();
 * \`\`\`
 */
export declare function createSagaInspectorAdapter(config: SagaInspectorAdapterConfig): SagaInspectorAdapterType;
/**
 * DI Adapter that provides a SagaRegistry singleton.
 *
 * Register this adapter in a GraphBuilder to make SagaRegistryPort resolvable:
 *
 * @example
 * \`\`\`typescript
 * const graph = GraphBuilder.create()
 *   .provide(SagaRegistryAdapter)
 *   .build();
 *
 * const registry = container.resolve(SagaRegistryPort);
 * const executions = registry.getAllExecutions();
 * \`\`\`
 */
export type SagaRegistryAdapterType = Adapter<typeof SagaRegistryPort, never, "singleton", "sync", false, readonly [
]>;
export declare const SagaRegistryAdapter: SagaRegistryAdapterType;
/**
 * Saga Library Inspector Port
 *
 * Port token for the saga library inspector bridge, enabling auto-registration
 * with the container's unified inspection protocol.
 *
 * @packageDocumentation
 */
/**
 * DI Port for resolving a SagaLibraryInspector from the container.
 *
 * When used with a graph, this provides a LibraryInspector bridge that
 * integrates saga inspection into the container's unified
 * Library Inspector Protocol.
 */
export declare const SagaLibraryInspectorPort: DirectedPort<"SagaLibraryInspector", LibraryInspector, "outbound", "library-inspector">;
/**
 * Pre-built frozen adapter for SagaLibraryInspectorPort.
 *
 * Depends on SagaInspectorPort and produces a LibraryInspector bridge
 * via createSagaLibraryInspector. Because SagaLibraryInspectorPort
 * has \`category: "library-inspector"\`, the container's afterResolve hook
 * will auto-register it with the unified inspection protocol.
 */
export type SagaLibraryInspectorAdapterType = Adapter<typeof SagaLibraryInspectorPort, typeof SagaInspectorPort, "singleton", "sync", false, readonly [
	typeof SagaInspectorPort
]>;
export declare const SagaLibraryInspectorAdapter: SagaLibraryInspectorAdapterType;
export interface SagaInspectorConfig {
	/** Registered saga definitions */
	readonly definitions: readonly AnySagaDefinition[];
	/** Persister for execution history (optional) */
	readonly persister?: SagaPersister;
	/** Active execution traces tracked by the runner */
	readonly activeTraces?: Readonly<Record<string, ExecutionTrace>>;
}
export declare function createSagaInspector(config: SagaInspectorConfig): SagaInspector;
/**
 * Emit a saga event to all inspector subscribers.
 *
 * Called by the integration layer to bridge runner events
 * to inspector subscriptions.
 */
export declare function emitToInspector(inspector: SagaInspector, event: SagaEvent): void;
/**
 * Creates a SagaRegistry instance for tracking live saga executions.
 *
 * @returns A new SagaRegistry
 */
export declare function createSagaRegistry(): SagaRegistry;
/**
 * Creates a SagaTracingHook instance for distributed tracing integration.
 *
 * @param options - Hook configuration with tracer, optional filter, and traceCompensation flag
 * @returns A new SagaTracingHook
 */
export declare function createSagaTracingHook(options: SagaTracingHookOptions): SagaTracingHook;
/**
 * Creates an in-memory SagaPersister backed by a Map for O(1) lookup.
 *
 * Uses structuredClone on read/write to prevent external mutation of
 * internal state, mirroring the isolation guarantees of a real database.
 */
export declare function createInMemoryPersister(): SagaPersister;
export interface SagaErrorBaseInput {
	readonly executionId: string;
	readonly sagaName: string;
	readonly stepName: string;
	readonly stepIndex: number;
	readonly message: string;
	readonly completedSteps: readonly string[];
	readonly compensatedSteps: readonly string[];
}
export declare function createStepFailedError<TCause>(base: SagaErrorBaseInput, cause: TCause): StepFailedError<TCause>;
export declare function createCompensationFailedError<TCause>(base: SagaErrorBaseInput, cause: TCause, compensationCause: unknown, failedCompensationSteps: readonly string[]): CompensationFailedError<TCause>;
export declare function createTimeoutError(base: SagaErrorBaseInput, timeoutMs: number): TimeoutError;
export declare function createCancelledError(base: SagaErrorBaseInput): CancelledError;
export declare function createValidationFailedError(base: SagaErrorBaseInput, cause: unknown): ValidationFailedError;
export declare function createPortNotFoundError(base: SagaErrorBaseInput, portName: string): PortNotFoundError;
export declare function createPersistenceFailedError(base: SagaErrorBaseInput, operation: "save" | "load" | "delete" | "update", cause: unknown): PersistenceFailedError;

export {};
}`;
