// Auto-generated by scripts/bundle-playground-types.ts
// Package: @hex-di/store
export const dts = `declare module "@hex-di/store" {
/**
 * DeepReadonly Type Utility
 *
 * Recursively makes all properties readonly. Functions are preserved as-is.
 *
 * @packageDocumentation
 */
/**
 * Recursively makes all properties of T readonly.
 *
 * - Functions are preserved as-is (no readonly on function properties)
 * - Maps become ReadonlyMaps
 * - Sets become ReadonlySets
 * - Arrays become readonly arrays
 * - Objects have all properties made readonly recursively
 * - Primitives pass through unchanged
 */
export type DeepReadonly<T> = T extends (...args: never[]) => unknown ? T : T extends ReadonlyMap<infer K, infer V> ? ReadonlyMap<K, DeepReadonly<V>> : T extends ReadonlySet<infer U> ? ReadonlySet<DeepReadonly<U>> : T extends readonly (infer U)[] ? readonly DeepReadonly<U>[] : T extends object ? {
	readonly [K in keyof T]: DeepReadonly<T[K]>;
} : T;
declare const __noPayload: unique symbol;
/**
 * Branded sentinel type for no-payload actions.
 *
 * Used as default for ActionReducer TPayload to avoid the
 * \`undefined extends void\` ambiguity in TypeScript.
 * End users never interact with this type directly.
 */
export type NoPayload = {
	readonly __noPayload: true;
};
/**
 * A reducer function that transforms state.
 *
 * When TPayload is NoPayload (default), the reducer takes only state.
 * When TPayload is provided, the reducer takes state and payload.
 *
 * Uses \`[TPayload] extends [NoPayload]\` distribution guard to prevent
 * union distribution AND the void/undefined ambiguity.
 */
export type ActionReducer<TState, TPayload = NoPayload> = [
	TPayload
] extends [
	NoPayload
] ? (state: TState) => TState : (state: TState, payload: TPayload) => TState;
/**
 * A record mapping action names to reducer functions.
 *
 * Uses \`never[]\` rest params to allow actions with specific payload
 * types (e.g., \`number\`) to satisfy the constraint without
 * contravariance issues. Any function \`(state) => state\` or
 * \`(state, payload: P) => state\` satisfies \`(state, ...never[]) => state\`.
 */
export type ActionMap<TState> = Record<string, (state: TState, ...args: never[]) => TState>;
/**
 * Converts action reducers to callable bound actions.
 *
 * The state parameter is removed -- only the payload remains.
 * No-payload reducers become \`() => void\`.
 * Payload reducers become \`(payload: P) => void\`.
 */
export type BoundActions<TState, TActions extends ActionMap<TState>> = {
	readonly [K in keyof TActions]: TActions[K] extends (state: TState) => TState ? () => void : TActions[K] extends (state: TState, payload: infer P) => TState ? (payload: P) => void : never;
};
/** Unsubscribe function returned by subscribe calls */
export type Unsubscribe = () => void;
/** Listener for full state changes */
export type StateListener<TState> = (state: DeepReadonly<TState>, prev: DeepReadonly<TState>) => void;
/**
 * Service interface for state ports.
 *
 * Provides reactive state access, bound actions, and subscriptions.
 * The \`actions\` object and each bound action function are referentially
 * stable for the lifetime of the service instance.
 */
export interface StateService<TState, TActions extends ActionMap<TState>> {
	/** Current state snapshot (deeply frozen, immutable) */
	readonly state: DeepReadonly<TState>;
	/**
	 * Type-safe bound actions.
	 * Referentially stable for the lifetime of the service instance.
	 */
	readonly actions: BoundActions<TState, TActions>;
	/** Whether this service has been disposed. */
	readonly isDisposed: boolean;
	/** Subscribe to all state changes */
	subscribe(listener: StateListener<TState>): Unsubscribe;
	/** Subscribe to a selected slice with optional equality function */
	subscribe<TSelected>(selector: (state: DeepReadonly<TState>) => TSelected, listener: (value: TSelected, prev: TSelected) => void, equalityFn?: (a: TSelected, b: TSelected) => boolean): Unsubscribe;
}
/**
 * Service interface for atom ports.
 *
 * Simple reactive values with get/set/update. No actions.
 * \`set\` and \`update\` functions are referentially stable.
 */
export interface AtomService<TValue> {
	/** Current value (deeply frozen) */
	readonly value: DeepReadonly<TValue>;
	/** Whether this service has been disposed. */
	readonly isDisposed: boolean;
	/** Replace the value. Referentially stable. */
	set(value: TValue): void;
	/** Update the value with a function. Referentially stable. */
	update(fn: (current: TValue) => TValue): void;
	/** Subscribe to value changes */
	subscribe(listener: (value: DeepReadonly<TValue>, prev: DeepReadonly<TValue>) => void): Unsubscribe;
}
/**
 * Service interface for derived ports.
 *
 * Read-only computed values derived from other state.
 */
export interface DerivedService<TResult> {
	/** Current computed value (deeply frozen) */
	readonly value: DeepReadonly<TResult>;
	/** Whether this service has been disposed. */
	readonly isDisposed: boolean;
	/** Subscribe to recomputation */
	subscribe(listener: (value: DeepReadonly<TResult>, prev: DeepReadonly<TResult>) => void): Unsubscribe;
}
/**
 * Discriminated union snapshot for async derived services.
 *
 * Each variant narrows the available fields based on status.
 * When E is never (default), the error variant uses unknown.
 */
export type AsyncDerivedSnapshot<TResult, E = never> = {
	readonly status: "idle";
	readonly data: undefined;
	readonly error: undefined;
	readonly isLoading: false;
} | {
	readonly status: "loading";
	readonly data: DeepReadonly<TResult> | undefined;
	readonly error: undefined;
	readonly isLoading: true;
} | {
	readonly status: "success";
	readonly data: DeepReadonly<TResult>;
	readonly error: undefined;
	readonly isLoading: false;
} | {
	readonly status: "error";
	readonly data: undefined;
	readonly error: [
		E
	] extends [
		never
	] ? unknown : E;
	readonly isLoading: false;
};
/**
 * Service interface for async derived ports.
 *
 * Computed values from async operations (API calls, lazy imports).
 * \`refresh\` is referentially stable.
 */
export interface AsyncDerivedService<TResult, E = never> {
	/** Current snapshot as a discriminated union */
	readonly snapshot: AsyncDerivedSnapshot<TResult, E>;
	/** Convenience: current status */
	readonly status: AsyncDerivedSnapshot<TResult, E>["status"];
	/** Convenience flag: true when status is "loading" */
	readonly isLoading: boolean;
	/** Whether this service has been disposed. */
	readonly isDisposed: boolean;
	/** Trigger a re-fetch. Referentially stable. */
	refresh(): void;
	/** Subscribe to status/data/error changes */
	subscribe(listener: (snapshot: AsyncDerivedSnapshot<TResult, E>) => void): Unsubscribe;
}
/**
 * Service interface for bidirectional derived ports.
 *
 * Extends DerivedService with a write-back capability.
 * \`set\` is referentially stable.
 */
export interface LinkedDerivedService<TResult> extends DerivedService<TResult> {
	/** Write back to source state. Referentially stable. */
	set(value: TResult): void;
}
/**
 * Tagged Union Error Types for @hex-di/store.
 *
 * All store errors are frozen plain objects with a \`_tag\` discriminant
 * for exhaustive pattern matching via \`switch\`/\`match\`.
 *
 * @packageDocumentation
 */
export declare const DisposedStateAccess: (fields: {
	readonly portName: string;
	readonly containerName: string;
	readonly operation: "state" | "value" | "actions" | "subscribe" | "set" | "update" | "refresh";
}) => DisposedStateAccess;
export type DisposedStateAccess = Readonly<{
	_tag: "DisposedStateAccess";
	portName: string;
	containerName: string;
	operation: "state" | "value" | "actions" | "subscribe" | "set" | "update" | "refresh";
	code: "DISPOSED_STATE_ACCESS";
	isProgrammingError: true;
	message: string;
}>;
export declare const DerivedComputationFailed: (fields: {
	readonly portName: string;
	readonly cause: unknown;
}) => DerivedComputationFailed;
export type DerivedComputationFailed = Readonly<{
	_tag: "DerivedComputationFailed";
	portName: string;
	cause: unknown;
	code: "DERIVED_COMPUTATION_FAILED";
	isProgrammingError: false;
	message: string;
}>;
export declare const AsyncDerivedExhausted: (fields: {
	readonly portName: string;
	readonly attempts: number;
	readonly cause: unknown;
}) => AsyncDerivedExhausted;
export type AsyncDerivedExhausted = Readonly<{
	_tag: "AsyncDerivedExhausted";
	portName: string;
	attempts: number;
	cause: unknown;
	code: "ASYNC_DERIVED_EXHAUSTED";
	isProgrammingError: true;
	message: string;
}>;
export declare const CircularDerivedDependency: (fields: {
	readonly dependencyChain: readonly string[];
}) => CircularDerivedDependency;
export type CircularDerivedDependency = Readonly<{
	_tag: "CircularDerivedDependency";
	dependencyChain: readonly string[];
	code: "CIRCULAR_DERIVED_DEPENDENCY";
	isProgrammingError: true;
	message: string;
}>;
export declare const BatchExecutionFailed: (fields: {
	readonly cause: unknown;
}) => BatchExecutionFailed;
export type BatchExecutionFailed = Readonly<{
	_tag: "BatchExecutionFailed";
	cause: unknown;
	code: "BATCH_EXECUTION_FAILED";
	isProgrammingError: false;
	message: string;
}>;
export declare const WaitForStateTimeout: (fields: {
	readonly portName: string;
	readonly timeoutMs: number;
}) => WaitForStateTimeout;
export type WaitForStateTimeout = Readonly<{
	_tag: "WaitForStateTimeout";
	portName: string;
	timeoutMs: number;
	code: "WAIT_FOR_STATE_TIMEOUT";
	isProgrammingError: false;
	message: string;
}>;
export declare const InvalidComputedGetter: () => InvalidComputedGetter;
export type InvalidComputedGetter = Readonly<{
	_tag: "InvalidComputedGetter";
	code: "INVALID_COMPUTED_GETTER";
	isProgrammingError: true;
	message: string;
}>;
/**
 * Produced when a state adapter effect returns Err.
 * Wraps the original error with action context for diagnostics.
 */
export declare const EffectFailedError: <Fields extends Record<string, unknown>>(fields: Fields) => Readonly<{
	_tag: "EffectFailed";
} & Fields>;
export type EffectFailedError = Readonly<{
	_tag: "EffectFailed";
	portName: string;
	actionName: string;
	cause: unknown;
}>;
/**
 * Produced when an async derived adapter's select returns Err after all retries.
 */
export declare const AsyncDerivedSelectError: <Fields extends Record<string, unknown>>(fields: Fields) => Readonly<{
	_tag: "AsyncDerivedSelectFailed";
} & Fields>;
export type AsyncDerivedSelectError = Readonly<{
	_tag: "AsyncDerivedSelectFailed";
	portName: string;
	attempts: number;
	cause: unknown;
}>;
/**
 * Convention type for hydrator adapter implementations.
 * The store runtime does not produce this -- user-written hydrator adapters construct it.
 */
export declare const HydrationError: <Fields extends Record<string, unknown>>(fields: Fields) => Readonly<{
	_tag: "HydrationFailed";
} & Fields>;
export type HydrationError = Readonly<{
	_tag: "HydrationFailed";
	portName: string;
	cause: unknown;
}>;
/**
 * Produced when an effect adapter's onAction callback throws.
 * Wraps the original error for diagnostics.
 */
export declare const EffectAdapterError: <Fields extends Record<string, unknown>>(fields: Fields) => Readonly<{
	_tag: "EffectAdapterFailed";
} & Fields>;
export type EffectAdapterError = Readonly<{
	_tag: "EffectAdapterFailed";
	cause: unknown;
}>;
/**
 * Produced when an onEffectError handler itself throws.
 * Both the original effect error and the handler error are captured.
 */
export declare const EffectErrorHandlerError: <Fields extends Record<string, unknown>>(fields: Fields) => Readonly<{
	_tag: "EffectErrorHandlerFailed";
} & Fields>;
export type EffectErrorHandlerError = Readonly<{
	_tag: "EffectErrorHandlerFailed";
	portName: string;
	actionName: string;
	originalError: EffectFailedError;
	handlerError: unknown;
}>;
/**
 * Union of all thrown store errors.
 */
export type StoreError = DisposedStateAccess | DerivedComputationFailed | AsyncDerivedExhausted | CircularDerivedDependency | BatchExecutionFailed | WaitForStateTimeout | InvalidComputedGetter;
/**
 * Union of store errors where isProgrammingError is true.
 */
export type StoreProgrammingError = DisposedStateAccess | AsyncDerivedExhausted | CircularDerivedDependency | InvalidComputedGetter;
declare const RESULT_BRAND: unique symbol;
declare const OPTION_BRAND: unique symbol;
/**
 * The presence variant of \`Option\`. Represents a value that exists.
 *
 * \`Some<T>\` carries a \`value\` of type \`T\` and provides transformation,
 * chaining, extraction, and conversion methods. Instances are created
 * via the \`some()\` factory and are frozen plain objects branded with \`OPTION_BRAND\`.
 *
 * @example
 * \`\`\`ts
 * import { some } from '@hex-di/result';
 *
 * const opt = some(42);
 * opt.isSome();      // true
 * opt.map(x => x * 2); // Some(84)
 * opt.unwrapOr(0);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-002
 */
export interface Some<T> {
	readonly _tag: "Some";
	readonly value: T;
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<T>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: T) => boolean): boolean;
	map<U>(f: (value: T) => U): Some<U>;
	filter(predicate: (value: T) => boolean): Option\$1<T>;
	flatten<U>(this: Some<Option\$1<U>>): Option\$1<U>;
	zip<U>(other: Option\$1<U>): Option\$1<[
		T,
		U
	]>;
	zipWith<U, R>(other: Option\$1<U>, f: (a: T, b: U) => R): Option\$1<R>;
	andThen<U>(f: (value: T) => Option\$1<U>): Option\$1<U>;
	orElse(f: () => Option\$1<T>): Some<T>;
	match<A, B>(onSome: (value: T) => A, onNone: () => B): A;
	unwrapOr<U>(defaultValue: U): T;
	expect(message: string): T;
	toResult<E>(onNone: () => E): Ok<T, E>;
	toNullable(): T;
	toUndefined(): T;
	toJSON(): {
		_tag: "Some";
		_schemaVersion: 1;
		value: T;
	};
	transpose<U, E>(this: Some<Result<U, E>>): Result<Some<U>, E>;
}
/**
 * The absence variant of \`Option\`. Represents the lack of a value.
 *
 * \`None\` carries no value and short-circuits all transformations and chaining operations.
 * Extraction methods return defaults or throw. A single frozen singleton is reused
 * for all \`none()\` calls.
 *
 * @example
 * \`\`\`ts
 * import { none } from '@hex-di/result';
 *
 * const opt = none();
 * opt.isNone();      // true
 * opt.map(x => x * 2); // None
 * opt.unwrapOr(0);   // 0
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/behaviors/09-option.md — BEH-09-003
 */
export interface None {
	readonly _tag: "None";
	readonly [OPTION_BRAND]: true;
	isSome(): this is Some<never>;
	isNone(): this is None;
	isSomeAnd(predicate: (value: never) => boolean): boolean;
	map<U>(f: (value: never) => U): None;
	filter(predicate: (value: never) => boolean): None;
	flatten(): None;
	zip<U>(other: Option\$1<U>): None;
	zipWith<U, R>(other: Option\$1<U>, f: (a: never, b: U) => R): None;
	andThen<U>(f: (value: never) => Option\$1<U>): None;
	orElse<T>(f: () => Option\$1<T>): Option\$1<T>;
	match<A, B>(onSome: (value: never) => A, onNone: () => B): B;
	unwrapOr<U>(defaultValue: U): U;
	expect(message: string): never;
	toResult<E>(onNone: () => E): Err<never, E>;
	toNullable(): null;
	toUndefined(): undefined;
	toJSON(): {
		_tag: "None";
		_schemaVersion: 1;
	};
	transpose(): Ok<None, never>;
}
type Option\$1<T> = Some<T> | None;
export interface ResultAsync<T, E> extends PromiseLike<Result<T, E>> {
	map<U>(f: (value: T) => U | Promise<U>): ResultAsync<U, E>;
	mapErr<F>(f: (error: E) => F | Promise<F>): ResultAsync<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U | Promise<U>, onErr: (error: E) => F | Promise<F>): ResultAsync<U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F> | ResultAsync<U, F>): ResultAsync<T | U, F>;
	andTee(f: (value: T) => void | Promise<void>): ResultAsync<T, E>;
	orTee(f: (error: E) => void | Promise<void>): ResultAsync<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F> | ResultAsync<unknown, F>): ResultAsync<T, E | F>;
	inspect(f: (value: T) => void): ResultAsync<T, E>;
	inspectErr(f: (error: E) => void): ResultAsync<T, E>;
	match<A, B>(onOk: (value: T) => A | Promise<A>, onErr: (error: E) => B | Promise<B>): Promise<A | B>;
	unwrapOr<U>(defaultValue: U): Promise<T | U>;
	unwrapOrElse<U>(f: (error: E) => U): Promise<T | U>;
	orDie(): Promise<T>;
	toNullable(): Promise<T | null>;
	toUndefined(): Promise<T | undefined>;
	intoTuple(): Promise<[
		null,
		T
	] | [
		E,
		null
	]>;
	merge(): Promise<T | E>;
	flatten<U>(this: ResultAsync<Result<U, E>, E>): ResultAsync<U, E>;
	flip(): ResultAsync<E, T>;
	toJSON(): Promise<{
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	} | {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	}>;
}
/**
 * The success variant of {@link Result}. Contains a \`value\` of type \`T\`.
 *
 * \`Ok\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link ok} factory function. The phantom type parameter \`E\` has no runtime
 * representation; the \`ok()\` factory produces \`Ok<T, never>\`, where \`never\` extends any \`E\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error (phantom on Ok; defaults to \`never\` from the factory).
 *
 * @example
 * \`\`\`ts
 * import { ok } from '@hex-di/result';
 *
 * const result = ok(42);
 * console.log(result.isOk());  // true
 * console.log(result.value);   // 42
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-004}
 */
export interface Ok<T, E> {
	readonly _tag: "Ok";
	readonly value: T;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Ok<U, E>;
	mapErr<F>(f: (error: E) => F): Ok<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Ok<U, F>;
	flatten<U, E2>(this: Ok<Result<U, E2>, E>): Result<U, E | E2>;
	flip(): Err<E, T>;
	and<U, F>(other: Result<U, F>): Result<U, E | F>;
	or<U, F>(other: Result<U, F>): Ok<T, E>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Result<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Ok<T, E>;
	andTee(f: (value: T) => void): Ok<T, E>;
	orTee(f: (error: E) => void): Ok<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Result<T, E | F>;
	inspect(f: (value: T) => void): Ok<T, E>;
	inspectErr(f: (error: E) => void): Ok<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): A;
	unwrapOr<U>(defaultValue: U): T;
	unwrapOrElse<U>(f: (error: E) => U): T;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): T;
	expectErr(message: string): never;
	orDie(): T;
	toNullable(): T;
	toUndefined(): T;
	intoTuple(): [
		null,
		T
	];
	merge(): T;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): Some<T>;
	toOptionErr(): None;
	transpose<U>(this: Ok<Option\$1<U>, E>): Option\$1<Result<U, E>>;
	toJSON(): {
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	};
	[Symbol.iterator](): Generator<never, T, unknown>;
}
/**
 * The failure variant of {@link Result}. Contains an \`error\` of type \`E\`.
 *
 * \`Err\` is an interface, not a class -- instances are plain objects with closure-based methods
 * created by the {@link err} factory function. The phantom type parameter \`T\` has no runtime
 * representation; the \`err()\` factory produces \`Err<never, E>\`, where \`never\` extends any \`T\`.
 *
 * @typeParam T - The type of the success value (phantom on Err; defaults to \`never\` from the factory).
 * @typeParam E - The type of the error.
 *
 * @example
 * \`\`\`ts
 * import { err } from '@hex-di/result';
 *
 * const result = err('not found');
 * console.log(result.isErr());  // true
 * console.log(result.error);    // 'not found'
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-005}
 */
export interface Err<T, E> {
	readonly _tag: "Err";
	readonly error: E;
	readonly [RESULT_BRAND]: true;
	isOk(): this is Ok<T, E>;
	isErr(): this is Err<T, E>;
	isOkAnd(predicate: (value: T) => boolean): boolean;
	isErrAnd(predicate: (error: E) => boolean): boolean;
	map<U>(f: (value: T) => U): Err<U, E>;
	mapErr<F>(f: (error: E) => F): Err<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U, onErr: (error: E) => F): Err<U, F>;
	flatten<U, E2>(this: Err<Result<U, E2>, E>): Err<U, E>;
	flip(): Ok<E, T>;
	and<U, F>(other: Result<U, F>): Err<U, E>;
	or<U, F>(other: Result<U, F>): Result<T | U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F>): Err<U, E>;
	orElse<U, F>(f: (error: E) => Result<U, F>): Result<T | U, F>;
	andTee(f: (value: T) => void): Err<T, E>;
	orTee(f: (error: E) => void): Err<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F>): Err<T, E>;
	inspect(f: (value: T) => void): Err<T, E>;
	inspectErr(f: (error: E) => void): Err<T, E>;
	match<A, B>(onOk: (value: T) => A, onErr: (error: E) => B): B;
	unwrapOr<U>(defaultValue: U): U;
	unwrapOrElse<U>(f: (error: E) => U): U;
	mapOr<U>(defaultValue: U, f: (value: T) => U): U;
	mapOrElse<U>(defaultF: (error: E) => U, f: (value: T) => U): U;
	contains(value: T): boolean;
	containsErr(error: E): boolean;
	expect(message: string): never;
	expectErr(message: string): E;
	orDie(): never;
	toNullable(): null;
	toUndefined(): undefined;
	intoTuple(): [
		E,
		null
	];
	merge(): E;
	toAsync(): ResultAsync<T, E>;
	asyncMap<U>(f: (value: T) => Promise<U>): ResultAsync<U, E>;
	asyncAndThen<U, F>(f: (value: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
	toOption(): None;
	toOptionErr(): Some<E>;
	transpose(): Some<Err<never, E>>;
	toJSON(): {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	};
	[Symbol.iterator](): Generator<Err<never, E>, never, unknown>;
}
/**
 * A discriminated union of {@link Ok} and {@link Err}.
 *
 * \`Result<T, E>\` represents either a success (\`Ok\`) holding a value of type \`T\`,
 * or a failure (\`Err\`) holding an error of type \`E\`. TypeScript narrows to the
 * correct variant after checking \`_tag\`, \`isOk()\`, or \`isErr()\`.
 *
 * @typeParam T - The type of the success value.
 * @typeParam E - The type of the error value.
 *
 * @example
 * \`\`\`ts
 * import { ok, err, type Result } from '@hex-di/result';
 *
 * function divide(a: number, b: number): Result<number, string> {
 *   if (b === 0) return err('division by zero');
 *   return ok(a / b);
 * }
 *
 * const result = divide(10, 2);
 * if (result.isOk()) {
 *   console.log(result.value); // 5
 * }
 * \`\`\`
 *
 * @since v1.0.0
 * @see {@link spec/result/behaviors/01-types-and-guards.md | BEH-01-006}
 */
export type Result<T, E> = Ok<T, E> | Err<T, E>;
/**
 * Extracts the success type \`T\` from a \`Result<T, E>\` or \`ResultAsync<T, E>\`.
 *
 * @example
 * \`\`\`ts
 * import { ok } from '@hex-di/result';
 * import type { InferOk } from '@hex-di/result';
 *
 * type R = ReturnType<typeof ok<number>>;
 * type T = InferOk<R>; // number
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOk<R> = R extends Result<infer T, unknown> ? T : R extends ResultAsync<infer T, unknown> ? T : never;
/**
 * Extracts the error type \`E\` from a \`Result<T, E>\` or \`ResultAsync<T, E>\`.
 *
 * @example
 * \`\`\`ts
 * import { err } from '@hex-di/result';
 * import type { InferErr } from '@hex-di/result';
 *
 * type R = ReturnType<typeof err<string>>;
 * type E = InferErr<R>; // string
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErr<R> = R extends Result<unknown, infer E> ? E : R extends ResultAsync<unknown, infer E> ? E : never;
/**
 * Extracts the \`Ok\` types from a tuple of \`Result\` or \`ResultAsync\` values as a mapped tuple.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferOkTuple } from '@hex-di/result';
 *
 * type Rs = [Result<number, string>, Result<boolean, Error>];
 * type Oks = InferOkTuple<Rs>; // [number, boolean]
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOkTuple<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = {
	[K in keyof T]: InferOk<T[K]>;
};
/**
 * Extracts the union of all \`Err\` types from a tuple of \`Result\` or \`ResultAsync\` values.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferErrUnion } from '@hex-di/result';
 *
 * type Rs = [Result<number, "a">, Result<boolean, "b">];
 * type Errs = InferErrUnion<Rs>; // "a" | "b"
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErrUnion<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = InferErr<T[number]>;
/**
 * Extracts the union of \`Ok\` types from a tuple of \`Result\` or \`ResultAsync\` values.
 * Useful for \`Result.any\` which returns a single Ok from the first success.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferOkUnion } from '@hex-di/result';
 *
 * type Rs = [Result<number, string>, Result<boolean, string>];
 * type OkU = InferOkUnion<Rs>; // number | boolean
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferOkUnion<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = InferOk<T[number]>;
/**
 * A non-empty array type that guarantees at least one element.
 * The first element is always present (\`T\`), followed by zero or more additional elements.
 *
 * @example
 * \`\`\`ts
 * import type { NonEmptyArray } from '@hex-di/result';
 *
 * const valid: NonEmptyArray<number> = [1, 2, 3]; // ok
 * // const invalid: NonEmptyArray<number> = [];    // type error
 *
 * function head<T>(arr: NonEmptyArray<T>): T {
 *   return arr[0]; // T, not T | undefined
 * }
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type NonEmptyArray<T> = [
	T,
	...T[]
];
/**
 * Extracts the \`Err\` types from a tuple of \`Result\` or \`ResultAsync\` values as a mapped tuple.
 * Useful for \`Result.any\` error collection.
 *
 * @example
 * \`\`\`ts
 * import type { Result, InferErrTuple } from '@hex-di/result';
 *
 * type Rs = [Result<number, "a">, Result<boolean, "b">];
 * type Errs = InferErrTuple<Rs>; // ["a", "b"]
 * \`\`\`
 *
 * @since v1.0.0
 * @see spec/result/type-system/utility.md
 */
export type InferErrTuple<T extends readonly (Result<unknown, unknown> | ResultAsync<unknown, unknown>)[]> = {
	[K in keyof T]: InferErr<T[K]>;
};
declare function all<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, InferErrUnion<R>>;
declare function allSettled<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, InferErrUnion<R>[]>;
declare function any<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkUnion<R>, InferErrTuple<R>>;
export type InferErrUnionFromRecord<R extends Record<string, Result<unknown, unknown>>> = InferErr<R[keyof R]>;
declare function collect<R extends Record<string, Result<unknown, unknown>>>(results: R): Result<{
	[K in keyof R]: InferOk<R[K]>;
}, InferErrUnionFromRecord<R>>;
declare function partition<T, E>(results: readonly Result<T, E>[]): [
	T[],
	E[]
];
declare function forEach<T, U, E>(items: readonly T[], f: (item: T, index: number) => Result<U, E>): Result<U[], E>;
declare function zipOrAccumulate<R extends readonly Result<unknown, unknown>[]>(...results: R): Result<InferOkTuple<R>, NonEmptyArray<InferErrUnion<R>>>;
declare class ResultAsync\$1<T, E> implements ResultAsync<T, E> {
	#private;
	private constructor();
	/**
	 * Creates a \`ResultAsync\` wrapping an \`Ok\` value.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.ok(42);
	 * const inner = await result; // Ok(42)
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static ok<T>(value: T): ResultAsync\$1<T, never>;
	/**
	 * Creates a \`ResultAsync\` wrapping an \`Err\` value.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.err("not found");
	 * const inner = await result; // Err("not found")
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static err<E>(error: E): ResultAsync\$1<never, E>;
	/**
	 * Wraps a \`Promise<T>\` that might reject into a \`ResultAsync\`.
	 *
	 * Resolution produces \`Ok(value)\`. Rejection produces \`Err(mapErr(reason))\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.fromPromise(
	 *   fetch("/api/users").then(r => r.json()),
	 *   (error) => \`Request failed: \${error}\`
	 * );
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromPromise<T, E>(promise: Promise<T>, mapErr: (error: unknown) => E): ResultAsync\$1<T, E>;
	/**
	 * Wraps a \`Promise<T>\` that is guaranteed to never reject into a \`ResultAsync\`.
	 *
	 * Resolution produces \`Ok(value)\`. Since the promise never rejects, the error
	 * type is \`never\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const result = ResultAsync.fromSafePromise(Promise.resolve(42));
	 * const inner = await result; // Ok(42)
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromSafePromise<T>(promise: Promise<T>): ResultAsync\$1<T, never>;
	/**
	 * Creates a ResultAsync from a Promise that resolves to a Result.
	 *
	 * This is useful when you have an async function that already returns Result
	 * values (e.g., sequential effect execution loops that check \`_tag\` and return
	 * early on error). It avoids the need for \`andThen\` flattening, which has
	 * inference issues in TypeScript 5.9.
	 *
	 * The promise must never reject — it should always resolve to either
	 * ok(value) or err(error).
	 *
	 * @param promise - A Promise that resolves to a Result<T, E>
	 * @returns A ResultAsync<T, E> wrapping the promise
	 */
	static fromResult<T, E>(promise: Promise<Result<T, E>>): ResultAsync\$1<T, E>;
	/**
	 * Wraps an async function that might throw into a function returning \`ResultAsync\`.
	 *
	 * Returns a new function with the same parameter types that returns \`ResultAsync\`
	 * instead of \`Promise\`. Rejections are caught and mapped via \`mapErr\`.
	 *
	 * @example
	 * \`\`\`ts
	 * import { ResultAsync } from '@hex-di/result';
	 *
	 * const safeReadFile = ResultAsync.fromThrowable(
	 *   async (path: string) => fs.promises.readFile(path, "utf-8"),
	 *   (error) => \`Read failed: \${error}\`
	 * );
	 *
	 * const result = safeReadFile("config.json");
	 * // ResultAsync<string, string>
	 * \`\`\`
	 *
	 * @since v1.0.0
	 * @see spec/result/behaviors/06-async.md — BEH-06-003
	 */
	static fromThrowable<A extends readonly unknown[], T, E>(fn: (...args: A) => Promise<T>, mapErr: (error: unknown) => E): (...args: A) => ResultAsync\$1<T, E>;
	static fromCallback<T, E>(fn: (callback: (error: E | null, value: T) => void) => void): ResultAsync\$1<T, E>;
	static race<R extends readonly ResultAsync\$1<unknown, unknown>[]>(...results: R): ResultAsync\$1<InferOkUnion<R>, InferErrUnion<R>>;
	static all: typeof all;
	static allSettled: typeof allSettled;
	static any: typeof any;
	static collect: typeof collect;
	static partition: typeof partition;
	static forEach: typeof forEach;
	static zipOrAccumulate: typeof zipOrAccumulate;
	then<A = Result<T, E>, B = never>(onfulfilled?: ((value: Result<T, E>) => A | PromiseLike<A>) | null | undefined, onrejected?: ((reason: unknown) => B | PromiseLike<B>) | null | undefined): PromiseLike<A | B>;
	map<U>(f: (value: T) => U | Promise<U>): ResultAsync\$1<U, E>;
	mapErr<F>(f: (error: E) => F | Promise<F>): ResultAsync\$1<T, F>;
	mapBoth<U, F>(onOk: (value: T) => U | Promise<U>, onErr: (error: E) => F | Promise<F>): ResultAsync\$1<U, F>;
	andThen<U, F>(f: (value: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync\$1<U, E | F>;
	orElse<U, F>(f: (error: E) => Result<U, F> | ResultAsync<U, F>): ResultAsync\$1<T | U, F>;
	andTee(f: (value: T) => void | Promise<void>): ResultAsync\$1<T, E>;
	orTee(f: (error: E) => void | Promise<void>): ResultAsync\$1<T, E>;
	andThrough<F>(f: (value: T) => Result<unknown, F> | ResultAsync<unknown, F>): ResultAsync\$1<T, E | F>;
	inspect(f: (value: T) => void): ResultAsync\$1<T, E>;
	inspectErr(f: (error: E) => void): ResultAsync\$1<T, E>;
	match<A, B>(onOk: (value: T) => A | Promise<A>, onErr: (error: E) => B | Promise<B>): Promise<A | B>;
	unwrapOr<U>(defaultValue: U): Promise<T | U>;
	unwrapOrElse<U>(f: (error: E) => U): Promise<T | U>;
	orDie(): Promise<T>;
	toNullable(): Promise<T | null>;
	toUndefined(): Promise<T | undefined>;
	intoTuple(): Promise<[
		null,
		T
	] | [
		E,
		null
	]>;
	merge(): Promise<T | E>;
	flatten<U>(this: ResultAsync\$1<Result<U, E>, E>): ResultAsync\$1<U, E>;
	flip(): ResultAsync\$1<E, T>;
	toJSON(): Promise<{
		_tag: "Ok";
		_schemaVersion: 1;
		value: T;
	} | {
		_tag: "Err";
		_schemaVersion: 1;
		error: E;
	}>;
}
/**
 * Context passed to effect functions after a reducer runs.
 */
export interface EffectContext<TState, TActions extends ActionMap<TState>, K extends keyof TActions> {
	readonly state: DeepReadonly<TState>;
	readonly prevState: DeepReadonly<TState>;
	readonly payload: TActions[K] extends (state: TState, payload: infer P) => TState ? P : void;
}
/**
 * Maps action names to effect functions.
 * Effects return void for sync effects or ResultAsync for async effects.
 */
export type EffectMap<TState, TActions extends ActionMap<TState>> = {
	[K in keyof TActions]: (context: EffectContext<TState, TActions, K>) => void | ResultAsync\$1<void, unknown>;
};
/**
 * Handler for effect failures. Receives context and bound actions
 * for dispatching compensating actions.
 */
export interface EffectErrorHandler<TState, TActions extends ActionMap<TState>> {
	(context: {
		readonly error: EffectFailedError;
		readonly actionName: keyof TActions & string;
		readonly state: DeepReadonly<TState>;
		readonly prevState: DeepReadonly<TState>;
		readonly actions: BoundActions<TState, TActions>;
	}): void;
}
/**
 * Service interface for effect ports.
 * Receives action events from all state ports.
 */
export interface ActionEffect {
	onAction(event: ActionEvent): void | Promise<void>;
}
/**
 * Event dispatched to effect ports after a state transition.
 */
export interface ActionEvent {
	readonly portName: string;
	readonly actionName: string;
	readonly payload: unknown;
	readonly prevState: unknown;
	readonly nextState: unknown;
	readonly timestamp: number;
	readonly phase: "action" | "effect-error";
	readonly error?: EffectFailedError;
	/** W3C Trace Context trace ID (present when @hex-di/tracing is active) */
	readonly traceId?: string;
}
/**
 * Interface for hydrating (restoring) and dehydrating (persisting) state.
 */
export interface StateHydrator {
	hydrate(portName: string): ResultAsync\$1<unknown, HydrationError>;
	dehydrate(portName: string, state: unknown): ResultAsync\$1<void, HydrationError>;
}
/**
 * Backend storage interface for hydration adapters.
 */
export interface HydrationStorage {
	get(key: string): unknown | undefined;
	set(key: string, value: unknown): void;
	remove(key: string): void;
}
/**
 * Immutable state container with undo/redo stacks.
 *
 * - \`past\`: States before the current present (most recent last).
 * - \`present\`: The current state.
 * - \`future\`: States undone from present (most recent first).
 */
export interface HistoryState<TState> {
	readonly past: readonly TState[];
	readonly present: TState;
	readonly future: readonly TState[];
}
/**
 * Standard undo/redo/push/clear action reducers for HistoryState.
 *
 * Satisfies \`ActionMap<HistoryState<TState>>\` constraint.
 */
export interface HistoryActions<TState> extends ActionMap<HistoryState<TState>> {
	readonly undo: (state: HistoryState<TState>) => HistoryState<TState>;
	readonly redo: (state: HistoryState<TState>) => HistoryState<TState>;
	readonly push: (state: HistoryState<TState>, payload: TState) => HistoryState<TState>;
	readonly clear: (state: HistoryState<TState>) => HistoryState<TState>;
}
/**
 * Union of all errors that can be delivered to StateServiceConfig.onError.
 * All members are \`_tag\`-discriminated plain objects.
 *
 * - \`EffectFailedError\`         — \`_tag: "EffectFailed"\` — an inline effect returned Err
 * - \`EffectErrorHandlerError\`   — \`_tag: "EffectErrorHandlerFailed"\` — the onEffectError handler itself threw
 * - \`EffectAdapterError\`        — \`_tag: "EffectAdapterFailed"\` — an effect adapter's onAction threw
 */
export type StoreRuntimeError = EffectFailedError | EffectErrorHandlerError | EffectAdapterError;
/**
 * A branded port type that serves as a compile-time contract for a service interface.
 *
 * The Port type uses TypeScript's structural typing with a branded property
 * to achieve nominal typing. Two ports are only compatible if they have:
 * 1. The same service interface type \`T\`
 * 2. The same port name \`TName\`
 *
 * @typeParam TName - The literal string type for the port name (defaults to \`string\`)
 * @typeParam T - The service interface type (phantom type - exists only at compile time)
 *
 * @remarks
 * - The \`__brand\` property carries both the service type and name in a tuple
 * - The \`__portName\` property exposes the name for debugging and error messages
 * - Both properties are readonly to prevent modification
 * - The brand symbol value is \`undefined\` at runtime (zero overhead)
 *
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link InferService} - Utility to extract the service type from a port
 * @see {@link InferPortName} - Utility to extract the name type from a port
 *
 * @example Direct type usage
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * // Create typed port tokens
 * type ConsoleLoggerPort = Port<'ConsoleLogger', Logger>;
 * type FileLoggerPort = Port<'FileLogger', Logger>;
 *
 * // These are type-incompatible despite same interface
 * declare const consolePort: ConsoleLoggerPort;
 * declare const filePort: FileLoggerPort;
 * // consolePort = filePort; // Type error!
 * \`\`\`
 *
 * @example With createPort (recommended)
 * \`\`\`typescript
 * // Use createPort for value + type duality
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerPortType = typeof LoggerPort;
 * \`\`\`
 */
export type Port<TName extends string, T> = {
	/**
	 * Brand property for nominal typing.
	 * Contains a tuple of [PortName, ServiceType] at the type level.
	 * Value is undefined at runtime.
	 */
	readonly __brand: [
		TName,
		T
	];
	/**
	 * The port name, exposed for debugging and error messages.
	 */
	readonly __portName: TName;
};
/**
 * Error type returned when type inference utilities receive a non-Port type.
 *
 * This branded error provides actionable guidance in IDE tooltips when users
 * accidentally pass incorrect types to InferService or InferPortName.
 *
 * @typeParam T - The type that was passed (preserved for debugging)
 *
 * @remarks
 * Instead of returning opaque \`never\`, this error type provides:
 * - Clear error message explaining what was expected
 * - The actual type that was received (for debugging)
 * - A hint about common mistakes (e.g., forgetting \`typeof\`)
 *
 * @example IDE tooltip when misused
 * \`\`\`typescript
 * type Result = InferService<string>;
 * // Hovering shows:
 * // {
 * //   __errorBrand: "NotAPortError";
 * //   __message: "Expected a Port type created with createPort() or port()";
 * //   __received: string;
 * //   __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
 * // }
 * \`\`\`
 */
export type NotAPortError<T> = {
	readonly __errorBrand: "NotAPortError";
	readonly __message: "Expected a Port type created with createPort() or port()";
	readonly __received: T;
	readonly __hint: "Use InferService<typeof YourPort>, not InferService<YourPort>";
};
/**
 * Extracts the service interface type from a Port type.
 *
 * This utility type uses conditional type inference to extract the phantom
 * type parameter \`T\` from a \`Port<T, TName>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the service from
 * @returns The service interface type \`T\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferPortName} - Companion utility to extract the port name
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type LoggerService = InferService<typeof LoggerPort>;
 * // LoggerService = Logger
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferService<string>;
 * // Invalid = NotAPortError<string>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferService<P> = P extends Port<infer _TName, infer T> ? T : NotAPortError<P>;
/**
 * Extracts the port name literal type from a Port type.
 *
 * This utility type uses conditional type inference to extract the name
 * type parameter \`TName\` from a \`Port<T, TName>\`. If the provided type is not
 * a valid Port, it returns a descriptive \`NotAPortError\` type.
 *
 * @typeParam P - The Port type to extract the name from
 * @returns The port name literal type \`TName\`, or \`NotAPortError<P>\` if P is not a Port
 *
 * @see {@link Port} - The port type this utility extracts from
 * @see {@link InferService} - Companion utility to extract the service type
 * @see {@link createPort} - Factory function to create port tokens
 * @see {@link NotAPortError} - The error type returned for invalid inputs
 *
 * @example Successful extraction
 * \`\`\`typescript
 * interface Logger {
 *   log(message: string): void;
 * }
 *
 * const LoggerPort = createPort<'Logger', Logger>('Logger');
 * type PortName = InferPortName<typeof LoggerPort>;
 * // PortName = 'Logger'
 * \`\`\`
 *
 * @example Error case (descriptive error type)
 * \`\`\`typescript
 * type Invalid = InferPortName<number>;
 * // Invalid = NotAPortError<number>
 * // IDE shows: { __errorBrand: "NotAPortError", __message: "Expected a Port...", ... }
 * \`\`\`
 */
export type InferPortName<P> = P extends Port<infer TName, infer _T> ? TName : NotAPortError<P>;
declare const __metadataKey: unique symbol;
/**
 * Discriminator for hexagonal architecture port types.
 *
 * - \`'inbound'\` - Driving ports (use cases, primary adapters)
 * - \`'outbound'\` - Driven ports (infrastructure, secondary adapters)
 *
 * @see {@link DirectedPort} - The port type that carries direction
 * @see {@link createInboundPort} - Factory for inbound ports
 * @see {@link createOutboundPort} - Factory for outbound ports
 */
export type PortDirection = "inbound" | "outbound";
/**
 * Optional metadata for documenting ports.
 *
 * Metadata provides human-readable documentation that can be used for:
 * - IDE tooltips and documentation
 * - Dependency graph visualization
 * - API documentation generation
 *
 * All properties are optional and readonly.
 *
 * @example
 * \`\`\`typescript
 * const UserServicePort = createInboundPort<'UserService', UserService>({
 *   name: 'UserService',
 *   description: 'Handles user CRUD operations',
 *   category: 'domain',
 *   tags: ['user', 'crud', 'core'],
 * });
 * \`\`\`
 */
export interface PortMetadata {
	/** Human-readable description of the port's purpose */
	readonly description?: string;
	/** Categorical grouping for organization */
	readonly category?: string;
	/** Searchable tags for filtering and discovery */
	readonly tags?: readonly string[];
}
/**
 * A port with hexagonal architecture direction and optional metadata.
 *
 * DirectedPort extends the base Port type with additional type-level branding:
 * - \`TDirection\` - Whether this is an inbound (driving) or outbound (driven) port
 * - Metadata association for documentation purposes
 *
 * DirectedPorts are structurally compatible with base Ports, enabling gradual
 * adoption without breaking existing code.
 *
 * @typeParam TName - The literal string type for the port name
 * @typeParam TService - The service interface type (phantom type)
 * @typeParam TDirection - 'inbound' or 'outbound'
 *
 * @see {@link InboundPort} - Convenience alias for inbound directed ports
 * @see {@link OutboundPort} - Convenience alias for outbound directed ports
 * @see {@link createInboundPort} - Factory for creating inbound ports
 * @see {@link createOutboundPort} - Factory for creating outbound ports
 *
 * @example
 * \`\`\`typescript
 * // DirectedPort is assignable to Port (backward compatible)
 * const port: DirectedPort<'Logger', Logger, 'inbound'> = createInboundPort({
 *   name: 'Logger',
 * });
 * const basePort: Port<'Logger', Logger> = port; // OK
 * \`\`\`
 */
export type DirectedPort<TName extends string, TService, TDirection extends PortDirection, TCategory extends string = string> = Port<TName, TService> & {
	readonly __directionBrand: TDirection;
	readonly __metadataKey: PortMetadata;
	readonly __categoryBrand: TCategory;
};
/**
 * Converts a tuple/array type to a union of its element types.
 *
 * @typeParam T - A tuple or array type
 * @returns Union of all element types, or \`never\` for empty array
 */
export type TupleToUnion<T extends readonly Port<string, unknown>[]> = T extends readonly [
] ? never : T[number];
/**
 * Discriminator for sync vs async factory functions.
 */
export type FactoryKind = "sync" | "async";
/**
 * Lifetime scope for an adapter's service instance.
 *
 * | Lifetime    | Description                                                      |
 * |-------------|------------------------------------------------------------------|
 * | \`singleton\` | One instance per container, shared across all resolutions        |
 * | \`scoped\`    | One instance per scope, isolated from parent and sibling scopes  |
 * | \`transient\` | New instance on every resolution                                 |
 */
export type Lifetime = "singleton" | "scoped" | "transient";
/**
 * Type representing empty dependencies (no required ports).
 *
 * This is a branded empty type that:
 * - IS assignable from empty object literals: \`const deps: EmptyDeps = {}\` ✓
 * - PREVENTS arbitrary key access: \`deps.nonExistent\` ✗ (type error)
 *
 * The brand uses \`?: never\` which means the property can only be satisfied
 * by omitting it entirely (since \`never\` has no values). This makes \`{}\`
 * assignable while preventing index access.
 */
export type EmptyDeps = {
	readonly __emptyDepsBrand?: never;
};
/**
 * Maps a union of Port types to an object type for dependency injection.
 *
 * When \`TRequires\` is \`never\` (no dependencies), returns \`EmptyDeps\` which
 * is a branded empty type that prevents arbitrary key access.
 *
 * When \`TRequires\` is a Port union, returns an object type with port names
 * as keys and service types as values.
 *
 * @example
 * \`\`\`typescript
 * // No dependencies - returns EmptyDeps (branded empty type)
 * type NoDeps = ResolvedDeps<never>;
 * const deps: NoDeps = {}; // ✓ OK
 * deps.anything; // ✗ Error: Property 'anything' does not exist
 *
 * // With dependencies - returns mapped object type
 * type WithDeps = ResolvedDeps<typeof LoggerPort | typeof DatabasePort>;
 * // { Logger: Logger; Database: Database }
 * \`\`\`
 */
export type ResolvedDeps<TRequires> = [
	TRequires
] extends [
	never
] ? EmptyDeps : {
	[TPort in TRequires as InferPortName<TPort> & string]: InferService<TPort>;
};
/**
 * Maps a tuple of Port types to a typed dependencies object.
 *
 * This is the canonical type for expressing "these ports -> this deps object"
 * across all HexDI libraries (store, flow, query). It composes \`TupleToUnion\`
 * and \`ResolvedDeps\` to convert a readonly tuple of ports into a keyed object
 * where port names are keys and service types are values.
 *
 * For empty tuples, returns \`EmptyDeps\` (branded empty type that prevents
 * arbitrary key access).
 *
 * @typeParam TRequires - A readonly tuple of Port types
 *
 * @example
 * \`\`\`typescript
 * const LoggerPort = createPort<Logger>('Logger');
 * const DbPort = createPort<Database>('Database');
 *
 * type Deps = PortDeps<readonly [typeof LoggerPort, typeof DbPort]>;
 * // { Logger: Logger; Database: Database }
 *
 * type NoDeps = PortDeps<readonly []>;
 * // EmptyDeps
 * \`\`\`
 */
export type PortDeps<TRequires extends readonly Port<string, unknown>[]> = ResolvedDeps<TupleToUnion<TRequires>>;
/**
 * A branded adapter type that captures the complete contract for a service implementation.
 *
 * ## Type Parameter Constraints
 *
 * | Parameter     | Constraint           | Purpose                                    |
 * |---------------|----------------------|--------------------------------------------|
 * | \`TProvides\`   | \`out\` (covariant)    | Port type this adapter implements          |
 * | \`TRequires\`   | invariant            | Union of required port types               |
 * | \`TLifetime\`   | \`extends Lifetime\`   | Declared lifetime (normalized for async) |
 * | \`TFactoryKind\`| \`extends FactoryKind\`| Must be "sync" | "async"                   |
 * | \`TClonable\`   | \`extends boolean\`    | Literal \`true\` or \`false\`                  |
 * | \`TRequiresTuple\`| derived            | Computed from TRequires for runtime array  |
 *
 * ## Variance Annotations
 *
 * The \`out\` modifier on \`TProvides\`, \`TFactoryKind\`, \`TClonable\`, and \`TRequiresTuple\`
 * marks them as covariant-only. This means:
 * - \`Adapter<DerivedPort, ...>\` is assignable to \`Adapter<BasePort, ...>\`
 * - Enables correct subtyping for adapters in collections
 *
 * \`TRequires\` is invariant (no modifier) because:
 * - The factory function both reads (contravariant) and returns (covariant) based on it
 * - Changing \`TRequires\` changes the factory signature bidirectionally
 *
 * ## Example
 *
 * \`\`\`typescript
 * // Full type signature of an adapter:
 * type LoggerAdapter = Adapter<
 *   typeof LoggerPort,  // TProvides: the port being implemented
 *   never,              // TRequires: no dependencies (never = empty union)
 *   "singleton",        // TLifetime: instance lifetime
 *   "sync",             // TFactoryKind: synchronous factory
 *   false,              // TClonable: not safe to shallow-clone
 *   readonly [],        // TRequiresTuple: empty tuple (computed from TRequires)
 *   never               // TError: no error channel (infallible factory)
 * >;
 * \`\`\`
 */
export type Adapter<out TProvides, TRequires, TLifetime extends string, // Widened to accept error message strings
out TFactoryKind extends FactoryKind = "sync", out TClonable extends boolean = false, out TRequiresTuple extends readonly unknown[] = [
	TRequires
] extends [
	never
] ? readonly [
] : readonly TRequires[], out TError = never> = {
	/**
	 * Brand property for nominal typing.
	 */
	readonly __adapterBrand?: [
		TProvides,
		TRequires,
		TLifetime,
		TFactoryKind,
		TClonable,
		TError
	];
	/**
	 * The port this adapter provides/implements.
	 */
	readonly provides: TProvides;
	/**
	 * The ports this adapter depends on.
	 */
	readonly requires: TRequiresTuple;
	/**
	 * The lifetime scope for this adapter's service instances.
	 *
	 * For sync factories, this is the declared lifetime.
	 * For async factories, this is either "singleton" (valid) or an error message
	 * string (invalid - when non-singleton lifetime was specified with async factory).
	 *
	 * The error string makes the adapter unusable with GraphBuilder, producing
	 * a compile-time error.
	 */
	readonly lifetime: TLifetime;
	/**
	 * The factory kind discriminator.
	 */
	readonly factoryKind: TFactoryKind;
	/**
	 * Factory function that creates the service instance.
	 */
	readonly factory: TFactoryKind extends "async" ? (deps: ResolvedDeps<TRequires>) => Promise<InferService<TProvides>> : (deps: ResolvedDeps<TRequires>) => InferService<TProvides>;
	/**
	 * Whether this adapter's service can be safely shallow-cloned.
	 *
	 * When \`true\`, the adapter's instances can be used with forked inheritance mode,
	 * which creates a shallow clone for child containers.
	 *
	 * When \`false\` (default), forked inheritance mode will fail at compile time,
	 * requiring the use of shared or isolated mode instead.
	 *
	 * @remarks
	 * Mark as clonable only for services that:
	 * - Have no resource handles (sockets, file handles, connections)
	 * - Have no external references that would become shared
	 * - Are value-like objects where shallow cloning produces valid instances
	 *
	 * @default false
	 */
	readonly clonable: TClonable;
	/**
	 * Optional finalizer function called during disposal.
	 */
	finalizer?(instance: InferService<TProvides>): void | Promise<void>;
};
/**
 * Structural interface matching ANY Adapter without using \`any\`.
 *
 * This uses TypeScript's variance rules to create a type that ALL Adapters
 * are assignable to:
 * - \`unknown\` in covariant positions (outputs/reads)
 * - \`never\` in contravariant positions (inputs/writes)
 *
 * When used as a constraint \`<A extends AdapterConstraint>\`, the generic parameter \`A\`
 * preserves the EXACT adapter type for full inference.
 *
 * @example
 * \`\`\`typescript
 * // All adapters match this constraint
 * function process<A extends AdapterConstraint>(adapter: A): InferAdapterProvides<A> {
 *   // A is inferred as exact adapter type, not widened to AdapterConstraint
 * }
 *
 * const result = process(LoggerAdapter);
 * // result is LoggerPort, not unknown!
 * \`\`\`
 *
 * @remarks
 * This follows the Effect-TS pattern of \`Layer.Any\`, \`Service.Any\` interfaces.
 * The key insight is that we only match the STRUCTURE of an Adapter, not its
 * exact type parameters, while preserving full type inference through generics.
 */
export interface AdapterConstraint {
	/**
	 * The port this adapter provides (read-only, covariant).
	 * Uses Port<string, unknown> as the widest Port type.
	 */
	readonly provides: Port<string, unknown>;
	/**
	 * The ports this adapter depends on (read-only, covariant).
	 * Each element is a Port with \`__portName\` for runtime identification.
	 */
	readonly requires: readonly Port<string, unknown>[];
	/**
	 * The lifetime scope (fixed union, all values assignable).
	 */
	readonly lifetime: Lifetime;
	/**
	 * The factory kind discriminator (fixed union, all values assignable).
	 */
	readonly factoryKind: FactoryKind;
	/**
	 * Factory function (contravariant in params, covariant in return).
	 * \`never[]\` params accept any function signature.
	 */
	readonly factory: (...args: never[]) => unknown;
	/**
	 * Whether this adapter's service can be safely shallow-cloned.
	 * Defaults to false for safety.
	 */
	readonly clonable: boolean;
	/**
	 * Optional finalizer (contravariant param accepts any instance type).
	 */
	finalizer?(instance: never): void | Promise<void>;
}
/**
 * Event emitted by a library inspector.
 *
 * Wraps library-specific events with source identification for the
 * container's unified event stream.
 */
export interface LibraryEvent {
	/** Library name (matches LibraryInspector.name) */
	readonly source: string;
	/** Library-specific event type string */
	readonly type: string;
	/** Library-specific event payload */
	readonly payload: Readonly<Record<string, unknown>>;
	/** Event timestamp (Date.now()) */
	readonly timestamp: number;
}
/**
 * Listener callback for library inspector events.
 */
export type LibraryEventListener = (event: LibraryEvent) => void;
/**
 * Protocol that all library inspectors implement to participate
 * in the container's unified inspection system.
 *
 * Libraries implement this interface to make their domain-specific
 * inspection data discoverable and queryable through the container.
 */
export interface LibraryInspector {
	/** Unique library identifier. Must be lowercase kebab-case. */
	readonly name: string;
	/**
	 * Returns a frozen snapshot of the library's current state.
	 * The shape is library-specific but always a frozen record.
	 */
	getSnapshot(): Readonly<Record<string, unknown>>;
	/**
	 * Subscribe to library-specific events.
	 * Returns an unsubscribe function.
	 * Optional -- libraries without push-based events omit this.
	 */
	subscribe?(listener: LibraryEventListener): () => void;
	/**
	 * Dispose the library inspector and clean up resources.
	 * Optional -- called when the container disposes.
	 */
	dispose?(): void;
}
/**
 * Store Tracing Bridge
 *
 * Adapts a @hex-di/tracing-compatible tracer to Store's StoreTracingHook.
 * This bridges the distributed tracing system with Store action tracing
 * without @hex-di/store depending directly on @hex-di/tracing.
 *
 * @packageDocumentation
 */
/**
 * Minimal tracer interface for Store tracing bridge.
 * Compatible with @hex-di/tracing's TracerLike and Flow's TracerLike.
 */
export interface StoreTracerLike {
	pushSpan(name: string, attributes?: Record<string, string>): void;
	popSpan(status: "ok" | "error"): void;
}
/**
 * Context returned from a tracing span start, carrying optional W3C trace IDs.
 */
export interface StoreSpanContext {
	readonly traceId?: string;
	readonly spanId?: string;
}
/**
 * Hook interface consumed by StateServiceImpl to instrument action dispatch.
 * Optional methods instrument atom updates, derived recomputation, and async fetches.
 */
export interface StoreTracingHook {
	onActionStart(portName: string, actionName: string, containerName: string): StoreSpanContext;
	onActionEnd(ok: boolean): void;
	onAtomUpdate?(portName: string, containerName: string): StoreSpanContext;
	onAtomUpdateEnd?(ok: boolean): void;
	onDerivedRecompute?(portName: string, containerName: string): StoreSpanContext;
	onDerivedRecomputeEnd?(ok: boolean): void;
	onAsyncDerivedFetch?(portName: string, containerName: string): StoreSpanContext;
	onAsyncDerivedFetchEnd?(ok: boolean): void;
}
/**
 * Configuration for the Store tracing bridge.
 */
export interface StoreTracingBridgeConfig {
	/**
	 * A StoreTracerLike implementation (from @hex-di/tracing or any compatible adapter).
	 */
	readonly tracer: StoreTracerLike;
	/**
	 * Optional function returning the current span context.
	 * Called after pushSpan to retrieve trace/span IDs.
	 */
	readonly getSpanContext?: () => StoreSpanContext;
	/**
	 * Optional filter to control which ports are traced.
	 * Return true to trace the port, false to skip.
	 */
	readonly filter?: (portName: string) => boolean;
	/**
	 * Optional scope ID to include in span attributes.
	 */
	readonly scopeId?: string;
}
/**
 * Creates a StoreTracingHook from a StoreTracerLike implementation.
 *
 * The bridge calls \`tracer.pushSpan()\` in \`onActionStart\` with attributes
 * \`store.port\`, \`store.action\`, \`store.container\`, and optionally \`store.scope_id\`.
 * Returns span context from \`config.getSpanContext?.() ?? {}\`.
 * Calls \`tracer.popSpan()\` in \`onActionEnd\`.
 *
 * @param config - The bridge configuration
 * @returns StoreTracingHook ready to pass to StateServiceConfig
 */
export declare function createStoreTracingBridge(config: StoreTracingBridgeConfig): StoreTracingHook;
export interface StoreInspectorAPI {
	/** Snapshot of all store state at this instant */
	getSnapshot(): StoreSnapshot;
	/** Snapshot of a single port's state */
	getPortState(portName: string): PortSnapshot | undefined;
	/** List all registered state ports with metadata */
	listStatePorts(): readonly StatePortInfo[];
	/** Subscriber dependency graph */
	getSubscriberGraph(): SubscriberGraph;
	/** Action history with optional filtering */
	getActionHistory(filter?: ActionHistoryFilter): readonly ActionHistoryEntry[];
	/** Subscribe to inspector events */
	subscribe(listener: StoreInspectorListener): () => void;
}
export type StoreInspectorListener = (event: StoreInspectorEvent) => void;
export interface StatePortInfo {
	readonly portName: string;
	readonly kind: "state" | "atom" | "derived" | "async-derived";
	readonly lifetime: "singleton" | "scoped";
	readonly subscriberCount: number;
	readonly hasEffects: boolean;
	readonly scopeId?: string;
}
export interface StoreSnapshot {
	readonly timestamp: number;
	readonly ports: readonly PortSnapshot[];
	readonly totalSubscribers: number;
	readonly pendingEffects: number;
}
export type PortSnapshot = StatePortSnapshot | AtomPortSnapshot | DerivedPortSnapshot | AsyncDerivedPortSnapshot;
export interface StatePortSnapshot {
	readonly kind: "state";
	readonly portName: string;
	readonly state: unknown;
	readonly subscriberCount: number;
	readonly actionCount: number;
	readonly lastActionAt: number | null;
	readonly scopeId?: string;
}
export interface AtomPortSnapshot {
	readonly kind: "atom";
	readonly portName: string;
	readonly value: unknown;
	readonly subscriberCount: number;
	readonly scopeId?: string;
}
export interface DerivedPortSnapshot {
	readonly kind: "derived";
	readonly portName: string;
	readonly value: unknown;
	readonly subscriberCount: number;
	readonly sourcePortNames: readonly string[];
	readonly isStale: boolean;
	readonly scopeId?: string;
}
export interface AsyncDerivedPortSnapshot {
	readonly kind: "async-derived";
	readonly portName: string;
	readonly status: "idle" | "loading" | "success" | "error";
	readonly data: unknown;
	readonly error: unknown | undefined;
	readonly subscriberCount: number;
	readonly sourcePortNames: readonly string[];
	readonly scopeId?: string;
}
export interface ActionHistoryEntry {
	readonly id: string;
	readonly portName: string;
	readonly actionName: string;
	readonly payload: unknown;
	readonly prevState: unknown;
	readonly nextState: unknown;
	readonly timestamp: number;
	readonly effectStatus: "none" | "pending" | "completed" | "failed";
	readonly effectError?: EffectFailedError;
	readonly parentId: string | null;
	readonly order: number;
	readonly traceId?: string;
	readonly spanId?: string;
}
export interface ActionHistoryFilter {
	readonly portName?: string;
	readonly actionName?: string;
	readonly since?: number;
	readonly until?: number;
	readonly effectStatus?: "none" | "pending" | "completed" | "failed";
	readonly limit?: number;
	readonly traceId?: string;
}
export interface ActionHistoryConfig {
	readonly maxEntries: number;
	readonly mode: "full" | "lightweight" | "off";
	readonly samplingRate?: number;
	readonly alwaysRecord?: {
		readonly effectStatus?: readonly ("failed" | "pending")[];
		readonly portNames?: readonly string[];
		readonly actionNames?: readonly string[];
	};
}
export interface ActionHistory {
	/** Record a new action entry. Returns true if recorded, false if skipped. */
	record(entry: ActionHistoryEntry): boolean;
	/** Query entries with optional filter */
	query(filter?: ActionHistoryFilter): readonly ActionHistoryEntry[];
	/** Clear all recorded entries */
	clear(): void;
	/** Current entry count */
	readonly size: number;
}
/**
 * Entry representing a registered store port in the registry.
 */
export interface StoreRegistryEntry {
	readonly portName: string;
	readonly adapter: object;
	readonly lifetime: "singleton" | "scoped";
	readonly requires: readonly string[];
	readonly writesTo: readonly string[];
	getSnapshot: () => PortSnapshot;
	getSubscriberCount: () => number;
	getHasEffects: () => boolean;
}
/**
 * Event emitted by the StoreRegistry when ports are registered/unregistered.
 */
export type StoreRegistryEvent = {
	readonly type: "port-registered";
	readonly entry: StoreRegistryEntry;
} | {
	readonly type: "port-unregistered";
	readonly portName: string;
} | {
	readonly type: "scoped-port-registered";
	readonly scopeId: string;
	readonly entry: StoreRegistryEntry;
} | {
	readonly type: "scope-unregistered";
	readonly scopeId: string;
};
/**
 * Listener callback for registry events.
 */
export type StoreRegistryListener = (event: StoreRegistryEvent) => void;
/**
 * Registry for tracking store port instances.
 */
export interface StoreRegistry {
	/** Register a singleton port entry. */
	register(entry: StoreRegistryEntry): void;
	/** Unregister a singleton port by name. */
	unregister(portName: string): void;
	/** Register a scoped port entry under a scope ID. */
	registerScoped(scopeId: string, entry: StoreRegistryEntry): void;
	/** Remove all port entries for a given scope ID. */
	unregisterScope(scopeId: string): void;
	/** Get all singleton entries. */
	getAll(): readonly StoreRegistryEntry[];
	/** Get all scoped entries for a given scope ID. */
	getAllScoped(scopeId: string): readonly StoreRegistryEntry[];
	/** Get a singleton entry by port name. */
	get(portName: string): StoreRegistryEntry | undefined;
	/** Subscribe to registry events. */
	subscribe(listener: StoreRegistryListener): Unsubscribe\$1;
	/** Dispose the registry, clearing all entries and listeners. */
	dispose(): void;
}
type Unsubscribe\$1 = () => void;
export interface SubscriberGraph {
	readonly correlationId: string;
	readonly nodes: readonly SubscriberNode[];
	readonly edges: readonly SubscriberEdge[];
}
export interface SubscriberNode {
	readonly id: string;
	readonly kind: "state" | "atom" | "derived" | "async-derived";
	readonly subscriberCount: number;
}
export interface SubscriberEdge {
	readonly from: string;
	readonly to: string;
	readonly type: "derives-from" | "subscribes-to" | "writes-to";
}
export type StoreInspectorEvent = {
	readonly type: "action-dispatched";
	readonly entry: ActionHistoryEntry;
} | {
	readonly type: "state-changed";
	readonly portName: string;
} | {
	readonly type: "subscriber-added";
	readonly portName: string;
	readonly count: number;
} | {
	readonly type: "subscriber-removed";
	readonly portName: string;
	readonly count: number;
} | {
	readonly type: "effect-completed";
	readonly portName: string;
	readonly actionName: string;
} | {
	readonly type: "effect-failed";
	readonly portName: string;
	readonly actionName: string;
	readonly error: EffectFailedError;
} | {
	readonly type: "async-derived-failed";
	readonly error: AsyncDerivedSelectError;
} | {
	readonly type: "snapshot-changed";
};
export interface PortRegistryEntry {
	readonly portName: string;
	readonly adapter: object;
	readonly lifetime: "singleton" | "scoped";
	readonly requires: readonly string[];
	readonly writesTo: readonly string[];
	getSnapshot: () => PortSnapshot;
	getSubscriberCount: () => number;
	getHasEffects: () => boolean;
}
/**
 * Extended inspector interface for internal use by adapters and services.
 * Provides mutation methods (registerPort, recordAction, emit, etc.) on
 * top of the read-only StoreInspectorAPI.
 */
export interface StoreInspectorInternal extends StoreInspectorAPI {
	/** Register a singleton port for inspection */
	registerPort(entry: PortRegistryEntry): void;
	/** Unregister a singleton port */
	unregisterPort(portName: string): void;
	/** Register a scoped port for inspection */
	registerScopedPort(scopeId: string, entry: PortRegistryEntry): void;
	/** Remove all entries for a scope */
	unregisterScope(scopeId: string): void;
	/** Record an action (called from adapter hooks) */
	recordAction(entry: ActionHistoryEntry): void;
	/** Emit an inspector event */
	emit(event: StoreInspectorEvent): void;
	/** Access to the action history for testing */
	readonly actionHistory: ActionHistory;
	/** Pending effects counter */
	incrementPendingEffects(): void;
	decrementPendingEffects(): void;
}
/**
 * Port definition for container registration of StoreInspectorAPI.
 */
export declare const StoreInspectorPort: DirectedPort<"StoreInspector", StoreInspectorAPI, "outbound">;
export type StoreInspectorPortDef = typeof StoreInspectorPort;
/**
 * Port definition for the internal inspector interface.
 * Used by adapter factories with \`inspection: true\` to auto-register ports
 * and auto-record actions.
 */
export declare const StoreInspectorInternalPort: DirectedPort<"StoreInspectorInternal", StoreInspectorInternal, "outbound">;
export type StoreInspectorInternalPortDef = typeof StoreInspectorInternalPort;
/**
 * Port definition for container registration of StoreRegistry.
 *
 * When registered in a graph, enables auto-discovery of store port adapters
 * without manual \`registerPort()\` calls.
 */
export declare const StoreRegistryPort: DirectedPort<"StoreRegistry", StoreRegistry, "outbound">;
export type StoreRegistryPortDef = typeof StoreRegistryPort;
/**
 * Port definition for the store tracing hook.
 * When registered in a graph, enables distributed tracing for store operations.
 */
export declare const StoreTracingHookPort: DirectedPort<"StoreTracingHook", StoreTracingHook, "outbound">;
export type StoreTracingHookPortDef = typeof StoreTracingHookPort;
/**
 * Port definition for the store library inspector bridge.
 *
 * When registered in a graph, provides a LibraryInspector that bridges
 * store inspection into the container's unified Library Inspector Protocol.
 */
export declare const StoreLibraryInspectorPort: DirectedPort<"StoreLibraryInspector", LibraryInspector, "outbound", "library-inspector">;
declare const __stateType: unique symbol;
declare const __actionsType: unique symbol;
declare const __atomType: unique symbol;
declare const __asyncDerivedErrorType: unique symbol;
/**
 * State port definition.
 * Extends DirectedPort with phantom types for state and action inference.
 */
export type StatePortDef<TName extends string, TState, TActions extends ActionMap<TState>> = DirectedPort<TName, StateService<TState, TActions>, "outbound"> & {
	readonly __stateType: TState;
	readonly __actionsType: TActions;
};
/**
 * Atom port definition.
 * Extends DirectedPort with phantom type for value inference.
 */
export type AtomPortDef<TName extends string, TValue> = DirectedPort<TName, AtomService<TValue>, "outbound"> & {
	readonly __atomType: TValue;
};
/**
 * Derived port definition.
 */
export type DerivedPortDef<TName extends string, TResult> = DirectedPort<TName, DerivedService<TResult>, "outbound">;
/**
 * Async derived port definition.
 * Extends DirectedPort with phantom type for error inference.
 */
export type AsyncDerivedPortDef<TName extends string, TResult, E = never> = DirectedPort<TName, AsyncDerivedService<TResult, E>, "outbound"> & {
	readonly __asyncDerivedErrorType: E;
};
/**
 * Linked derived (bidirectional) port definition.
 */
export type LinkedDerivedPortDef<TName extends string, TResult> = DirectedPort<TName, LinkedDerivedService<TResult>, "outbound">;
/** Extract state type from a state port. Returns never for non-state ports. */
export type InferStateType<P> = [
	P
] extends [
	{
		readonly __stateType: infer S;
	}
] ? S : never;
/** Extract actions type from a state port. Returns never for non-state ports. */
export type InferActionsType<P> = [
	P
] extends [
	{
		readonly __actionsType: infer A;
	}
] ? A : never;
/** Extract atom value type from an atom port. Returns never for non-atom ports. */
export type InferAtomType<P> = [
	P
] extends [
	{
		readonly __atomType: infer V;
	}
] ? V : never;
/** Extract derived result type from a derived port. Returns never for non-derived ports. */
export type InferDerivedType<P> = [
	P
] extends [
	DerivedPortDef<string, infer R>
] ? R : never;
/** Extract linked derived result type. Returns never for non-linked-derived ports. */
export type InferLinkedDerivedType<P> = [
	P
] extends [
	LinkedDerivedPortDef<string, infer R>
] ? R : never;
/** Extract async derived result type. Returns never for non-async-derived ports. */
export type InferAsyncDerivedType<P> = [
	P
] extends [
	AsyncDerivedPortDef<string, infer R, infer _E>
] ? R : never;
/** Extract async derived error type. Returns never for non-async-derived ports. */
export type InferAsyncDerivedErrorType<P> = [
	P
] extends [
	{
		readonly __asyncDerivedErrorType: infer E;
	}
] ? E : never;
export interface PortConfig<TName extends string> {
	readonly name: TName;
	readonly description?: string;
	readonly category?: string;
	readonly tags?: readonly string[];
}
/**
 * Creates a state port with typed state and actions.
 *
 * Uses curried form to allow explicit TState/TActions with inferred TName.
 *
 * @example
 * \`\`\`typescript
 * const CounterPort = createStatePort<CounterState, CounterActions>()({
 *   name: "Counter",
 * });
 * \`\`\`
 */
export declare function createStatePort<TState, TActions extends ActionMap<TState>>(): <const TName extends string>(config: PortConfig<TName>) => StatePortDef<TName, TState, TActions>;
/**
 * Creates an atom port for a single reactive value.
 *
 * @example
 * \`\`\`typescript
 * const ThemePort = createAtomPort<"light" | "dark">()({
 *   name: "Theme",
 * });
 * \`\`\`
 */
export declare function createAtomPort<TValue>(): <const TName extends string>(config: PortConfig<TName>) => AtomPortDef<TName, TValue>;
/**
 * Creates a derived port for computed values.
 *
 * @example
 * \`\`\`typescript
 * const CartTotalPort = createDerivedPort<CartTotal>()({
 *   name: "CartTotal",
 * });
 * \`\`\`
 */
export declare function createDerivedPort<TResult>(): <const TName extends string>(config: PortConfig<TName>) => DerivedPortDef<TName, TResult>;
/**
 * Creates an async derived port for async computed values.
 *
 * @example
 * \`\`\`typescript
 * const RatePort = createAsyncDerivedPort<ExchangeRate>()({
 *   name: "ExchangeRate",
 * });
 * \`\`\`
 */
export declare function createAsyncDerivedPort<TResult, E = never>(): <const TName extends string>(config: PortConfig<TName>) => AsyncDerivedPortDef<TName, TResult, E>;
/**
 * Creates a linked (bidirectional) derived port.
 *
 * @example
 * \`\`\`typescript
 * const FahrenheitPort = createLinkedDerivedPort<number>()({
 *   name: "Fahrenheit",
 * });
 * \`\`\`
 */
export declare function createLinkedDerivedPort<TResult>(): <const TName extends string>(config: PortConfig<TName>) => LinkedDerivedPortDef<TName, TResult>;
/**
 * Creates frozen reducer functions for undo/redo/push/clear operations.
 *
 * Reducer semantics:
 * - \`undo\`: pop from past → present, push old present → future. No-op if past empty.
 * - \`redo\`: pop from future → present, push old present → past. No-op if future empty.
 * - \`push\`: push present → past, payload → present, clear future.
 * - \`clear\`: empty past/future, keep present.
 */
export declare function createHistoryActions<TState>(): HistoryActions<TState>;
/**
 * Creates a history port wrapping any StatePortDef.
 *
 * The resulting port name is \`\${innerName}History\`.
 * State is \`HistoryState<TState>\` and actions are \`HistoryActions<TState>\`.
 */
export declare function createHistoryPort<TName extends string, TState, TActions extends ActionMap<TState>>(innerPort: StatePortDef<TName, TState, TActions>): StatePortDef<\`\${TName}History\`, HistoryState<TState>, HistoryActions<TState>>;
/**
 * Per-Container Isolated Reactive System Factory
 *
 * Ports alien-signals' module-level signal/computed/effect implementation
 * into an instance-scoped factory. Each call to \`createIsolatedReactiveSystem()\`
 * returns an independent reactive graph with its own batching, queue, and
 * subscriber tracking — eliminating cross-container interference.
 *
 * Built on \`createReactiveSystem\` from \`alien-signals/system\`, which provides
 * the low-level dependency graph primitives (link, unlink, propagate, checkDirty,
 * shallowPropagate). This module adds the signal/computed/effect layer on top,
 * using closure-scoped state instead of module globals.
 *
 * @packageDocumentation
 */
/**
 * An isolated reactive system instance.
 *
 * Each instance maintains its own dependency graph, batch queue, and
 * subscriber tracking. Signals created in one system cannot register
 * as dependencies in another system's computeds or effects.
 */
export interface ReactiveSystemInstance {
	/** Create a reactive signal with read/write function interface */
	signal<T>(initialValue: T): {
		(): T;
		(value: T): void;
	};
	/** Create a computed value that auto-tracks dependencies */
	computed<T>(getter: (previousValue?: T) => T): () => T;
	/** Create a reactive effect; returns a dispose function */
	effect(fn: () => void): () => void;
	/** Begin a batch — defers notifications until matching endBatch() */
	startBatch(): void;
	/** End a batch — flushes deferred notifications when outermost batch ends */
	endBatch(): void;
	/** Get the current active subscriber (for untracked reads) */
	getActiveSub(): ReactiveNode | undefined;
	/** Set the active subscriber; returns the previous one */
	setActiveSub(sub?: ReactiveNode): ReactiveNode | undefined;
}
export interface ReactiveNode {
	deps?: Link;
	depsTail?: Link;
	subs?: Link;
	subsTail?: Link;
	flags: number;
}
export interface Link {
	version: number;
	dep: ReactiveNode;
	sub: ReactiveNode;
	prevSub: Link | undefined;
	nextSub: Link | undefined;
	prevDep: Link | undefined;
	nextDep: Link | undefined;
}
/**
 * Creates a fully isolated reactive system.
 *
 * All state (cycle counter, batch depth, active subscriber, effect queue)
 * is closure-scoped to the returned instance. Two systems cannot interfere
 * with each other's batching, notification ordering, or dependency tracking.
 */
export declare function createIsolatedReactiveSystem(): ReactiveSystemInstance;
/**
 * Return type for store adapter factories.
 *
 * Generic over TName to preserve the port name through the type system.
 * This enables GraphBuilder to distinguish adapters (avoiding false duplicate
 * and self-dependency detection) while erasing the service type and requires.
 *
 * Built on \`Adapter<...>\` (not \`AdapterConstraint\`) so the \`__adapterBrand\`
 * property is present — required for \`InferAdapterProvides\` / \`InferAdapterRequires\`
 * pattern matching to succeed in the GraphBuilder validation pipeline.
 *
 * TRequires = \`never\` maps to \`requires: readonly []\` via the Adapter's default
 * TRequiresTuple computation, preventing false self-dependency detection.
 */
export type StoreAdapterResult<TName extends string = string> = Adapter<Port<TName, unknown>, never, Lifetime, "sync", boolean>;
/** Type for effect adapter branding */
export type EffectAdapterBrand = {
	readonly __effectBrand: true;
};
/**
 * Creates a state adapter providing StateService implementation.
 *
 * Generic over TState and TActions to preserve concrete types from the port definition.
 * Uses function overload to bridge between the generic public API and internal
 * createAdapter (which works with unknown).
 *
 * Effects can be provided as either:
 * - A static object (Partial<EffectMap<TState, TActions>>)
 * - A DI function (deps: Record<string, unknown>) => Partial<EffectMap<TState, TActions>>
 *
 * When \`inspection: true\`, the adapter auto-registers with StoreRegistry and auto-records
 * actions via StoreInspectorInternal.
 */
export declare function createStateAdapter<TName extends string, TState, TActions extends ActionMap<TState>, const TRequires extends readonly Port<string, unknown>[] = readonly [
]>(config: {
	readonly provides: StatePortDef<TName, TState, TActions>;
	readonly requires?: TRequires;
	readonly lifetime?: "singleton" | "scoped";
	readonly initial: TState;
	readonly actions: TActions;
	readonly effects?: Partial<EffectMap<TState, TActions>> | ((deps: PortDeps<TRequires>) => Partial<EffectMap<TState, TActions>>);
	readonly onEffectError?: (context: unknown) => void;
	readonly tracingHook?: StoreTracingHook;
	readonly inspection?: boolean;
	readonly reactiveSystem?: ReactiveSystemInstance;
}): StoreAdapterResult<TName>;
/**
 * Creates an atom adapter providing AtomService implementation.
 */
export declare function createAtomAdapter<TName extends string>(config: {
	readonly provides: AtomPortDef<TName, unknown>;
	readonly lifetime?: "singleton" | "scoped";
	readonly initial: unknown;
	readonly inspection?: boolean;
	readonly reactiveSystem?: ReactiveSystemInstance;
}): StoreAdapterResult<TName>;
/**
 * Creates a derived adapter providing DerivedService implementation.
 *
 * The adapter computes its value by calling \`select\` with resolved dependencies.
 * Recomputation occurs when any dependency changes.
 */
export declare function createDerivedAdapter<TPort extends DerivedPortDef<string, unknown>, const TRequires extends readonly Port<string, unknown>[]>(config: {
	readonly provides: TPort;
	readonly requires: TRequires;
	readonly select: (deps: PortDeps<TRequires>) => InferDerivedType<TPort>;
	readonly equals?: (a: InferDerivedType<TPort>, b: InferDerivedType<TPort>) => boolean;
	readonly lifetime?: "singleton" | "scoped";
	readonly inspection?: boolean;
	readonly reactiveSystem?: ReactiveSystemInstance;
}): StoreAdapterResult<InferPortName<TPort> & string>;
/**
 * Creates an async derived adapter providing AsyncDerivedService implementation.
 *
 * The adapter fetches data using \`select\`, which returns a ResultAsync.
 * It tracks loading/error status and supports retry and stale-while-revalidate.
 */
export declare function createAsyncDerivedAdapter<TPort extends AsyncDerivedPortDef<string, unknown, unknown>, const TRequires extends readonly Port<string, unknown>[]>(config: {
	readonly provides: TPort;
	readonly requires: TRequires;
	readonly select: (deps: PortDeps<TRequires>) => ResultAsync\$1<InferAsyncDerivedType<TPort>, InferAsyncDerivedErrorType<TPort>>;
	readonly staleTime?: number;
	readonly retryCount?: number;
	readonly retryDelay?: number | ((attempt: number) => number);
	readonly inspection?: boolean;
	readonly reactiveSystem?: ReactiveSystemInstance;
}): StoreAdapterResult<InferPortName<TPort> & string>;
/**
 * Creates a linked (bidirectional) derived adapter.
 *
 * Supports both read (select) and write (set -> write) operations.
 * The \`write\` function propagates changes back to source state.
 */
export declare function createLinkedDerivedAdapter<TPort extends LinkedDerivedPortDef<string, unknown>, const TRequires extends readonly Port<string, unknown>[]>(config: {
	readonly provides: TPort;
	readonly requires: TRequires;
	readonly select: (deps: PortDeps<TRequires>) => InferLinkedDerivedType<TPort>;
	readonly write: (value: InferLinkedDerivedType<TPort>, deps: PortDeps<TRequires>) => void;
	readonly writesTo?: readonly Port<string, unknown>[];
	readonly equals?: (a: InferLinkedDerivedType<TPort>, b: InferLinkedDerivedType<TPort>) => boolean;
	readonly inspection?: boolean;
	readonly reactiveSystem?: ReactiveSystemInstance;
}): StoreAdapterResult<InferPortName<TPort> & string>;
export interface CreateEffectAdapterConfig<TName extends string = string, TRequires extends readonly Port<string, unknown>[] = readonly Port<string, unknown>[]> {
	readonly provides: Port<TName, ActionEffect>;
	readonly requires?: TRequires;
	readonly factory: (deps: PortDeps<TRequires>) => ActionEffect;
	readonly inspection?: boolean;
}
/**
 * Creates an effect adapter for cross-cutting concerns.
 *
 * Effect adapters receive ActionEvents from all state ports and can
 * perform side effects (logging, analytics, persistence, etc.).
 */
export declare function createEffectAdapter<TName extends string, const TRequires extends readonly Port<string, unknown>[] = readonly [
]>(config: CreateEffectAdapterConfig<TName, TRequires>): StoreAdapterResult<TName>;
export interface CreateHydrationAdapterConfig<TName extends string = string> {
	readonly provides: Port<TName, StateHydrator>;
	readonly storage: HydrationStorage;
}
/**
 * Creates a hydration adapter for persisting and restoring state.
 *
 * The adapter wraps a synchronous HydrationStorage backend and exposes
 * async ResultAsync-based hydrate/dehydrate operations.
 */
export declare function createHydrationAdapter<TName extends string>(config: CreateHydrationAdapterConfig<TName>): StoreAdapterResult<TName>;
/**
 * Type guard: checks if an adapter is an effect adapter.
 */
export declare function isEffectAdapter(adapter: AdapterConstraint): adapter is AdapterConstraint & EffectAdapterBrand;
/**
 * Filters a list of adapters, returning only effect adapters.
 */
export declare function withEffectAdapters(adapters: readonly AdapterConstraint[]): readonly (AdapterConstraint & EffectAdapterBrand)[];
/**
 * Runs \`fn\` outside the current reactive tracking scope.
 *
 * When a \`system\` is provided, uses that system's subscriber tracking.
 * Otherwise uses the global alien-signals tracking.
 */
export declare function untracked<T>(fn: () => T, system?: ReactiveSystemInstance): T;
/** A reactive value that tracks dependents */
export interface Signal<T> {
	/** Read the current value and register as a dependency */
	get(): T;
	/** Write a new value and notify dependents */
	set(value: T): void;
	/** Read without tracking (no dependency registration) */
	peek(): T;
}
/**
 * Creates a reactive signal.
 *
 * @param initial - Initial signal value
 * @param system - Optional isolated reactive system. When provided, the signal
 *   lives in that system's dependency graph instead of the global one.
 */
export declare function createSignal<T>(initial: T, system?: ReactiveSystemInstance): Signal<T>;
/** A derived signal that auto-tracks dependencies */
export interface Computed<T> {
	/** Read the computed value (lazy, cached until deps change) */
	get(): T;
	/** Read without tracking */
	peek(): T;
}
/**
 * Creates a computed signal.
 *
 * @param fn - Computation function
 * @param system - Optional isolated reactive system
 */
export declare function createComputed<T>(fn: () => T, system?: ReactiveSystemInstance): Computed<T>;
/** A reactive effect that runs when tracked signals change */
export interface ReactiveEffect {
	/** Run the effect and track dependencies */
	run(): void;
	/** Stop tracking and dispose */
	dispose(): void;
}
/**
 * Creates a reactive effect.
 *
 * @param fn - Effect function (runs immediately and re-runs when deps change)
 * @param system - Optional isolated reactive system
 */
export declare function createEffect(fn: () => void, system?: ReactiveSystemInstance): ReactiveEffect;
/**
 * Shallow equality comparison for objects.
 *
 * @packageDocumentation
 */
/**
 * Compares two objects shallowly.
 * Returns true if all top-level properties are strictly equal.
 */
export declare function shallowEqual<T extends Record<string, unknown>>(a: T, b: T): boolean;
/**
 * Configure a callback for cross-container batch detection.
 *
 * When \`batch()\` is called with target A while target B is already in a batch,
 * alien-signals cannot isolate the two batches. The callback receives both
 * targets so diagnostics or warnings can be emitted.
 *
 * Pass \`null\` to disable detection.
 *
 * @param callback - The diagnostic callback, or \`null\` to disable.
 */
export declare function setBatchDiagnostics(callback: ((newTarget: object, existingTarget: object) => void) | null): void;
/**
 * Groups multiple state changes into a single notification cycle.
 *
 * Uses alien-signals batching primitives by default. When an explicit
 * \`system\` is provided, uses that system's isolated batching instead.
 *
 * When the batch function throws, deferred notifications are flushed
 * and a BatchExecutionError is returned as the Err variant of the Result.
 *
 * **Scope isolation:** When using an explicit \`ReactiveSystemInstance\`,
 * batching is fully isolated to that system's dependency graph.
 * Without a system, alien-signals' global batching is used and per-target
 * depth tracking via WeakMap provides diagnostic visibility.
 *
 * @param containerOrScope - The container or scope to associate batch depth with.
 *   Pass \`null\` for global-only mode (no per-target depth tracking).
 * @param fn - The function to execute within the batch.
 * @param system - Optional isolated reactive system to use for batching.
 */
export declare function batch(containerOrScope: object | null, fn: () => void, system?: ReactiveSystemInstance): Result<void, BatchExecutionFailed>;
/**
 * Returns \`true\` if the given target is currently inside a \`batch()\` call.
 *
 * @param target - The container or scope object to check.
 */
export declare function isInBatch(target: object): boolean;
/**
 * Returns the current batch nesting depth for the given target.
 *
 * Returns \`0\` when the target is not inside any batch.
 *
 * @param target - The container or scope object to check.
 */
export declare function getBatchDepth(target: object): number;
/**
 * Returns the set of targets currently in a batch.
 *
 * Useful for debugging and introspection. Since the internal tracking uses
 * a \`WeakMap\`, this function requires the caller to pass candidate targets
 * to check against.
 *
 * @param candidates - The targets to check for active batch membership.
 * @returns The subset of candidates that are currently inside a batch.
 */
export declare function batchTargets(candidates: readonly object[]): ReadonlySet<object>;
/**
 * Proxy-Based Path Tracking
 *
 * Records which property paths a selector accesses, enabling fine-grained
 * change detection that skips selector execution when only unrelated
 * parts of state change.
 *
 * @packageDocumentation
 */
/**
 * Result of tracking a selector's property accesses.
 */
export interface TrackingResult<S> {
	/** The value returned by the selector */
	readonly value: S;
	/** Dot-delimited property paths accessed during selector execution */
	readonly paths: ReadonlySet<string>;
}
/**
 * Creates a proxy that records all property access paths as dot-delimited strings.
 *
 * Nested object access creates child proxies with prefix propagation.
 * Symbol keys are ignored (only string keys tracked).
 * null/undefined intermediates stop recursion.
 * Works on frozen objects (get traps are allowed on frozen objects).
 */
export declare function createTrackingProxy<T>(state: T): {
	proxy: T;
	paths: Set<string>;
};
/**
 * Runs a selector through a tracking proxy, returning the result and
 * the set of property paths accessed during execution.
 */
export declare function trackSelector<T, S>(state: T, selector: (s: T) => S): TrackingResult<S>;
/**
 * Compares two objects only at the tracked paths using \`Object.is\`.
 *
 * Returns \`true\` if any tracked path has a different value between
 * \`prev\` and \`next\`. Returns \`false\` when all tracked paths are identical.
 */
export declare function hasPathChanged<T>(prev: T, next: T, paths: ReadonlySet<string>): boolean;
/**
 * Recursively freezes an object graph.
 * Returns the same reference typed as DeepReadonly for structural sharing.
 * Primitives and already-frozen objects pass through without modification.
 */
export declare function deepFreeze<T>(obj: T): DeepReadonly<T>;
export declare function createActionHistory(config: ActionHistoryConfig): ActionHistory;
/**
 * Minimal metadata the inspector collects from each registered adapter.
 */
export interface AdapterRegistration {
	readonly portName: string;
	readonly adapter: object;
	readonly requires: readonly string[];
	readonly writesTo: readonly string[];
	readonly subscriberCount: number;
}
/**
 * Builds a SubscriberGraph from adapter registrations.
 */
export declare function buildSubscriberGraph(registrations: readonly AdapterRegistration[]): SubscriberGraph;
export interface StoreInspectorConfig {
	readonly historyConfig?: ActionHistoryConfig;
	readonly registry?: StoreRegistry;
}
export declare function createStoreInspectorImpl(config?: StoreInspectorConfig): StoreInspectorInternal;
export interface CreateStoreInspectorAdapterConfig {
	readonly historyConfig?: ActionHistoryConfig;
	readonly registry?: StoreRegistry;
}
export interface StoreInspectorAdapterResult {
	/** The public StoreInspectorAPI for consumers */
	readonly api: StoreInspectorAPI;
	/** The internal interface for the runtime to hook into */
	readonly internal: StoreInspectorInternal;
}
/**
 * Creates a StoreInspectorAPI adapter.
 *
 * Returns both the public API (for consumers) and the internal interface
 * (for the store runtime to register ports and record actions).
 */
export declare function createStoreInspectorAdapter(config?: CreateStoreInspectorAdapterConfig): StoreInspectorAdapterResult;
/**
 * Pre-built frozen adapter for auto-registering StoreInspectorAPI with a GraphBuilder.
 * Does not depend on StoreRegistryPort — use this for simple setups
 * where manual \`registerPort()\` is acceptable.
 *
 * @example
 * \`\`\`typescript
 * const graph = GraphBuilder.create()
 *   .provide(StoreInspectorAdapter)
 *   .build();
 *
 * const inspector = container.resolve(StoreInspectorPort);
 * const snapshot = inspector.getSnapshot();
 * \`\`\`
 */
export declare const StoreInspectorAdapter: Adapter<typeof StoreInspectorPort, never, "singleton", "sync", false, readonly [
]>;
/**
 * Inspector adapter that depends on StoreRegistryPort for auto-discovery.
 * When the registry is resolved, the inspector auto-populates its port list
 * from registered entries and subscribes for future changes.
 *
 * @example
 * \`\`\`typescript
 * const graph = GraphBuilder.create()
 *   .provide(StoreRegistryAdapter)
 *   .provide(StoreInspectorWithRegistryAdapter)
 *   .provide(myStateAdapter)
 *   .build();
 *
 * const inspector = container.resolve(StoreInspectorPort);
 * // Auto-discovers ports registered with the StoreRegistry
 * \`\`\`
 */
export declare const StoreInspectorWithRegistryAdapter: Adapter<typeof StoreInspectorPort, typeof StoreRegistryPort, "singleton", "sync", false, readonly [
	typeof StoreRegistryPort
]>;
/**
 * Adapter that provides StoreInspectorInternal (the extended mutation API).
 * Depends on StoreRegistryPort so the inspector auto-discovers registered ports.
 *
 * Used by adapter factories with \`inspection: true\` to get access to
 * \`recordAction\`, \`emit\`, and \`incrementPendingEffects\`/\`decrementPendingEffects\`.
 */
export declare const StoreInspectorInternalAdapter: Adapter<typeof StoreInspectorInternalPort, typeof StoreRegistryPort, "singleton", "sync", false, readonly [
	typeof StoreRegistryPort
]>;
/**
 * Creates a StoreRegistry instance for tracking store port adapters.
 *
 * @returns A new StoreRegistry
 */
export declare function createStoreRegistry(): StoreRegistry;
/**
 * DI Adapter that provides a StoreRegistry singleton.
 *
 * Register this adapter in a GraphBuilder to make StoreRegistryPort resolvable:
 *
 * @example
 * \`\`\`typescript
 * const graph = GraphBuilder.create()
 *   .provide(StoreRegistryAdapter)
 *   .build();
 *
 * const registry = container.resolve(StoreRegistryPort);
 * const ports = registry.getAll();
 * \`\`\`
 */
export declare const StoreRegistryAdapter: Adapter<typeof StoreRegistryPort, never, "singleton", "sync", false, readonly [
]>;
/**
 * Structural type guard for StoreInspectorInternal.
 * Checks for the \`recordAction\` and \`emit\` methods which are unique to the internal interface.
 */
export declare function isStoreInspectorInternal(value: unknown): value is StoreInspectorInternal;
/**
 * Structural type guard for StoreRegistry.
 * Checks for the \`register\` and \`getAll\` methods.
 */
export declare function isStoreRegistry(value: unknown): value is StoreRegistry;
/**
 * Structural type guard for StoreTracingHook.
 * Checks for the mandatory \`onActionStart\` and \`onActionEnd\` methods.
 */
export declare function isStoreTracingHook(value: unknown): value is StoreTracingHook;
/**
 * Extracts StoreInspectorInternal from a deps value, returning undefined if not valid.
 */
export declare function extractStoreInspectorInternal(value: unknown): StoreInspectorInternal | undefined;
/**
 * Extracts StoreRegistry from a deps value, returning undefined if not valid.
 */
export declare function extractStoreRegistry(value: unknown): StoreRegistry | undefined;
/**
 * Extracts StoreTracingHook from a deps value, returning undefined if not valid.
 */
export declare function extractStoreTracingHook(value: unknown): StoreTracingHook | undefined;
/**
 * Creates a LibraryInspector that bridges StoreInspectorAPI
 * into the container's unified Library Inspector Protocol.
 *
 * The returned inspector:
 * - Reports \`name: "store"\`
 * - Exposes store snapshot data via \`getSnapshot()\`
 * - Forwards store inspector events to subscribers as LibraryEvents
 * - \`dispose()\` is a no-op (StoreInspectorAPI has no cleanup)
 *
 * @param inspector - The StoreInspectorAPI instance to bridge
 * @returns A LibraryInspector for the store library
 *
 * @example
 * \`\`\`typescript
 * const libraryInspector = createStoreLibraryInspector(storeInspector);
 * container.inspector.registerLibrary(libraryInspector);
 *
 * const snapshot = libraryInspector.getSnapshot();
 * // { timestamp: ..., ports: [...], totalSubscribers: 5, pendingEffects: 0 }
 * \`\`\`
 */
export declare function createStoreLibraryInspector(inspector: StoreInspectorAPI): LibraryInspector;
/**
 * Pre-built frozen adapter for StoreLibraryInspectorPort.
 *
 * Depends on StoreInspectorPort and produces a LibraryInspector bridge
 * via createStoreLibraryInspector. Because StoreLibraryInspectorPort
 * has \`category: "library-inspector"\`, the container's afterResolve hook
 * will auto-register it with the unified inspection protocol.
 *
 * @example
 * \`\`\`typescript
 * const graph = GraphBuilder.create()
 *   .provide(StoreInspectorAdapter)
 *   .provide(StoreLibraryInspectorAdapter)
 *   .build();
 *
 * // Auto-registered on first resolve thanks to category: "library-inspector"
 * const inspector = container.resolve(StoreLibraryInspectorPort);
 * \`\`\`
 */
export declare const StoreLibraryInspectorAdapter: Adapter<typeof StoreLibraryInspectorPort, typeof StoreInspectorPort, "singleton", "sync", false, readonly [
	typeof StoreInspectorPort
]>;
/**
 * Creates a frozen adapter that provides StoreTracingHookPort.
 * The adapter wraps a StoreTracerLike via createStoreTracingBridge.
 */
export declare function createStoreTracingHookAdapter(config: {
	readonly tracer: StoreTracerLike;
	readonly filter?: (portName: string) => boolean;
}): Adapter<typeof StoreTracingHookPort, never, "singleton", "sync", false, readonly [
]>;
/**
 * Maps MCP resource URIs to their response types.
 */
export interface StoreMcpResourceMap {
	readonly "hexdi://store/snapshot": StoreSnapshot;
	readonly "hexdi://store/ports": readonly StatePortInfo[];
	readonly "hexdi://store/graph": SubscriberGraph;
	readonly "hexdi://store/history": readonly ActionHistoryEntry[];
}
/**
 * Known MCP resource URI strings.
 */
export type StoreMcpResourceUri = keyof StoreMcpResourceMap;
/**
 * Handler that resolves MCP resource URIs to inspector data.
 */
export interface StoreMcpResourceHandler {
	resolveSnapshot(params?: ActionHistoryFilter): StoreSnapshot;
	resolvePorts(): readonly StatePortInfo[];
	resolveGraph(): SubscriberGraph;
	resolveHistory(params?: ActionHistoryFilter): readonly ActionHistoryEntry[];
	readonly supportedUris: readonly StoreMcpResourceUri[];
}
/**
 * Creates a StoreMcpResourceHandler from a StoreInspectorAPI.
 *
 * The handler maps resource operations to the appropriate inspector method:
 * - \`resolveSnapshot()\` → \`inspector.getSnapshot()\`
 * - \`resolvePorts()\` → \`inspector.listStatePorts()\`
 * - \`resolveGraph()\` → \`inspector.getSubscriberGraph()\`
 * - \`resolveHistory(filter?)\` → \`inspector.getActionHistory(filter?)\`
 */
export declare function createStoreMcpResourceHandler(inspector: StoreInspectorAPI): StoreMcpResourceHandler;

export {};
}`;
