/**
 * Build script: Extract `.d.ts` files from hex-di packages and embed them
 * as string constants in `packages/playground/src/editor/type-definitions.ts`.
 *
 * Usage:
 *   npx tsx scripts/bundle-playground-types.ts
 *
 * This script:
 * 1. Reads each package's dist/ directory for `.d.ts` files
 * 2. Concatenates them into a single `declare module "..." { ... }` block
 * 3. Writes the result into `type-definitions.ts` as embedded string constants
 *
 * @see spec/playground/03-code-editor.md Section 12
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const OUTPUT_PATH = join(ROOT, "packages/playground/src/editor/type-definitions.ts");

const PACKAGES = [
  { name: "@hex-di/core", dir: "packages/core" },
  { name: "@hex-di/graph", dir: "packages/graph" },
  { name: "@hex-di/runtime", dir: "packages/runtime" },
  { name: "@hex-di/result", dir: "packages/result" },
  { name: "@hex-di/flow", dir: "libs/flow/core" },
  { name: "@hex-di/store", dir: "libs/store/core" },
  { name: "@hex-di/query", dir: "libs/query/core" },
  { name: "@hex-di/saga", dir: "libs/saga/core" },
  { name: "@hex-di/tracing", dir: "packages/tracing" },
  { name: "@hex-di/logger", dir: "packages/logger" },
] as const;

/**
 * Recursively collects all `.d.ts` file paths under a given directory.
 */
function collectDtsFiles(dir: string): string[] {
  const results: string[] = [];
  if (!existsSync(dir)) {
    return results;
  }
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...collectDtsFiles(full));
    } else if (entry.endsWith(".d.ts")) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Extracts the public type definitions from a package's dist/ directory
 * and wraps them in a `declare module` block.
 */
function extractPackageTypes(packageName: string, packageDir: string): string {
  const distDir = join(ROOT, packageDir, "dist");
  const dtsFiles = collectDtsFiles(distDir);

  if (dtsFiles.length === 0) {
    console.warn(`  Warning: No .d.ts files found for ${packageName} in ${distDir}`);
    return `declare module "${packageName}" { /* no types found — build the package first */ }`;
  }

  // Read the main index.d.ts if it exists, otherwise concatenate all
  const indexDts = dtsFiles.find(f => f.endsWith("index.d.ts"));
  const content = indexDts
    ? readFileSync(indexDts, "utf-8")
    : dtsFiles.map(f => readFileSync(f, "utf-8")).join("\n");

  return `declare module "${packageName}" {\n${content}\n}`;
}

function main(): void {
  console.warn("Bundling playground type definitions...\n");

  const entries: Array<[string, string]> = [];

  for (const pkg of PACKAGES) {
    console.warn(`  Processing ${pkg.name} (${pkg.dir})...`);
    const types = extractPackageTypes(pkg.name, pkg.dir);
    entries.push([pkg.name, types]);
  }

  // Generate the output file
  const escapedEntries = entries.map(([name, dts]) => {
    const escaped = dts.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
    return `  ["${name}", \`${escaped}\`]`;
  });

  const output = `/**
 * Bundled TypeScript type definitions for hex-di packages.
 *
 * AUTO-GENERATED by scripts/bundle-playground-types.ts
 * Do not edit manually.
 *
 * @see spec/playground/03-code-editor.md Section 12
 */

// ---------------------------------------------------------------------------
// Monaco language types (minimal interface to avoid importing full Monaco)
// ---------------------------------------------------------------------------

/** Minimal interface for Monaco TypeScript defaults. */
interface MonacoTypescriptDefaults {
  addExtraLib(content: string, filePath?: string): void;
}

/** Minimal interface for the Monaco TypeScript language API we need. */
export interface MonacoTypescriptLanguage {
  readonly typescriptDefaults: MonacoTypescriptDefaults;
}

// ---------------------------------------------------------------------------
// Package list
// ---------------------------------------------------------------------------

const PACKAGES = [
  "@hex-di/core",
  "@hex-di/graph",
  "@hex-di/runtime",
  "@hex-di/result",
  "@hex-di/flow",
  "@hex-di/store",
  "@hex-di/query",
  "@hex-di/saga",
  "@hex-di/tracing",
  "@hex-di/logger",
] as const;

export type HexDiPackageName = (typeof PACKAGES)[number];

// ---------------------------------------------------------------------------
// Bundled type definitions
// ---------------------------------------------------------------------------

export const typeDefinitions: ReadonlyMap<string, string> = new Map<string, string>([
${escapedEntries.join(",\n")},
]);

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

export function registerTypeDefinitions(
  ts: MonacoTypescriptLanguage,
): void {
  for (const [packageName, dts] of typeDefinitions) {
    const filePath = \`file:///node_modules/\${packageName}/index.d.ts\`;
    ts.typescriptDefaults.addExtraLib(dts, filePath);
  }
}
`;

  writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.warn(`\nWrote ${entries.length} type definition bundles to ${OUTPUT_PATH}`);
}

main();
