/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "HexDI",
  "tagline": "Type-Safe Dependency Injection for TypeScript",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "markdown": {
    "format": "detect",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "url": "https://hexdi.dev",
  "baseUrl": "/",
  "organizationName": "leaderiop",
  "projectName": "hex-di",
  "plugins": [
    null
  ],
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "HexDI is a type-safe dependency injection framework for TypeScript. Catch dependency errors at compile time with full type inference and zero runtime overhead."
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "keywords",
        "content": "dependency injection, TypeScript, type-safe, DI, IoC, inversion of control, hexagonal architecture, ports and adapters, React DI, compile-time validation"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "author",
        "content": "HexDI Contributors"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "robots",
        "content": "index, follow"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "theme-color",
        "content": "#020408"
      }
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "../../docs",
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "docs",
          "editUrl": "https://github.com/leaderiop/hex-di/tree/main/docs/"
        },
        "blog": {
          "path": "blog",
          "routeBasePath": "blog",
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "title": "HexDI Blog",
            "description": "Engineering updates, tutorials, and release notes from the HexDI team",
            "copyright": "Copyright 2026 HexDI Contributors"
          },
          "blogTitle": "HexDI Blog",
          "blogDescription": "Engineering updates, tutorials, and release notes from the HexDI team",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All Posts",
          "editUrl": "https://github.com/leaderiop/hex-di/tree/main/websites/core/",
          "tags": "tags.yml"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "lastmod": "date",
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexDocs": true,
        "indexPages": true,
        "indexBlog": true,
        "blogRouteBasePath": "/blog",
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true,
        "docsRouteBasePath": "/docs",
        "searchBarShortcut": true,
        "searchBarShortcutHint": true,
        "searchBarPosition": "right",
        "searchResultLimits": 8,
        "searchResultContextMaxLength": 50,
        "removeDefaultStopWordFilter": false,
        "removeDefaultStemmer": false
      }
    ]
  ],
  "themeConfig": {
    "image": "img/hexdi-social-card.png",
    "metadata": [
      {
        "name": "og:type",
        "content": "website"
      },
      {
        "name": "og:site_name",
        "content": "HexDI"
      },
      {
        "name": "og:title",
        "content": "HexDI - Type-Safe Dependency Injection for TypeScript"
      },
      {
        "name": "og:description",
        "content": "Catch dependency errors at compile time, not runtime. Build robust TypeScript applications with full type inference and zero runtime overhead."
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:title",
        "content": "HexDI - Type-Safe Dependency Injection for TypeScript"
      },
      {
        "name": "twitter:description",
        "content": "Catch dependency errors at compile time, not runtime. Build robust TypeScript applications with full type inference and zero runtime overhead."
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "navbar": {
      "title": "HexDI",
      "logo": {
        "alt": "HexDI Logo",
        "src": "img/logo.svg",
        "width": 40,
        "height": 40
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/docs/api",
          "position": "left",
          "label": "API"
        },
        {
          "to": "/docs/examples",
          "position": "left",
          "label": "Examples"
        },
        {
          "type": "dropdown",
          "label": "Libraries",
          "position": "left",
          "items": [
            {
              "label": "Result",
              "href": "https://result.hexdi.dev"
            },
            {
              "label": "Flow",
              "href": "https://flow.hexdi.dev"
            },
            {
              "label": "Guard",
              "href": "https://guard.hexdi.dev"
            },
            {
              "label": "Saga",
              "href": "https://saga.hexdi.dev"
            },
            {
              "label": "Query",
              "href": "https://query.hexdi.dev"
            },
            {
              "label": "Store",
              "href": "https://store.hexdi.dev"
            },
            {
              "label": "Logger",
              "href": "https://logger.hexdi.dev"
            },
            {
              "label": "Tracing",
              "href": "https://tracing.hexdi.dev"
            },
            {
              "label": "Clock",
              "href": "https://clock.hexdi.dev"
            },
            {
              "label": "Crypto",
              "href": "https://crypto.hexdi.dev"
            },
            {
              "label": "HTTP Client",
              "href": "https://http-client.hexdi.dev"
            }
          ]
        },
        {
          "to": "/blog",
          "position": "left",
          "label": "Blog"
        },
        {
          "to": "/presentations",
          "position": "left",
          "label": "Presentations"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "https://github.com/leaderiop/hex-di",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started"
            },
            {
              "label": "API Reference",
              "to": "/docs/api"
            },
            {
              "label": "Guides",
              "to": "/docs/guides"
            },
            {
              "label": "Examples",
              "to": "/docs/examples"
            }
          ]
        },
        {
          "title": "Ecosystem",
          "items": [
            {
              "label": "Result",
              "href": "https://result.hexdi.dev"
            },
            {
              "label": "Flow",
              "href": "https://flow.hexdi.dev"
            },
            {
              "label": "Guard",
              "href": "https://guard.hexdi.dev"
            },
            {
              "label": "Saga",
              "href": "https://saga.hexdi.dev"
            },
            {
              "label": "Query",
              "href": "https://query.hexdi.dev"
            },
            {
              "label": "Store",
              "href": "https://store.hexdi.dev"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/leaderiop/hex-di"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/leaderiop/hex-di/discussions"
            },
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "License",
              "href": "https://github.com/leaderiop/hex-di/blob/main/LICENSE"
            }
          ]
        }
      ],
      "copyright": "Copyright 2026 HexDI Contributors. MIT License."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "typescript",
        "tsx",
        "jsx",
        "diff",
        "shell-session"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "error-line",
          "block": {
            "start": "error-start",
            "end": "error-end"
          }
        },
        {
          "className": "code-block-success-line",
          "line": "success-line",
          "block": {
            "start": "success-start",
            "end": "success-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
